/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
export {MenuActionItem} from './MenuActionItem.js';
export type {MenuActionItemProps} from './MenuActionItem.js';
