/**
 * Tecton MenuActionItem.
 *
 * Helper component for custom item rendering with consistent styling.
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {DropdownMenuItem as BaseMenuActionItem} from '@astryxdesign/core/DropdownMenu';
import {resolveIcon, type TectonIconRef} from '../../icons/renderIcon.js';

type MenuActionItemBaseProps = ComponentProps<typeof BaseMenuActionItem>;

/** Props for {@link MenuActionItem}. */
export interface MenuActionItemProps extends Omit<
  MenuActionItemBaseProps,
  'icon'
> {
  /**
   * Icon to display before the label. Takes a Tecton glyph name or an SVG
   * component.
   */
  icon?: TectonIconRef;
}

export function MenuActionItem({icon, ...rest}: MenuActionItemProps) {
  return (
    <BaseMenuActionItem
      {...(rest as MenuActionItemBaseProps)}
      icon={resolveIcon(icon)}
    />
  );
}

MenuActionItem.displayName = 'MenuActionItem';
