/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
import {describe, expect, it} from 'vitest';
import {CodeBlock} from './CodeBlock.js';

describe('CodeBlock', () => {
  it('is a component', () => {
    expect(typeof CodeBlock).toBe('function');
  });

  it('names itself for the React tree', () => {
    expect(CodeBlock.displayName).toBe('CodeBlock');
  });
});
