/**
 * Tecton ToggleButtonBar.
 *
 * Groups toggle buttons for exclusive (single) or multi-select behavior.
 * Uses discriminated union on type for type-safe value/onChange.
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {ToggleButtonGroup as BaseToggleButtonBar} from '@astryxdesign/core/ToggleButton';

type ToggleButtonBarBaseProps = ComponentProps<typeof BaseToggleButtonBar>;

/** Props for {@link ToggleButtonBar}. */
export type ToggleButtonBarProps = ToggleButtonBarBaseProps;

export function ToggleButtonBar(props: ToggleButtonBarProps) {
  return <BaseToggleButtonBar {...props} />;
}

ToggleButtonBar.displayName = 'ToggleButtonBar';
