/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
export {PowerSearch} from './PowerSearch.js';
export type {PowerSearchProps} from './PowerSearch.js';
