/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
import {describe, expect, it} from 'vitest';
import {PowerSearch} from './PowerSearch.js';

describe('PowerSearch', () => {
  it('is a component', () => {
    expect(typeof PowerSearch).toBe('function');
  });

  it('names itself for the React tree', () => {
    expect(PowerSearch.displayName).toBe('PowerSearch');
  });
});
