/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
export {TopNavItem} from './TopNavItem.js';
export type {TopNavItemProps} from './TopNavItem.js';
