/**
 * Tecton TopNavItem.
 *
 * Navigation link item for use in TopNav startContent: renders as an anchor
 * with hover and selected states.
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {TopNavItem as BaseTopNavItem} from '@astryxdesign/core/TopNav';
import {tectonIconNode, type TectonIconRef} from '../../icons/renderIcon.js';

type TopNavItemBaseProps = ComponentProps<typeof BaseTopNavItem>;

/** Props for {@link TopNavItem}. */
export interface TopNavItemProps extends Omit<TopNavItemBaseProps, 'icon'> {
  /**
   * Optional icon to display before the label. Takes a Tecton glyph name
   * or an SVG component.
   */
  icon?: TectonIconRef | TopNavItemBaseProps['icon'];
}

export function TopNavItem({icon, ...rest}: TopNavItemProps) {
  return (
    <BaseTopNavItem
      {...(rest as TopNavItemBaseProps)}
      icon={tectonIconNode(icon) as TopNavItemBaseProps['icon']}
    />
  );
}

TopNavItem.displayName = 'TopNavItem';
