/**
 * Tecton ContextMenuRadioGroup.
 *
 * ContextMenuRadioGroup is published as part of the Tecton surface.
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {ContextMenuRadioGroup as BaseContextMenuRadioGroup} from '@astryxdesign/core/ContextMenu';

type ContextMenuRadioGroupBaseProps = ComponentProps<
  typeof BaseContextMenuRadioGroup
>;

/** Props for {@link ContextMenuRadioGroup}. */
export type ContextMenuRadioGroupProps = ContextMenuRadioGroupBaseProps;

export function ContextMenuRadioGroup(props: ContextMenuRadioGroupProps) {
  return <BaseContextMenuRadioGroup {...props} />;
}

ContextMenuRadioGroup.displayName = 'ContextMenuRadioGroup';
