/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
export {ContextMenuRadioGroup} from './ContextMenuRadioGroup.js';
export type {ContextMenuRadioGroupProps} from './ContextMenuRadioGroup.js';
