/**
 * `@tecton/react/Pagination` — the `Pagination` module, as the design system publishes it.
 *
 * @generated by packages/react/scripts/generate-modules.mjs — do not edit.
 */
export * from '@astryxdesign/core/Pagination';
