/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
export {TopNavHeading} from './TopNavHeading.js';
export type {TopNavHeadingProps} from './TopNavHeading.js';
