/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
/** @type {import('@tecton/docs').ComponentDoc} */
export const docs = {
  name: 'TopNavHeading',
  displayName: 'TopNavHeading',
  group: 'TopNav',
  category: 'Navigation',
  keywords: ['topnavheading'],
  usage: {
    description:
      'Product/suite/account heading for the TopNav heading slot. Supports smart interaction boundary logic: logo, heading text, superheading/subheading with independent links, and an optional menu popover with automatic chevron indicator.',
  },
  props: [
    {
      name: 'logo',
      type: 'ReactNode',
      description:
        'Logo element to display before the heading text. Can be an image, NavIcon, or any ReactNode.',
    },
    {
      name: 'heading',
      type: 'string',
      description: 'Product/app name displayed as the primary heading text.',
    },
    {
      name: 'headingHref',
      type: 'string',
      description:
        'Link for the heading text (e.g. product home). When no menu is present and this is the only href, the whole heading becomes one clickable link.',
    },
    {
      name: 'superheading',
      type: 'string',
      description:
        'Text above the heading (e.g. suite name). Rendered in a smaller secondary style.',
    },
    {
      name: 'superheadingHref',
      type: 'string',
      description:
        'Link for the superheading text (e.g. suite home). When provided alongside a menu, renders as an independent inline link.',
    },
    {
      name: 'subheading',
      type: 'string',
      description:
        'Text below the heading (e.g. account context). Rendered in a smaller secondary style.',
    },
    {
      name: 'subheadingHref',
      type: 'string',
      description:
        'Link for the subheading text. When provided alongside a menu, renders as an independent inline link.',
    },
    {
      name: 'headerEndContent',
      type: 'ReactNode',
      description:
        'Content rendered at the trailing edge of the heading row (e.g. a badge or status indicator).',
    },
    {
      name: 'menu',
      type: 'ReactNode',
      description:
        'Menu content shown in a popover dropdown. When provided, a chevron indicator appears automatically. Interaction boundary is determined by the presence of hrefs: no hrefs means the whole header is the trigger; with hrefs, links are independent and the chevron area is the trigger.',
    },
    {
      name: 'as',
      type: 'LinkComponentType',
      description:
        'Custom component to render instead of <a>. Overrides the provider-level default set by LinkProvider. Must accept href, className, style, and children props.',
    },
    {
      name: 'xstyle',
      type: 'StyleXStyles',
      description:
        'StyleX styles for layout customization. Must be a stylex.create() value.',
    },
  ],
  examples: ['TopNavHeadingBasic', 'TopNavHeadingShowcase'],
  notes: [
    'Generated wrapper: Tecton publishes this component with its behaviour unchanged, under Tecton names and with Tecton glyphs on its icon props.',
  ],
};
