/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
import {describe, expect, it} from 'vitest';
import {TopNavHeading} from './TopNavHeading.js';

describe('TopNavHeading', () => {
  it('is a component', () => {
    expect(typeof TopNavHeading).toBe('function');
  });

  it('names itself for the React tree', () => {
    expect(TopNavHeading.displayName).toBe('TopNavHeading');
  });
});
