/**
 * Tecton TopNavHeading.
 *
 * Product/suite/account heading for the TopNav heading slot. Supports smart
 * interaction boundary logic: logo, heading text, superheading/subheading
 * with independent links, and an optional menu popover with automatic
 * chevron indicator.
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {TopNavHeading as BaseTopNavHeading} from '@astryxdesign/core/TopNav';

type TopNavHeadingBaseProps = ComponentProps<typeof BaseTopNavHeading>;

/** Props for {@link TopNavHeading}. */
export type TopNavHeadingProps = TopNavHeadingBaseProps;

export function TopNavHeading(props: TopNavHeadingProps) {
  return <BaseTopNavHeading {...props} />;
}

TopNavHeading.displayName = 'TopNavHeading';
