/**
 * Tecton OverflowList.
 *
 * A horizontal list that automatically hides items when they exceed the
 * available width. Use OverflowList for breadcrumbs, toolbars, tag lists, or
 * any row that needs to collapse gracefully at smaller sizes.
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {OverflowList as BaseOverflowList} from '@astryxdesign/core/OverflowList';

type OverflowListBaseProps = ComponentProps<typeof BaseOverflowList>;

/** Props for {@link OverflowList}. */
export type OverflowListProps = OverflowListBaseProps;

export function OverflowList(props: OverflowListProps) {
  return <BaseOverflowList {...props} />;
}

OverflowList.displayName = 'OverflowList';
