/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
import {describe, expect, it} from 'vitest';
import {OverflowList} from './OverflowList.js';

describe('OverflowList', () => {
  it('is a component', () => {
    expect(typeof OverflowList).toBe('function');
  });

  it('names itself for the React tree', () => {
    expect(OverflowList.displayName).toBe('OverflowList');
  });
});
