/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
export {MetadataList} from './MetadataList.js';
export type {MetadataListProps} from './MetadataList.js';
