/**
 * Tecton MetadataList.
 *
 * MetadataList displays key-value pairs for object attributes like quality,
 * condition, and status, in a structured layout. Use it for detail panels,
 * settings summaries, and record information.
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {MetadataList as BaseMetadataList} from '@astryxdesign/core/MetadataList';

type MetadataListBaseProps = ComponentProps<typeof BaseMetadataList>;

/** Props for {@link MetadataList}. */
export type MetadataListProps = MetadataListBaseProps;

export function MetadataList(props: MetadataListProps) {
  return <BaseMetadataList {...props} />;
}

MetadataList.displayName = 'MetadataList';
