/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
import {describe, expect, it} from 'vitest';
import {MetadataList} from './MetadataList.js';

describe('MetadataList', () => {
  it('is a component', () => {
    expect(typeof MetadataList).toBe('function');
  });

  it('names itself for the React tree', () => {
    expect(MetadataList.displayName).toBe('MetadataList');
  });
});
