/**
 * Tecton AvatarStatusDot.
 *
 * Size-aware status indicator dot that reads avatar size from context and
 * scales proportionally. Each variant pairs a colour with a distinct
 * built-in shape (filled, ring, minus) so status is never conveyed by colour
 * alone (WCAG 1.4.1).
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {AvatarStatusDot as BaseAvatarStatusDot} from '@astryxdesign/core/Avatar';
import {tectonIconNode, type TectonIconRef} from '../../icons/renderIcon.js';

type AvatarStatusDotBaseProps = ComponentProps<typeof BaseAvatarStatusDot>;

/** Props for {@link AvatarStatusDot}. */
export interface AvatarStatusDotProps extends Omit<
  AvatarStatusDotBaseProps,
  'icon'
> {
  /**
   * Icon centered inside the dot (hidden at tiny sizes). A rendered icon
   * replaces the built-in shape glyph, so use a different icon per status.
   * Takes a Tecton glyph name or an SVG component.
   */
  icon?: TectonIconRef | AvatarStatusDotBaseProps['icon'];
}

export function AvatarStatusDot({icon, ...rest}: AvatarStatusDotProps) {
  return (
    <BaseAvatarStatusDot
      {...(rest as AvatarStatusDotBaseProps)}
      icon={tectonIconNode(icon) as AvatarStatusDotBaseProps['icon']}
    />
  );
}

AvatarStatusDot.displayName = 'AvatarStatusDot';
