/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
/** @type {import('@tecton/docs').ComponentDoc} */
export const docs = {
  name: 'ContextMenuCheckboxItem',
  displayName: 'ContextMenuCheckboxItem',
  group: 'ContextMenuCheckboxItem',
  category: 'Overlay',
  keywords: ['contextmenucheckboxitem'],
  usage: {
    description:
      'ContextMenuCheckboxItem is published as part of the Tecton surface.',
  },
  props: [],
  examples: [],
  notes: [
    'Generated wrapper: Tecton publishes this component with its behaviour unchanged, under Tecton names and with Tecton glyphs on its icon props.',
  ],
};
