/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
import {describe, expect, it} from 'vitest';
import {ContextMenuCheckboxItem} from './ContextMenuCheckboxItem.js';

describe('ContextMenuCheckboxItem', () => {
  it('is a component', () => {
    expect(typeof ContextMenuCheckboxItem).toBe('function');
  });

  it('names itself for the React tree', () => {
    expect(ContextMenuCheckboxItem.displayName).toBe('ContextMenuCheckboxItem');
  });
});
