/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
export {ContextMenuCheckboxItem} from './ContextMenuCheckboxItem.js';
export type {ContextMenuCheckboxItemProps} from './ContextMenuCheckboxItem.js';
