/**
 * Tecton HoverCard.
 *
 * HoverCard shows additional information when the user hovers or focuses a
 * trigger element. Use it for profile cards, link summaries, or inline
 * definitions where the user needs more context without navigating away.
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {HoverCard as BaseHoverCard} from '@astryxdesign/core/HoverCard';

type HoverCardBaseProps = ComponentProps<typeof BaseHoverCard>;

/** Props for {@link HoverCard}. */
export type HoverCardProps = HoverCardBaseProps;

export function HoverCard(props: HoverCardProps) {
  return <BaseHoverCard {...props} />;
}

HoverCard.displayName = 'HoverCard';
