/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
export {HoverCard} from './HoverCard.js';
export type {HoverCardProps} from './HoverCard.js';
