/**
 * Tecton TableBody.
 *
 * <tbody> wrapper for children mode. Holds the data rows. A row must sit
 * inside a section: <table> cannot contain a <tr> directly, because the HTML
 * parser inserts an implied <tbody> when it parses server-rendered markup
 * and React does not when it renders on the client, so rows written straight
 * into Table mismatch on hydration. The data-driven data={...} mode renders
 * this element itself; in children mode it is yours to supply.
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {TableBody as BaseTableBody} from '@astryxdesign/core/Table';

type TableBodyBaseProps = ComponentProps<typeof BaseTableBody>;

/** Props for {@link TableBody}. */
export type TableBodyProps = TableBodyBaseProps;

export function TableBody(props: TableBodyProps) {
  return <BaseTableBody {...props} />;
}

TableBody.displayName = 'TableBody';
