/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
import {describe, expect, it} from 'vitest';
import {TableBody} from './TableBody.js';

describe('TableBody', () => {
  it('is a component', () => {
    expect(typeof TableBody).toBe('function');
  });

  it('names itself for the React tree', () => {
    expect(TableBody.displayName).toBe('TableBody');
  });
});
