/**
 * Tecton Tokenizer.
 *
 * Tokenizer is a multi-select input that lets users search, select, and
 * manage multiple items displayed as removable chips. Use it when users need
 * to build a set of selections from a searchable data source, like adding
 * team members, applying tags, or choosing filters.
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {Tokenizer as BaseTokenizer} from '@astryxdesign/core/Tokenizer';
import {resolveIcon, type TectonIconRef} from '../../icons/renderIcon.js';

type TokenizerBaseProps = ComponentProps<typeof BaseTokenizer>;

/** Props for {@link Tokenizer}. */
export interface TokenizerProps extends Omit<TokenizerBaseProps, 'startIcon'> {
  /**
   * Icon to display at the start of the input, before any tokens. Accepts
   * a semantic icon name, an SVG icon component, or a ReactNode directly.
   * Takes a Tecton glyph name or an SVG component.
   */
  startIcon?: TectonIconRef;
}

export function Tokenizer({startIcon, ...rest}: TokenizerProps) {
  return (
    <BaseTokenizer
      {...(rest as TokenizerBaseProps)}
      startIcon={resolveIcon(startIcon)}
    />
  );
}

Tokenizer.displayName = 'Tokenizer';
