/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
export {Markdown} from './Markdown.js';
export type {MarkdownProps} from './Markdown.js';
