/**
 * Tecton ChatMessageList.
 *
 * Presentational message container with density context and infinite scroll
 * support. Provides role="log" with aria-live="polite" for accessibility. A
 * flex spacer pushes messages to the bottom when the list isn't full; set
 * align="top" to start messages at the top instead.
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {ChatMessageList as BaseChatMessageList} from '@astryxdesign/core/Chat';

type ChatMessageListBaseProps = ComponentProps<typeof BaseChatMessageList>;

/** Props for {@link ChatMessageList}. */
export type ChatMessageListProps = ChatMessageListBaseProps;

export function ChatMessageList(props: ChatMessageListProps) {
  return <BaseChatMessageList {...props} />;
}

ChatMessageList.displayName = 'ChatMessageList';
