/**
 * Third-party glyph name → Tecton glyph name.
 *
 * The example blocks Tecton's examples are ported from draw their icons from
 * two general-purpose icon sets. Tecton has one icon set — 131 glyphs the
 * design delivered — so every icon in a ported example is substituted for the
 * closest Tecton glyph, and the substitution is recorded in
 * `docs/engineering/ported-examples.log`.
 *
 * A name that is not in this table falls back to `SUBSTITUTE_FALLBACK`, which
 * is also recorded. Adding a row here is how you improve a substitution.
 */

/** When nothing better fits: a neutral mark that reads as "something here". */
export const SUBSTITUTE_FALLBACK = 'diamond-mark';

export const ICON_SUBSTITUTIONS = {
  // --- navigation and chrome ---------------------------------------------
  MagnifyingGlassIcon: 'search',
  Search: 'search',
  DocumentMagnifyingGlassIcon: 'search',
  XMarkIcon: 'close',
  X: 'close',
  Bars3Icon: 'menu',
  Bars3BottomLeftIcon: 'menu',
  Bars4Icon: 'list',
  Menu: 'menu',
  EllipsisHorizontalIcon: 'more-vert',
  MoreHorizontal: 'more-vert',
  HomeIcon: 'home',
  Home: 'home',
  HomeModernIcon: 'home',
  ChevronDownIcon: 'chevron-down',
  ChevronDown: 'chevron-down',
  ChevronUpIcon: 'chevron-up',
  ChevronUp: 'chevron-up',
  ChevronLeftIcon: 'chevron-left',
  ChevronLeft: 'chevron-left',
  ChevronRightIcon: 'chevron-right',
  ChevronRight: 'chevron-right',
  ChevronsLeft: 'chevron-left-small',
  ChevronsRight: 'chevron-right-small',
  ArrowUpIcon: 'arrow-up',
  ArrowUp: 'arrow-up',
  ArrowDownIcon: 'arrow-down',
  ArrowDown: 'arrow-down',
  ArrowLeftIcon: 'arrow-left',
  ArrowLeft: 'arrow-left',
  ArrowRightIcon: 'arrow-right',
  ArrowRight: 'arrow-right',
  ArrowUpDown: 'caret-up-down',
  ArrowsUpDownIcon: 'caret-up-down',
  ArrowUturnLeftIcon: 'undo',
  ArrowPathIcon: 'rotate',
  ArrowTopRightOnSquareIcon: 'open-in-new',
  ExternalLink: 'open-in-new',
  ArrowsPointingOutIcon: 'expand-content',
  ArrowTrendingDownIcon: 'trend',
  ArrowDownTrayIcon: 'export-upload',
  ArrowDownOnSquareIcon: 'export-upload',
  FolderArrowDownIcon: 'export-upload',
  Download: 'export-upload',

  // --- status and feedback -----------------------------------------------
  CheckIcon: 'check',
  Check: 'check',
  CheckCheck: 'check-circle',
  CheckCircleIcon: 'check-circle',
  CheckCircle: 'check-circle',
  CheckBadgeIcon: 'check-circle',
  XCircleIcon: 'cancel-circle',
  XCircle: 'cancel-circle',
  CircleX: 'cancel-circle',
  ExclamationTriangleIcon: 'warning',
  AlertTriangle: 'warning',
  InformationCircleIcon: 'info',
  Info: 'info',
  QuestionMarkCircleIcon: 'info',
  MinusIcon: 'remove',
  PlusIcon: 'add',
  Plus: 'add',
  PlusCircleIcon: 'add-circle',
  StopIcon: 'diamond-mark',
  Square: 'checkbox-outline-blank',
  ClockIcon: 'history',
  Clock: 'history',

  // --- editing ------------------------------------------------------------
  PencilIcon: 'edit-square',
  Pencil: 'edit-square',
  PencilSquareIcon: 'edit-square',
  TrashIcon: 'delete',
  Trash: 'delete',
  DocumentDuplicateIcon: 'copy',
  ClipboardDocumentIcon: 'copy',
  ClipboardIcon: 'copy',
  ClipboardDocumentCheckIcon: 'copy',
  Copy: 'copy',
  ScissorsIcon: 'design',
  BoldIcon: 'annotate',
  ItalicIcon: 'annotate',
  UnderlineIcon: 'annotate',
  StrikethroughIcon: 'annotate',
  PaintBrushIcon: 'design',
  SwatchIcon: 'design',
  GripVertical: 'drag-indicator',
  SlidersHorizontal: 'controls',
  AdjustmentsHorizontalIcon: 'controls',
  Wrench: 'engineering',
  WrenchScrewdriverIcon: 'engineering',

  // --- content ------------------------------------------------------------
  DocumentTextIcon: 'reports-analytics',
  DocumentIcon: 'reports-analytics',
  BookOpenIcon: 'reports-analytics',
  BuildingLibraryIcon: 'facility',
  FolderIcon: 'folder',
  Folder: 'folder',
  FolderPlusIcon: 'folder-new',
  PhotoIcon: 'image',
  ImageIcon: 'image',
  Image: 'image',
  PaperClipIcon: 'link',
  LinkIcon: 'link',
  CodeBracketIcon: 'code',
  CommandLineIcon: 'code',
  CpuChipIcon: 'node',
  CircleStackIcon: 'database',
  ServerStackIcon: 'database',
  TableCellsIcon: 'view-column',
  TableIcon: 'view-column',
  Table2: 'view-column',
  ViewColumnsIcon: 'view-column',
  Columns: 'view-column',
  Columns3: 'view-column',
  Squares2X2Icon: 'view-module',
  SquaresPlusIcon: 'view-module',
  LayoutGrid: 'grid-view',
  RectangleStackIcon: 'layers',
  ListBulletIcon: 'list',
  List: 'list',
  ArchiveBoxIcon: 'folder',
  InboxIcon: 'folder-open',
  ChartBarIcon: 'reports-analytics',
  PuzzlePieceIcon: 'frameworks',
  BeakerIcon: 'discovery',
  LightBulbIcon: 'discovery',
  SparklesIcon: 'robot-2',
  RocketLaunchIcon: 'play',
  PlayIcon: 'play',
  PlayCircleIcon: 'play',
  CubeIcon: 'cube',
  Cube: 'cube',

  // --- people and identity -------------------------------------------------
  UserIcon: 'person',
  User: 'person',
  UserCircleIcon: 'person',
  UsersIcon: 'person',
  UserGroupIcon: 'person',
  UserPlusIcon: 'person',
  UserPlus: 'person',
  UserMinusIcon: 'person',
  FaceSmileIcon: 'person',
  HandRaisedIcon: 'pan-tool',
  HandThumbUpIcon: 'check-circle-open',
  HandThumbDownIcon: 'cancel-circle',

  // --- security -------------------------------------------------------------
  LockClosedIcon: 'lock',
  Lock: 'lock',
  KeyIcon: 'lock',
  FingerPrintIcon: 'lock',
  ShieldCheckIcon: 'lock',
  EyeIcon: 'visibility',
  EyeSlashIcon: 'visibility-off',
  EyeOff: 'visibility-off',

  // --- communication --------------------------------------------------------
  BellIcon: 'notifications',
  BellAlertIcon: 'notifications',
  BellSlashIcon: 'notifications',
  EnvelopeIcon: 'reports-analytics',
  AtSymbolIcon: 'link',
  ChatBubbleLeftIcon: 'annotate',
  ChatBubbleLeftRightIcon: 'annotate',
  MegaphoneIcon: 'notifications',
  PaperAirplaneIcon: 'arrow-right',
  MicrophoneIcon: 'microphone',
  Mic: 'microphone',
  SpeakerWaveIcon: 'microphone',
  LanguageIcon: 'apps',
  ShareIcon: 'link',
  SignalIcon: 'pulse',

  // --- commerce --------------------------------------------------------------
  ShoppingCartIcon: 'money',
  ShoppingBagIcon: 'money',
  ShoppingBag: 'money',
  CreditCardIcon: 'money',
  CreditCard: 'money',
  BanknotesIcon: 'money',
  Banknote: 'money',
  CurrencyDollarIcon: 'money',
  ReceiptPercentIcon: 'money',
  Wallet: 'money',
  GiftIcon: 'christmas-tree',
  TruckIcon: 'oil-rig-offshore',
  BriefcaseIcon: 'project',

  // --- markers ----------------------------------------------------------------
  StarIcon: 'crown',
  BookmarkIcon: 'add-pin',
  Bookmark: 'add-pin',
  BookmarkPlus: 'add-pin',
  Pin: 'add-pin',
  HeartIcon: 'crown',
  FlagIcon: 'add-pin',
  TagIcon: 'numeric',
  Tag: 'numeric',
  HashtagIcon: 'numeric',
  MapPinIcon: 'map',
  MapPin: 'map',
  GlobeAltIcon: 'map',
  CalendarIcon: 'history',
  Calendar: 'history',
  CalendarDaysIcon: 'history',
  FunnelIcon: 'filter',
  Filter: 'filter',
  BoltIcon: 'electricity',
  FireIcon: 'electricity',
  CloudIcon: 'layers',
  MoonIcon: 'visibility-off',
  SunIcon: 'visibility',
  Cog6ToothIcon: 'settings',
  Settings: 'settings',
  ComputerDesktopIcon: 'window',
  DevicePhoneMobileIcon: 'window',
  DeviceTabletIcon: 'window',
  Smartphone: 'window',
  BuildingOffice2Icon: 'facility',
  CursorArrowRaysIcon: 'select-cursor',
};
