/**
 * Tecton TimeInput.
 *
 * It converts values to a standard format and supports arrow-key adjustment
 * on the typed surface. Use it in forms, scheduling flows, or any interface
 * where users need to select a specific time.
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {TimeInput as BaseTimeInput} from '@astryxdesign/core/TimeInput';

type TimeInputBaseProps = ComponentProps<typeof BaseTimeInput>;

/** Props for {@link TimeInput}. */
export type TimeInputProps = TimeInputBaseProps;

export function TimeInput(props: TimeInputProps) {
  return <BaseTimeInput {...props} />;
}

TimeInput.displayName = 'TimeInput';
