/**
 * Tecton MenuCheckboxItem.
 *
 * A checkable menu item (role="menuitemcheckbox") that toggles an
 * independent boolean. Use for on/off options inside a Menu; for a one-of-N
 * choice use MenuRadioGroup.
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {DropdownMenuCheckboxItem as BaseMenuCheckboxItem} from '@astryxdesign/core/DropdownMenu';
import {resolveIcon, type TectonIconRef} from '../../icons/renderIcon.js';

type MenuCheckboxItemBaseProps = ComponentProps<typeof BaseMenuCheckboxItem>;

/** Props for {@link MenuCheckboxItem}. */
export interface MenuCheckboxItemProps extends Omit<
  MenuCheckboxItemBaseProps,
  'icon'
> {
  /**
   * Icon to display before the label. Takes a Tecton glyph name or an SVG
   * component.
   */
  icon?: TectonIconRef;
}

export function MenuCheckboxItem({icon, ...rest}: MenuCheckboxItemProps) {
  return (
    <BaseMenuCheckboxItem
      {...(rest as MenuCheckboxItemBaseProps)}
      icon={resolveIcon(icon)}
    />
  );
}

MenuCheckboxItem.displayName = 'MenuCheckboxItem';
