/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
import {describe, expect, it} from 'vitest';
import {MenuCheckboxItem} from './MenuCheckboxItem.js';

describe('MenuCheckboxItem', () => {
  it('is a component', () => {
    expect(typeof MenuCheckboxItem).toBe('function');
  });

  it('names itself for the React tree', () => {
    expect(MenuCheckboxItem.displayName).toBe('MenuCheckboxItem');
  });
});
