/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
export {CodeTheme} from './CodeTheme.js';
export type {CodeThemeProps} from './CodeTheme.js';
