/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
export {TableCell} from './TableCell.js';
export type {TableCellProps} from './TableCell.js';
