/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
export {Layout} from './Layout.js';
export type {LayoutProps} from './Layout.js';
