/**
 * Tecton Layout.
 *
 * Layout is a general five-slot primitive for arranging header, start,
 * content, end, and footer regions within a page or bounded container.
 * AppShell owns the page shell and app-wide navigation behavior; use HStack
 * or VStack for simple directional stacking.
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {Layout as BaseLayout} from '@astryxdesign/core/Layout';

type LayoutBaseProps = ComponentProps<typeof BaseLayout>;

/** Props for {@link Layout}. */
export type LayoutProps = LayoutBaseProps;

export function Layout(props: LayoutProps) {
  return <BaseLayout {...props} />;
}

Layout.displayName = 'Layout';
