/**
 * Tecton ChatComposerDrawer.
 *
 * Accordion drawer panel that sits above the chat input inside ChatComposer.
 * Pass it to the composer's `drawer` slot to show attachments, context
 * chips, or any supplementary content. When `count` is provided the drawer
 * gains a collapse toggle: collapsed state shows a badge and label, expanded
 * state shows all children.
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {ChatComposerDrawer as BaseChatComposerDrawer} from '@astryxdesign/core/Chat';

type ChatComposerDrawerBaseProps = ComponentProps<
  typeof BaseChatComposerDrawer
>;

/** Props for {@link ChatComposerDrawer}. */
export type ChatComposerDrawerProps = ChatComposerDrawerBaseProps;

export function ChatComposerDrawer(props: ChatComposerDrawerProps) {
  return <BaseChatComposerDrawer {...props} />;
}

ChatComposerDrawer.displayName = 'ChatComposerDrawer';
