/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
import {describe, expect, it} from 'vitest';
import {ChatComposerDrawer} from './ChatComposerDrawer.js';

describe('ChatComposerDrawer', () => {
  it('is a component', () => {
    expect(typeof ChatComposerDrawer).toBe('function');
  });

  it('names itself for the React tree', () => {
    expect(ChatComposerDrawer.displayName).toBe('ChatComposerDrawer');
  });
});
