/**
 * Tecton NumberInput.
 *
 * A form input for numeric values with built-in validation, min/max
 * constraints, and step controls. Use NumberInput for quantities,
 * measurements, percentages, and similar inputs.
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {NumberInput as BaseNumberInput} from '@astryxdesign/core/NumberInput';
import {resolveIcon, type TectonIconRef} from '../../icons/renderIcon.js';

type NumberInputBaseProps = ComponentProps<typeof BaseNumberInput>;

/** Props for {@link NumberInput}. */
export interface NumberInputProps extends Omit<
  NumberInputBaseProps,
  'labelIcon' | 'startIcon'
> {
  /**
   * Icon to display before the label text. Takes a Tecton glyph name or an
   * SVG component.
   */
  labelIcon?: TectonIconRef;
  /**
   * Icon to display at the start of the input. Takes a Tecton glyph name
   * or an SVG component.
   */
  startIcon?: TectonIconRef;
}

export function NumberInput({labelIcon, startIcon, ...rest}: NumberInputProps) {
  return (
    <BaseNumberInput
      {...(rest as NumberInputBaseProps)}
      labelIcon={resolveIcon(labelIcon)}
      startIcon={resolveIcon(startIcon)}
    />
  );
}

NumberInput.displayName = 'NumberInput';
