/**
 * Tecton ChatSystemMessage.
 *
 * Centered system message for non-sender content like date separators,
 * membership changes, and status notices. It is not a chat bubble; it has no
 * avatar, no alignment, and no sender context. Use the divider variant for
 * temporal breaks and default for inline status updates.
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {ChatSystemMessage as BaseChatSystemMessage} from '@astryxdesign/core/Chat';
import {tectonIconNode, type TectonIconRef} from '../../icons/renderIcon.js';

type ChatSystemMessageBaseProps = ComponentProps<typeof BaseChatSystemMessage>;

/** Props for {@link ChatSystemMessage}. */
export interface ChatSystemMessageProps extends Omit<
  ChatSystemMessageBaseProps,
  'icon'
> {
  /**
   * Leading icon that reinforces the message type. Wrap in Icon for
   * consistent sizing. Use for membership changes, encryption notices, or
   * AI activity. Takes a Tecton glyph name or an SVG component.
   */
  icon?: TectonIconRef | ChatSystemMessageBaseProps['icon'];
}

export function ChatSystemMessage({icon, ...rest}: ChatSystemMessageProps) {
  return (
    <BaseChatSystemMessage
      {...(rest as ChatSystemMessageBaseProps)}
      icon={tectonIconNode(icon) as ChatSystemMessageBaseProps['icon']}
    />
  );
}

ChatSystemMessage.displayName = 'ChatSystemMessage';
