/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
export {ChatSystemMessage} from './ChatSystemMessage.js';
export type {ChatSystemMessageProps} from './ChatSystemMessage.js';
