/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
/** @type {import('@tecton/docs').ComponentDoc} */
export const docs = {
  name: 'MultiSelector',
  displayName: 'MultiSelector',
  group: 'MultiSelector',
  category: 'Forms',
  keywords: [
    'multiselect',
    'checkbox',
    'dropdown',
    'multi',
    'picker',
    'checklist',
    'facet',
    'filter',
    'select',
  ],
  usage: {
    description:
      'A checkbox dropdown for selecting multiple values from a list. Selected items can display as a count, labels, or badges. Use it for filtering or when presenting a finite set of options where multiple choices are needed.',
    bestPractices: [
      {
        guidance: true,
        description:
          'Use for a moderate, finite set of options where multiple choices are needed.',
      },
      {
        guidance: true,
        description:
          'Enable search filtering when the list exceeds ~15 options.',
      },
      {
        guidance: true,
        description:
          'Use renderOption for custom option rows; the checkbox affordance remains owned by MultiSelector.',
      },
      {
        guidance: true,
        description:
          'Enable select-all when most users will want all or nearly all options selected.',
      },
      {
        guidance: true,
        description:
          'Use inside InputGroup only when the control needs a short prefix or suffix addon as part of one decorated input surface; prefer count or labels trigger display so the group stays single-line.',
      },
      {
        guidance: true,
        description:
          'Use variant="ghost" when a multi-selector sits in a toolbar with ghost buttons. If validation status is needed there, prefer statusVariant="tooltip" so the toolbar height stays compact.',
      },
      {
        guidance: true,
        description:
          'Use presentation="adaptive" when the multi-selector should become a bottom sheet on compact touch screens.',
      },
      {
        guidance: false,
        description: 'Use for single-value selection; use Select instead.',
      },
      {
        guidance: false,
        description: 'Show more than ~20 options without enabling search.',
      },
      {
        guidance: false,
        description:
          'Wrap a disabled MultiSelector in Tooltip to explain why it is disabled; disabled triggers swallow the hover events the wrapper needs. Use the disabledMessage prop instead.',
      },
    ],
    anatomy: [
      {
        name: 'Field',
        required: false,
        description:
          'Standalone Field shell that provides the label and optional supporting content; omitted inside InputGroup.',
      },
      {
        name: 'Trigger',
        required: true,
        description:
          'Painted control that displays the current selection or placeholder and opens the selection surface when editable.',
      },
      {
        name: 'Icon-rendered start icon',
        required: false,
        description:
          'Optional leading semantic icon or icon component rendered through Icon.',
      },
      {
        name: 'Caller-rendered start content',
        required: false,
        description:
          'Optional arbitrary React content rendered directly at the start of the trigger.',
      },
      {
        name: 'Trigger clear button',
        required: false,
        description:
          'Shared clear action that removes every selected value when hasClear is enabled.',
      },
      {
        name: 'Status icon',
        required: false,
        description:
          'Status glyph shown in place of the disclosure indicator for attached or tooltip status.',
      },
      {
        name: 'Indicator icon',
        required: false,
        description:
          'Trailing chevron shown when status presentation does not replace it; reflects collapsed or expanded state.',
      },
      {
        name: 'Search row',
        required: false,
        description:
          'Panel header with a borderless search input and optional clear action.',
      },
      {
        name: 'Search icon',
        required: false,
        description:
          'Leading magnifier rendered through Icon inside the search row.',
      },
      {
        name: 'Search clear button',
        required: false,
        description:
          'Shared clear action shown in the search row while a query is present.',
      },
      {
        name: 'Option row',
        required: false,
        description:
          'Selectable row for an option or the optional select-all choice.',
      },
      {
        name: 'Option checkbox indicator',
        required: false,
        description:
          'Checkbox indicator that presents each row’s selected, unselected, or indeterminate state.',
      },
      {
        name: 'Option divider',
        required: false,
        description:
          'Divider supplied in the public options data to separate adjacent option groups.',
      },
      {
        name: 'Section heading',
        required: false,
        description: 'Visible heading for a labeled group of option rows.',
      },
      {
        name: 'Empty state',
        required: false,
        description:
          'Message shown when the shared panel content has no options or no search matches.',
      },
      {
        name: 'Pointer popup',
        required: false,
        description:
          'Anchored painted surface that hosts the shared panel content for popover presentation.',
      },
      {
        name: 'Touch sheet heading',
        required: false,
        description:
          'Heading above the shared panel content in bottom-sheet presentation.',
      },
      {
        name: 'Touch sheet',
        required: false,
        description:
          'BottomSheet surface that hosts the same panel content for bottom-sheet presentation.',
      },
    ],
  },
  props: [],
  examples: [
    'MultiSelectorBottomSheet',
    'MultiSelectorColumnVisibilitySelector',
    'MultiSelectorForm',
    'MultiSelectorGhostToolbar',
    'MultiSelectorSearchableMultiSelector',
    'MultiSelectorSectionedMultiSelector',
    'MultiSelectorShowcase',
  ],
  notes: [
    'Generated wrapper: Tecton publishes this component with its behaviour unchanged, under Tecton names and with Tecton glyphs on its icon props.',
  ],
};
