/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
import {describe, expect, it} from 'vitest';
import {MultiSelector} from './MultiSelector.js';

describe('MultiSelector', () => {
  it('is a component', () => {
    expect(typeof MultiSelector).toBe('function');
  });

  it('names itself for the React tree', () => {
    expect(MultiSelector.displayName).toBe('MultiSelector');
  });
});
