/**
 * Tecton MultiSelector.
 *
 * A checkbox dropdown for selecting multiple values from a list. Selected
 * items can display as a count, labels, or badges. Use it for filtering or
 * when presenting a finite set of options where multiple choices are needed.
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {MultiSelector as BaseMultiSelector} from '@astryxdesign/core/MultiSelector';

type MultiSelectorBaseProps = ComponentProps<typeof BaseMultiSelector>;

/** Props for {@link MultiSelector}. */
export type MultiSelectorProps = MultiSelectorBaseProps;

export function MultiSelector(props: MultiSelectorProps) {
  return <BaseMultiSelector {...props} />;
}

MultiSelector.displayName = 'MultiSelector';
