/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
import {describe, expect, it} from 'vitest';
import {FileInput} from './FileInput.js';

describe('FileInput', () => {
  it('is a component', () => {
    expect(typeof FileInput).toBe('function');
  });

  it('names itself for the React tree', () => {
    expect(FileInput.displayName).toBe('FileInput');
  });
});
