/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
/** @type {import('@tecton/docs').ComponentDoc} */
export const docs = {
  name: 'FileInput',
  displayName: 'FileInput',
  group: 'FileInput',
  category: 'Forms',
  keywords: [
    'fileinput',
    'file',
    'upload',
    'drag',
    'drop',
    'dropzone',
    'attachment',
    'browse',
  ],
  usage: {
    description:
      'FileInput provides file upload with optional drag-and-drop support. Use it for single or multiple file selection with built-in validation for file type, size, and count. Pair with validation status for upload feedback.',
    bestPractices: [
      {
        guidance: true,
        description:
          'Always specify an accept prop to guide users toward valid file types.',
      },
      {
        guidance: true,
        description:
          'Use maxSize and maxFiles to prevent oversized uploads; the component handles validation and error display automatically.',
      },
      {
        guidance: true,
        description:
          'Add a description to communicate constraints like file size limits or accepted formats.',
      },
      {
        guidance: true,
        description:
          'Use changeAction for immediate upload workflows that benefit from optimistic UI.',
      },
      {
        guidance: false,
        description:
          "Don't use FileInput for directory or folder uploads; that is not supported in v1.",
      },
      {
        guidance: false,
        description:
          "Don't avoid dropzone mode unless space is constrained; drag-and-drop is the expected interaction for file uploads.",
      },
      {
        guidance: false,
        description:
          "Don't wrap a disabled FileInput in Tooltip to explain why it's disabled; disabled controls swallow the hover events the wrapper needs. Use the disabledMessage prop instead.",
      },
    ],
    anatomy: [
      {
        name: 'Label',
        required: true,
        description:
          'Text that identifies the field. Always rendered for accessibility even when visually hidden.',
      },
      {
        name: 'Description',
        required: false,
        description:
          'Helper text between the label and the drop zone explaining accepted formats or size limits.',
      },
      {
        name: 'Drop zone',
        required: true,
        description:
          'The clickable area for file selection. In dropzone mode, also accepts dragged files.',
      },
      {
        name: 'Upload icon',
        required: false,
        description:
          'An arrow icon in the drop zone hinting at the upload action.',
      },
      {
        name: 'Placeholder',
        required: false,
        description: 'Hint text shown when no files are selected.',
      },
      {
        name: 'File name display',
        required: false,
        description: 'Shows the name(s) of selected files.',
      },
      {
        name: 'Clear button',
        required: false,
        description:
          'A close button that removes selected files and returns focus to the input.',
      },
      {
        name: 'Spinner',
        required: false,
        description:
          'Loading indicator that appears during async upload actions.',
      },
      {
        name: 'Status message',
        required: false,
        description:
          'Validation feedback showing error, warning, or success with a message.',
      },
    ],
  },
  props: [
    {
      name: 'label',
      type: 'string',
      description: 'Accessible label for the file input.',
      required: true,
    },
    {
      name: 'value',
      type: 'File | File[] | null',
      description: 'Currently selected file(s). Controlled component.',
      required: true,
    },
    {
      name: 'onChange',
      type: '(files: File | File[] | null) => void',
      description: 'Callback fired when files are selected or removed.',
      required: true,
    },
    {
      name: 'changeAction',
      type: '(files: File | File[] | null) => Promise<void>',
      description:
        'Async change action (React 19 transitions pattern). Use for immediate upload on file selection.',
    },
    {
      name: 'accept',
      type: 'string',
      description:
        'Accepted file types. Uses the HTML accept attribute format (e.g. "image/*", ".pdf,.doc").',
    },
    {
      name: 'isMultiple',
      type: 'boolean',
      description:
        'Whether multiple files can be selected. When true, value and onChange use File[] instead of File.',
      default: 'false',
    },
    {
      name: 'maxSize',
      type: 'number',
      description:
        'Maximum file size in bytes. Files exceeding this are rejected with an error status.',
    },
    {
      name: 'maxFiles',
      type: 'number',
      description:
        'Maximum number of files (only applies when isMultiple is true).',
    },
    {
      name: 'isLabelHidden',
      type: 'boolean',
      description:
        'Visually hides the label while keeping it accessible to screen readers.',
      default: 'false',
    },
    {
      name: 'description',
      type: 'string',
      description: 'Description text displayed between the label and input.',
    },
    {
      name: 'isOptional',
      type: 'boolean',
      description:
        'Displays an "Optional" indicator next to the label. Mutually exclusive with isRequired.',
      default: 'false',
    },
    {
      name: 'isRequired',
      type: 'boolean',
      description:
        'Displays a "Required" indicator next to the label and adds a screen-reader-only "Required" description to the trigger (assistive tech does not reliably announce aria-required on the trigger). Mutually exclusive with isOptional.',
      default: 'false',
    },
    {
      name: 'isDisabled',
      type: 'boolean',
      description:
        'Disables the input, preventing interaction and dimming the element.',
      default: 'false',
    },
    {
      name: 'disabledMessage',
      type: 'string',
      description:
        'Explains why the input is disabled. With isDisabled, shows a tooltip on hover/keyboard focus and keeps the trigger focusable via aria-disabled (opening the file picker stays blocked). Use this instead of wrapping a disabled FileInput in Tooltip; disabled controls swallow the hover events an external Tooltip needs.',
    },
    {
      name: 'isLoading',
      type: 'boolean',
      description:
        'Puts the input in a loading state, showing a spinner and setting aria-busy.',
      default: 'false',
    },
    {
      name: 'placeholder',
      type: 'string',
      description: 'Placeholder text shown when no file is selected.',
      default: '"Choose file" or "Choose files"',
    },
    {
      name: 'mode',
      type: "'input' | 'dropzone'",
      description:
        "Visual mode. 'input' is a compact inline style; 'dropzone' is a larger area with drag-and-drop support.",
      default: "'input'",
    },
    {
      name: 'status',
      type: "{type: 'error' | 'warning' | 'success', message?: string}",
      description:
        'Validation status: applies a colored border. If message is provided, displays a floating message below the input. Error type also sets aria-invalid.',
    },
    {
      name: 'statusVariant',
      type: "'attached' | 'detached' | 'tooltip'",
      description:
        'How the status message is placed relative to the input. attached overlaps directly below the input (bordered treatment); detached floats below as a separate element with spacing; tooltip hides the message box and surfaces it in a tooltip on the status icon.',
      default: "'attached'",
    },
    {
      name: 'labelTooltip',
      type: 'string',
      description:
        'Tooltip text displayed in an info icon at the end of the label.',
    },
    {
      name: 'width',
      type: 'SizeValue',
      description:
        'Width of the field (number = pixels, string used as-is, e.g. "100%"). Sizes the whole field (label, control, and status) so they stay aligned.',
    },
  ],
  examples: [],
  notes: [
    'Generated wrapper: Tecton publishes this component with its behaviour unchanged, under Tecton names and with Tecton glyphs on its icon props.',
  ],
};
