/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
export {FileInput} from './FileInput.js';
export type {FileInputProps} from './FileInput.js';
