/**
 * `@tecton/react/TabList` — the `TabList` module, as the design system publishes it.
 *
 * @generated by packages/react/scripts/generate-modules.mjs — do not edit.
 */
export * from '@astryxdesign/core/TabList';
