/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
export {MenuRadioItem} from './MenuRadioItem.js';
export type {MenuRadioItemProps} from './MenuRadioItem.js';
