/**
 * Tecton MenuRadioItem.
 *
 * A single option in a MenuRadioGroup (role="menuitemradio"). Must be used
 * inside a MenuRadioGroup.
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {DropdownMenuRadioItem as BaseMenuRadioItem} from '@astryxdesign/core/DropdownMenu';
import {tectonIconValue, type TectonIconRef} from '../../icons/renderIcon.js';

type MenuRadioItemBaseProps = ComponentProps<typeof BaseMenuRadioItem>;

/** Props for {@link MenuRadioItem}. */
export interface MenuRadioItemProps extends Omit<
  MenuRadioItemBaseProps,
  'icon'
> {
  /**
   * Icon to display before the label. Takes a Tecton glyph name or an SVG
   * component.
   */
  icon?: TectonIconRef | MenuRadioItemBaseProps['icon'];
}

export function MenuRadioItem({icon, ...rest}: MenuRadioItemProps) {
  return (
    <BaseMenuRadioItem
      {...(rest as MenuRadioItemBaseProps)}
      icon={tectonIconValue(icon) as MenuRadioItemBaseProps['icon']}
    />
  );
}

MenuRadioItem.displayName = 'MenuRadioItem';
