/**
 * Tecton ToggleButtonGroupSegment.
 *
 * Individual segment item rendering as a radio button within the segmented
 * control.
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {SegmentedControlItem as BaseToggleButtonGroupSegment} from '@astryxdesign/core/SegmentedControl';
import {tectonIconNode, type TectonIconRef} from '../../icons/renderIcon.js';

type ToggleButtonGroupSegmentBaseProps = ComponentProps<
  typeof BaseToggleButtonGroupSegment
>;

/** Props for {@link ToggleButtonGroupSegment}. */
export interface ToggleButtonGroupSegmentProps extends Omit<
  ToggleButtonGroupSegmentBaseProps,
  'icon'
> {
  /**
   * Icon element displayed before the label. Takes a Tecton glyph name or
   * an SVG component.
   */
  icon?: TectonIconRef | ToggleButtonGroupSegmentBaseProps['icon'];
}

export function ToggleButtonGroupSegment({
  icon,
  ...rest
}: ToggleButtonGroupSegmentProps) {
  return (
    <BaseToggleButtonGroupSegment
      {...(rest as ToggleButtonGroupSegmentBaseProps)}
      icon={tectonIconNode(icon) as ToggleButtonGroupSegmentBaseProps['icon']}
    />
  );
}

ToggleButtonGroupSegment.displayName = 'ToggleButtonGroupSegment';
