/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
import {describe, expect, it} from 'vitest';
import {ToggleButtonGroupSegment} from './ToggleButtonGroupSegment.js';

describe('ToggleButtonGroupSegment', () => {
  it('is a component', () => {
    expect(typeof ToggleButtonGroupSegment).toBe('function');
  });

  it('names itself for the React tree', () => {
    expect(ToggleButtonGroupSegment.displayName).toBe(
      'ToggleButtonGroupSegment',
    );
  });
});
