/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
export {MobileNavToggle} from './MobileNavToggle.js';
export type {MobileNavToggleProps} from './MobileNavToggle.js';
