/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
import {describe, expect, it} from 'vitest';
import {MobileNavToggle} from './MobileNavToggle.js';

describe('MobileNavToggle', () => {
  it('is a component', () => {
    expect(typeof MobileNavToggle).toBe('function');
  });

  it('names itself for the React tree', () => {
    expect(MobileNavToggle.displayName).toBe('MobileNavToggle');
  });
});
