/**
 * Tecton MobileNavToggle.
 *
 * MobileNavToggle is published as part of the Tecton surface.
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {MobileNavToggle as BaseMobileNavToggle} from '@astryxdesign/core/MobileNav';

type MobileNavToggleBaseProps = ComponentProps<typeof BaseMobileNavToggle>;

/** Props for {@link MobileNavToggle}. */
export type MobileNavToggleProps = MobileNavToggleBaseProps;

export function MobileNavToggle(props: MobileNavToggleProps) {
  return <BaseMobileNavToggle {...props} />;
}

MobileNavToggle.displayName = 'MobileNavToggle';
