/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
/** @type {import('@tecton/docs').ComponentDoc} */
export const docs = {
  name: 'ChatLayout',
  displayName: 'ChatLayout',
  group: 'Chat',
  category: 'Chat',
  keywords: ['chatlayout'],
  usage: {
    description:
      'ChatLayout is the layout shell for full-page chat interfaces. It renders messages in normal page flow and docks the composer to the bottom with a frosted glass blur layer. Density adapts automatically via container width observation. Use it to wrap ChatMessageList and ChatComposer for a complete chat experience with built-in auto-scroll and a scroll-to-bottom button.',
    bestPractices: [
      {
        guidance: true,
        description:
          'Pass ChatMessageList as children and ChatComposer as the composer prop for a complete chat interface.',
      },
      {
        guidance: true,
        description:
          'Provide an emptyState so new conversations show a prompt instead of a blank screen.',
      },
      {
        guidance: true,
        description:
          'Use scrollRef when the chat is embedded in a page where a parent element handles scrolling.',
      },
      {
        guidance: false,
        description:
          "Don't apply a fixed height on the layout; let it fill its container with flex: 1.",
      },
      {
        guidance: false,
        description:
          "Don't render multiple ChatLayout instances in the same scroll container; each expects to own its scroll context.",
      },
    ],
    anatomy: [
      {
        name: 'Message area',
        required: true,
        description:
          'Scrollable region for messages. Renders children (typically ChatMessageList) in a flex column that pushes content to the bottom when the list is short.',
      },
      {
        name: 'Frosted glass dock',
        required: true,
        description:
          'Sticky or fixed container at the bottom with a backdrop-blur layer. Houses the scroll button and composer.',
      },
      {
        name: 'Scroll-to-bottom button',
        required: false,
        description:
          'Appears when the user scrolls up or new messages arrive. Defaults to ChatLayoutScrollButton; pass null to hide or a custom element to override.',
      },
      {
        name: 'Composer',
        required: true,
        description:
          'The input area for sending messages, typically ChatComposer. Docked at the bottom inside the frosted glass layer.',
      },
      {
        name: 'Empty state',
        required: false,
        description:
          'Centered placeholder shown when no messages exist. Use EmptyState for a consistent look.',
      },
    ],
  },
  props: [
    {
      name: 'children',
      type: 'ReactNode',
      description:
        'Message content: typically ChatMessageList. Flows naturally in the page and scrolls with the container.',
      required: true,
    },
    {
      name: 'composer',
      type: 'ReactNode',
      description:
        'Composer element: typically ChatComposer. Fixed to the bottom with a frosted glass dock.',
      required: true,
    },
    {
      name: 'emptyState',
      type: 'ReactNode',
      description:
        'Content shown when children is empty. Centered vertically in the message area.',
    },
    {
      name: 'scrollButton',
      type: 'ReactNode | null',
      description:
        'Scroll-to-bottom button rendered above the composer. Defaults to ChatLayoutScrollButton with auto-scroll integration. Pass null to hide.',
    },
    {
      name: 'scrollRef',
      type: 'React.RefObject<HTMLElement | null>',
      description:
        'External scroll container ref. When provided, auto-scroll and scroll-to-bottom target this element instead of the layout root. Use when the chat is embedded in a page where a parent element or the document body scrolls.',
    },
  ],
  examples: [],
  notes: [
    'Generated wrapper: Tecton publishes this component with its behaviour unchanged, under Tecton names and with Tecton glyphs on its icon props.',
  ],
};
