/**
 * Tecton ChatLayout.
 *
 * ChatLayout is the layout shell for full-page chat interfaces. It renders
 * messages in normal page flow and docks the composer to the bottom with a
 * frosted glass blur layer. Density adapts automatically via container width
 * observation. Use it to wrap ChatMessageList and ChatComposer for a
 * complete chat experience with built-in auto-scroll and a scroll-to-bottom
 * button.
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {ChatLayout as BaseChatLayout} from '@astryxdesign/core/Chat';

type ChatLayoutBaseProps = ComponentProps<typeof BaseChatLayout>;

/** Props for {@link ChatLayout}. */
export type ChatLayoutProps = ChatLayoutBaseProps;

export function ChatLayout(props: ChatLayoutProps) {
  return <BaseChatLayout {...props} />;
}

ChatLayout.displayName = 'ChatLayout';
