/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
export {ChatLayout} from './ChatLayout.js';
export type {ChatLayoutProps} from './ChatLayout.js';
