/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
export {MenuRadioGroup} from './MenuRadioGroup.js';
export type {MenuRadioGroupProps} from './MenuRadioGroup.js';
