/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
import {describe, expect, it} from 'vitest';
import {MenuRadioGroup} from './MenuRadioGroup.js';

describe('MenuRadioGroup', () => {
  it('is a component', () => {
    expect(typeof MenuRadioGroup).toBe('function');
  });

  it('names itself for the React tree', () => {
    expect(MenuRadioGroup.displayName).toBe('MenuRadioGroup');
  });
});
