/**
 * Tecton MenuRadioGroup.
 *
 * A single-select group of radio menu items (role="group" of menuitemradio).
 * Owns the selected value and lays its items out with the menu's inter-item
 * gap.
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {DropdownMenuRadioGroup as BaseMenuRadioGroup} from '@astryxdesign/core/DropdownMenu';

type MenuRadioGroupBaseProps = ComponentProps<typeof BaseMenuRadioGroup>;

/** Props for {@link MenuRadioGroup}. */
export type MenuRadioGroupProps = MenuRadioGroupBaseProps;

export function MenuRadioGroup(props: MenuRadioGroupProps) {
  return <BaseMenuRadioGroup {...props} />;
}

MenuRadioGroup.displayName = 'MenuRadioGroup';
