/**
 * Tecton Calendar.
 *
 * Calendar lets the user pick a date or date range from a month grid. Use it
 * in booking flows, scheduling UIs, date filters, or anywhere the user needs
 * to see surrounding dates for context.
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {Calendar as BaseCalendar} from '@astryxdesign/core/Calendar';

type CalendarBaseProps = ComponentProps<typeof BaseCalendar>;

/** Props for {@link Calendar}. */
export type CalendarProps = CalendarBaseProps;

export function Calendar(props: CalendarProps) {
  return <BaseCalendar {...props} />;
}

Calendar.displayName = 'Calendar';
