/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
export {Calendar} from './Calendar.js';
export type {CalendarProps} from './Calendar.js';
