/**
 * Tecton ChatDictationButton.
 *
 * ChatDictationButton is a toggle button that starts and stops voice
 * dictation inside a chat composer. It pairs with useChatDictation to show a
 * microphone icon when idle and animated frequency bars when listening.
 * Place it in the sendActions slot of ChatComposer.
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {ChatDictationButton as BaseChatDictationButton} from '@astryxdesign/core/Chat';

type ChatDictationButtonBaseProps = ComponentProps<
  typeof BaseChatDictationButton
>;

/** Props for {@link ChatDictationButton}. */
export type ChatDictationButtonProps = ChatDictationButtonBaseProps;

export function ChatDictationButton(props: ChatDictationButtonProps) {
  return <BaseChatDictationButton {...props} />;
}

ChatDictationButton.displayName = 'ChatDictationButton';
