/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
import {describe, expect, it} from 'vitest';
import {ChatDictationButton} from './ChatDictationButton.js';

describe('ChatDictationButton', () => {
  it('is a component', () => {
    expect(typeof ChatDictationButton).toBe('function');
  });

  it('names itself for the React tree', () => {
    expect(ChatDictationButton.displayName).toBe('ChatDictationButton');
  });
});
