/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
export {ChatDictationButton} from './ChatDictationButton.js';
export type {ChatDictationButtonProps} from './ChatDictationButton.js';
