/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
export {TopNavMegaMenuItem} from './TopNavMegaMenuItem.js';
export type {TopNavMegaMenuItemProps} from './TopNavMegaMenuItem.js';
