/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
export {Skeleton} from './Skeleton.js';
export type {SkeletonProps} from './Skeleton.js';
