/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
export {Lightbox} from './Lightbox.js';
export type {LightboxProps} from './Lightbox.js';
