/**
 * Tecton Lightbox.
 *
 * A fullscreen overlay for viewing images and videos at full resolution.
 * Supports single-item and gallery modes with prev/next navigation, optional
 * zoom and pan for images, and native video controls.
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {Lightbox as BaseLightbox} from '@astryxdesign/core/Lightbox';

type LightboxBaseProps = ComponentProps<typeof BaseLightbox>;

/** Props for {@link Lightbox}. */
export type LightboxProps = LightboxBaseProps;

export function Lightbox(props: LightboxProps) {
  return <BaseLightbox {...props} />;
}

Lightbox.displayName = 'Lightbox';
