/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
/** @type {import('@tecton/docs').ComponentDoc} */
export const docs = {
  name: 'Toolbar',
  displayName: 'Toolbar',
  group: 'Toolbar',
  category: 'Action',
  keywords: [
    'toolbar',
    'nav',
    'bar',
    'actions',
    'buttonbar',
    'header',
    'footer',
    'action-bar',
    'control-bar',
  ],
  usage: {
    description:
      'Toolbar is a horizontal bar with left, center, and right areas. Use it for contextual actions within a content area (above a table, inside a card, or in a panel), not as a page-level header. Set the size once on the toolbar and all buttons, inputs, and tabs inside it match automatically.',
    bestPractices: [
      {
        guidance: true,
        description:
          'Put secondary actions like "Back" on the left, and primary actions like "Save" on the right.',
      },
      {
        guidance: true,
        description:
          "Make temporary toolbars like bulk selection visually distinct so users can tell they're contextual, for example with a background color or border.",
      },
      {
        guidance: true,
        description:
          'Visually separate the toolbar from the content below it, with a divider, a background variant, or both.',
      },
      {
        guidance: true,
        description:
          'Use Toolbar as a card header when the header has interactive actions like filter or add; it gives you slot layout, keyboard navigation, and size cascading. If the header is just a title with no actions, a LayoutHeader or Section is enough.',
      },
      {
        guidance: false,
        description:
          'Put too many actions in one toolbar; move less common items into a MoreMenu.',
      },
      {
        guidance: false,
        description:
          'Set size on individual child buttons; set it once on the toolbar and it cascades automatically.',
      },
      {
        guidance: false,
        description:
          'Use Toolbar for app-wide navigation like main menu links or sign out; use TopNav or LayoutHeader for that.',
      },
    ],
    anatomy: [
      {
        name: 'Outer chrome',
        required: true,
        description:
          'Section-owned container that supplies the toolbar surface, padding, and selected divider edges.',
      },
      {
        name: 'Toolbar',
        required: true,
        description:
          'Named toolbar row that owns toolbar semantics and the start, optional center, and end layout.',
      },
    ],
  },
  props: [],
  examples: [
    'ToolbarCardHeader',
    'ToolbarSizes',
    'ToolbarThreeSlot',
    'ToolbarWithTabs',
  ],
  notes: [
    'Generated wrapper: Tecton publishes this component with its behaviour unchanged, under Tecton names and with Tecton glyphs on its icon props.',
  ],
};
