/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
export {NavHeadingMenuItem} from './NavHeadingMenuItem.js';
export type {NavHeadingMenuItemProps} from './NavHeadingMenuItem.js';
