/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
/** @type {import('@tecton/docs').ComponentDoc} */
export const docs = {
  name: 'NavHeadingMenuItem',
  displayName: 'NavHeadingMenuItem',
  group: 'NavHeadingMenuItem',
  category: 'Navigation',
  keywords: ['navheadingmenuitem'],
  usage: {
    description:
      'NavHeadingMenuItem is published as part of the Tecton surface.',
  },
  props: [],
  examples: [],
  notes: [
    'Generated wrapper: Tecton publishes this component with its behaviour unchanged, under Tecton names and with Tecton glyphs on its icon props.',
  ],
};
