/**
 * Tecton NavHeadingMenuItem.
 *
 * NavHeadingMenuItem is published as part of the Tecton surface.
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {NavHeadingMenuItem as BaseNavHeadingMenuItem} from '@astryxdesign/core/NavMenu';

type NavHeadingMenuItemBaseProps = ComponentProps<
  typeof BaseNavHeadingMenuItem
>;

/** Props for {@link NavHeadingMenuItem}. */
export type NavHeadingMenuItemProps = NavHeadingMenuItemBaseProps;

export function NavHeadingMenuItem(props: NavHeadingMenuItemProps) {
  return <BaseNavHeadingMenuItem {...props} />;
}

NavHeadingMenuItem.displayName = 'NavHeadingMenuItem';
