/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
import {describe, expect, it} from 'vitest';
import {NavHeadingMenuItem} from './NavHeadingMenuItem.js';

describe('NavHeadingMenuItem', () => {
  it('is a component', () => {
    expect(typeof NavHeadingMenuItem).toBe('function');
  });

  it('names itself for the React tree', () => {
    expect(NavHeadingMenuItem.displayName).toBe('NavHeadingMenuItem');
  });
});
