/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
export {Pagination} from './Pagination.js';
export type {PaginationProps} from './Pagination.js';
