/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
import {describe, expect, it} from 'vitest';
import {Pagination} from './Pagination.js';

describe('Pagination', () => {
  it('is a component', () => {
    expect(typeof Pagination).toBe('function');
  });

  it('names itself for the React tree', () => {
    expect(Pagination.displayName).toBe('Pagination');
  });
});
