/**
 * Tecton Pagination.
 *
 * Pagination lets users step through pages of content. Place it below a
 * table, list, or card grid so users can move forward and backward through
 * results. Pick a variant to match the context: numbered pages for data
 * tables, a count for large lists, compact for tight spaces, or dots for
 * carousels.
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {Pagination as BasePagination} from '@astryxdesign/core/Pagination';

type PaginationBaseProps = ComponentProps<typeof BasePagination>;

/** Props for {@link Pagination}. */
export type PaginationProps = PaginationBaseProps;

export function Pagination(props: PaginationProps) {
  return <BasePagination {...props} />;
}

Pagination.displayName = 'Pagination';
