/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
export {MenuSeparator} from './MenuSeparator.js';
export type {MenuSeparatorProps} from './MenuSeparator.js';
