/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
import {describe, expect, it} from 'vitest';
import {MenuSeparator} from './MenuSeparator.js';

describe('MenuSeparator', () => {
  it('is a component', () => {
    expect(typeof MenuSeparator).toBe('function');
  });

  it('names itself for the React tree', () => {
    expect(MenuSeparator.displayName).toBe('MenuSeparator');
  });
});
