/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
/** @type {import('@tecton/docs').ComponentDoc} */
export const docs = {
  name: 'MenuSeparator',
  displayName: 'MenuSeparator',
  group: 'Menu',
  category: 'Action',
  keywords: ['menuseparator'],
  usage: {
    description:
      'A horizontal rule separating groups of rows in a compound menu. Renders role="separator", so it is never a stop in the arrow-key order. The data-driven equivalent is the `{type: "divider"}` entry in `items`; both modes render this component, so they look and theme identically.',
  },
  props: [
    {
      name: 'xstyle',
      type: 'StyleXStyles',
      description:
        'StyleX styles applied after the menu spacing. Must be a stylex.create() value: not an inline style object like style={{}}.',
    },
  ],
  examples: [],
  notes: [
    'Generated wrapper: Tecton publishes this component with its behaviour unchanged, under Tecton names and with Tecton glyphs on its icon props.',
  ],
};
