/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
export {SideNavCollapseButton} from './SideNavCollapseButton.js';
export type {SideNavCollapseButtonProps} from './SideNavCollapseButton.js';
