/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
/** @type {import('@tecton/docs').ComponentDoc} */
export const docs = {
  name: 'SideNavCollapseButton',
  displayName: 'SideNavCollapseButton',
  group: 'SideNav',
  category: 'Navigation',
  keywords: ['sidenavcollapsebutton'],
  usage: {
    description:
      'Toggle button for sidenav collapse. Place inside SideNav (reads context automatically) or outside it (hand the same controlled collapsible config to both). Renders as an icon-only ghost button by default.',
  },
  props: [
    {
      name: 'collapsible',
      type: '{isCollapsed: boolean, onCollapsedChange: (isCollapsed: boolean) => void}',
      description:
        'The same controlled collapsible config passed to SideNav. Only needed when the button is rendered outside the sidenav, where collapse context cannot reach it.',
    },
    {
      name: 'handleRef',
      type: 'RefObject<SideNavImperativeCollapseHandle | null>',
      description:
        'Deprecated. Imperative collapse handle from SideNav; pass collapsible instead.',
    },
    {
      name: 'label',
      type: 'string',
      description:
        'Custom button label. When provided, renders as a text button with chevron. When omitted, renders icon-only.',
    },
    {
      name: 'size',
      type: "'sm' | 'md' | 'lg'",
      description:
        "Button size. Defaults to the size its container cascades ('sm' inside a SideNav footer) and to 'md' with no container. Set it when the button sits outside a sized container and has to match its neighbours.",
    },
    {
      name: 'children',
      type: 'ReactNode',
      description:
        'Custom button content. Overrides the default chevron icon and label.',
    },
  ],
  examples: [],
  notes: [
    'Generated wrapper: Tecton publishes this component with its behaviour unchanged, under Tecton names and with Tecton glyphs on its icon props.',
  ],
};
