/**
 * Tecton SideNavCollapseButton.
 *
 * Toggle button for sidenav collapse. Place inside SideNav (reads context
 * automatically) or outside it (hand the same controlled collapsible config
 * to both). Renders as an icon-only ghost button by default.
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {SideNavCollapseButton as BaseSideNavCollapseButton} from '@astryxdesign/core/SideNav';

type SideNavCollapseButtonBaseProps = ComponentProps<
  typeof BaseSideNavCollapseButton
>;

/** Props for {@link SideNavCollapseButton}. */
export type SideNavCollapseButtonProps = SideNavCollapseButtonBaseProps;

export function SideNavCollapseButton(props: SideNavCollapseButtonProps) {
  return <BaseSideNavCollapseButton {...props} />;
}

SideNavCollapseButton.displayName = 'SideNavCollapseButton';
