/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
import {describe, expect, it} from 'vitest';
import {SideNavCollapseButton} from './SideNavCollapseButton.js';

describe('SideNavCollapseButton', () => {
  it('is a component', () => {
    expect(typeof SideNavCollapseButton).toBe('function');
  });

  it('names itself for the React tree', () => {
    expect(SideNavCollapseButton.displayName).toBe('SideNavCollapseButton');
  });
});
