/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
export {MobileNav} from './MobileNav.js';
export type {MobileNavProps} from './MobileNav.js';
