/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
/** @type {import('@tecton/docs').ComponentDoc} */
export const docs = {
  name: 'MobileNav',
  displayName: 'MobileNav',
  group: 'MobileNav',
  category: 'Navigation',
  keywords: [
    'mobilenav',
    'drawer',
    'sidebar',
    'navigation',
    'hamburger',
    'menu',
    'offcanvas',
    'slideout',
    'navdrawer',
    'toggle',
  ],
  usage: {
    description:
      'A slide-out drawer for mobile navigation. MobileNav is the mobile counterpart to SideNav and accepts the same children. Use it on narrow viewports where a persistent sidebar is not practical. Inside AppShell, use MobileNavToggle as the trigger; it reads state from context automatically.',
    bestPractices: [
      {
        guidance: true,
        description:
          'Share the same nav items between MobileNav and SideNav by extracting them into a variable.',
      },
      {
        guidance: true,
        description:
          "Provide a header when the drawer's purpose is not obvious from its content.",
      },
      {
        guidance: true,
        description:
          'Inside AppShell, use MobileNavToggle to open the drawer; it reads state from context. Do not pass isOpen/onOpenChange to the toggle.',
      },
      {
        guidance: false,
        description:
          'Use MobileNav on desktop: use a persistent SideNav instead.',
      },
    ],
    anatomy: [
      {
        name: 'Navigation overlay',
        required: true,
        description:
          'Full-viewport dialog overlay that hosts the mobile navigation drawer.',
      },
      {
        name: 'Drawer',
        required: true,
        description:
          'Painted panel that slides in from the resolved viewport edge.',
      },
      {
        name: 'Header',
        required: true,
        description:
          'Fixed row containing optional header content and the close button.',
      },
      {
        name: 'Content',
        required: true,
        description: 'Scrollable region containing the navigation content.',
      },
      {
        name: 'Close button',
        required: true,
        description: 'Button that closes the navigation drawer.',
      },
      {
        name: 'Toggle button',
        required: false,
        description:
          'AppShell-aware Button that opens or closes the drawer on mobile viewports.',
      },
    ],
  },
  props: [],
  examples: [
    'MobileNavBasicMobileNav',
    'MobileNavEndSideMobileNav',
    'MobileNavShowcase',
    'MobileNavWithoutTitleMobileNav',
  ],
  notes: [
    'Generated wrapper: Tecton publishes this component with its behaviour unchanged, under Tecton names and with Tecton glyphs on its icon props.',
  ],
};
