/**
 * Tecton MobileNav.
 *
 * A slide-out drawer for mobile navigation. MobileNav is the mobile
 * counterpart to SideNav and accepts the same children. Use it on narrow
 * viewports where a persistent sidebar is not practical. Inside AppShell,
 * use MobileNavToggle as the trigger; it reads state from context
 * automatically.
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {MobileNav as BaseMobileNav} from '@astryxdesign/core/MobileNav';

type MobileNavBaseProps = ComponentProps<typeof BaseMobileNav>;

/** Props for {@link MobileNav}. */
export type MobileNavProps = MobileNavBaseProps;

export function MobileNav(props: MobileNavProps) {
  return <BaseMobileNav {...props} />;
}

MobileNav.displayName = 'MobileNav';
