/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
import {describe, expect, it} from 'vitest';
import {Popover} from './Popover.js';

describe('Popover', () => {
  it('is a component', () => {
    expect(typeof Popover).toBe('function');
  });

  it('names itself for the React tree', () => {
    expect(Popover.displayName).toBe('Popover');
  });
});
