/**
 * Tecton SurfaceTheme.
 *
 * Provides token overrides for content rendered on inverted surfaces: media
 * overlays, scrims, toasts, and tooltips. The base behavior flips
 * color-scheme so all light-dark() tokens resolve to the correct side. Only
 * a small set of tokens need explicit overrides beyond that. Themes can
 * further customize component appearance on media surfaces via
 * onDark/onLight in defineTheme(), with both token overrides (e.g.
 * "--color-accent": "#90CAF9") and component overrides (e.g. ghost buttons
 * get a border on dark surfaces).
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {MediaTheme as BaseSurfaceTheme} from '@astryxdesign/core/theme';

type SurfaceThemeBaseProps = ComponentProps<typeof BaseSurfaceTheme>;

/** Props for {@link SurfaceTheme}. */
export type SurfaceThemeProps = SurfaceThemeBaseProps;

export function SurfaceTheme(props: SurfaceThemeProps) {
  return <BaseSurfaceTheme {...props} />;
}

SurfaceTheme.displayName = 'SurfaceTheme';
