/**
 * Tecton CommandPaletteGroup.
 *
 * Visual grouping with a heading label. Place inside CommandPaletteList.
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {CommandPaletteGroup as BaseCommandPaletteGroup} from '@astryxdesign/core/CommandPalette';

type CommandPaletteGroupBaseProps = ComponentProps<
  typeof BaseCommandPaletteGroup
>;

/** Props for {@link CommandPaletteGroup}. */
export type CommandPaletteGroupProps = CommandPaletteGroupBaseProps;

export function CommandPaletteGroup(props: CommandPaletteGroupProps) {
  return <BaseCommandPaletteGroup {...props} />;
}

CommandPaletteGroup.displayName = 'CommandPaletteGroup';
