/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
export {CommandPaletteGroup} from './CommandPaletteGroup.js';
export type {CommandPaletteGroupProps} from './CommandPaletteGroup.js';
