/**
 * Tecton GridSpan.
 *
 * Grid item that spans multiple columns or rows.
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {GridSpan as BaseGridSpan} from '@astryxdesign/core/Grid';

type GridSpanBaseProps = ComponentProps<typeof BaseGridSpan>;

/** Props for {@link GridSpan}. */
export type GridSpanProps = GridSpanBaseProps;

export function GridSpan(props: GridSpanProps) {
  return <BaseGridSpan {...props} />;
}

GridSpan.displayName = 'GridSpan';
