/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
export {MenuSubMenu} from './MenuSubMenu.js';
export type {MenuSubMenuProps} from './MenuSubMenu.js';
