/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
/** @type {import('@tecton/docs').ComponentDoc} */
export const docs = {
  name: 'MenuSubMenu',
  displayName: 'MenuSubMenu',
  group: 'Menu',
  category: 'Action',
  keywords: ['menusubmenu'],
  usage: {
    description:
      'A single menu row that reveals a nested flyout of its own items. The row adopts MenuActionItem semantics (label / icon / description / isDisabled); its children become the flyout content. Opens inline-end with viewport auto-flip; Right/Enter/Space opens and focuses the first item, Left/Escape closes and returns focus to the trigger (Right/Left swap in RTL). For data-driven menus, give a menu item a nested `items` array instead of using this component directly.',
  },
  props: [
    {
      name: 'label',
      type: 'ReactNode',
      description: 'Primary label text for the trigger row.',
    },
    {
      name: 'icon',
      type: 'IconType',
      description: 'Icon to display before the label.',
    },
    {
      name: 'description',
      type: 'ReactNode',
      description: 'Secondary description text displayed below the label.',
    },
    {
      name: 'children',
      type: 'ReactNode',
      description:
        'The flyout menu items: the same components used at the top level (MenuActionItem, nested MenuSubMenu, selectable items).',
    },
    {
      name: 'isDisabled',
      type: 'boolean',
      description:
        'A disabled submenu renders its trigger row but never opens the flyout.',
      default: 'false',
    },
    {
      name: 'hasSpinner',
      type: 'boolean',
      description:
        "Show a spinner in place of the caret, e.g. while a lazy submenu's children are loading.",
      default: 'false',
    },
    {
      name: 'menuWidth',
      type: 'number | string',
      description:
        'Minimum flyout width. The flyout may grow for its content, but it is capped to the available viewport space. Defaults to intrinsic sizing (min 160px).',
    },
    {
      name: 'onOpenChange',
      type: '(isOpen: boolean) => void',
      description: 'Called when the flyout opens or closes.',
    },
    {
      name: 'xstyle',
      type: 'StyleXStyles',
      description:
        'StyleX styles for the trigger row. Must be a stylex.create() value: not an inline style object like style={{}}.',
    },
  ],
  examples: [],
  notes: [
    'Generated wrapper: Tecton publishes this component with its behaviour unchanged, under Tecton names and with Tecton glyphs on its icon props.',
  ],
};
