/**
 * Tecton MenuSubMenu.
 *
 * A single menu row that reveals a nested flyout of its own items. The row
 * adopts MenuActionItem semantics (label / icon / description / isDisabled);
 * its children become the flyout content. Opens inline-end with viewport
 * auto-flip; Right/Enter/Space opens and focuses the first item, Left/Escape
 * closes and returns focus to the trigger (Right/Left swap in RTL). For
 * data-driven menus, give a menu item a nested `items` array instead of
 * using this component directly.
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {DropdownMenuSubMenu as BaseMenuSubMenu} from '@astryxdesign/core/DropdownMenu';
import {resolveIcon, type TectonIconRef} from '../../icons/renderIcon.js';

type MenuSubMenuBaseProps = ComponentProps<typeof BaseMenuSubMenu>;

/** Props for {@link MenuSubMenu}. */
export interface MenuSubMenuProps extends Omit<MenuSubMenuBaseProps, 'icon'> {
  /**
   * Icon to display before the label. Takes a Tecton glyph name or an SVG
   * component.
   */
  icon?: TectonIconRef;
}

export function MenuSubMenu({icon, ...rest}: MenuSubMenuProps) {
  return (
    <BaseMenuSubMenu
      {...(rest as MenuSubMenuBaseProps)}
      icon={resolveIcon(icon)}
    />
  );
}

MenuSubMenu.displayName = 'MenuSubMenu';
