/**
 * Tecton AutocompleteBase.
 *
 * Composable combobox engine providing a bare input, search, keyboard
 * navigation, and a styled result dropdown. It renders no input wrapper,
 * border, or selected-value token. Autocomplete and Tokenizer compose it for
 * standard fields.
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {BaseTypeahead as BaseAutocompleteBase} from '@astryxdesign/core/Typeahead';

type AutocompleteBaseBaseProps = ComponentProps<typeof BaseAutocompleteBase>;

/** Props for {@link AutocompleteBase}. */
export type AutocompleteBaseProps = AutocompleteBaseBaseProps;

export function AutocompleteBase(props: AutocompleteBaseProps) {
  return <BaseAutocompleteBase {...props} />;
}

AutocompleteBase.displayName = 'AutocompleteBase';
