/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
export {AutocompleteBase} from './AutocompleteBase.js';
export type {AutocompleteBaseProps} from './AutocompleteBase.js';
