/**
 * Tecton CommandPalette.
 *
 * CommandPalette is a searchable dialog for quick access to commands,
 * navigation, and actions. Use it as a keyboard-driven launcher powered by
 * SearchSource for filtering and selection.
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {CommandPalette as BaseCommandPalette} from '@astryxdesign/core/CommandPalette';

type CommandPaletteBaseProps = ComponentProps<typeof BaseCommandPalette>;

/** Props for {@link CommandPalette}. */
export type CommandPaletteProps = CommandPaletteBaseProps;

export function CommandPalette(props: CommandPaletteProps) {
  return <BaseCommandPalette {...props} />;
}

CommandPalette.displayName = 'CommandPalette';
