/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
export {CommandPalette} from './CommandPalette.js';
export type {CommandPaletteProps} from './CommandPalette.js';
