/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
/** @type {import('@tecton/docs').ComponentDoc} */
export const docs = {
  name: 'CommandPaletteInput',
  displayName: 'CommandPaletteInput',
  group: 'CommandPalette',
  category: 'Overlay',
  keywords: ['commandpaletteinput'],
  usage: {
    description:
      'Search input slot. Auto-focuses on mount. Wires to command palette context when used inside CommandPalette.',
  },
  props: [
    {
      name: 'placeholder',
      type: 'string',
      description: 'Placeholder text for the input.',
      default: "'Search...'",
    },
    {
      name: 'label',
      type: 'string',
      description:
        'Accessible label for the combobox input, announced by screen readers. Falls back to the placeholder text when omitted.',
    },
    {
      name: 'hasAutoFocus',
      type: 'boolean',
      description:
        'Auto-focus the input when mounted. Automatically disabled when inside an inline command palette.',
      default: 'true',
    },
    {
      name: 'endContent',
      type: 'ReactNode',
      description:
        'Content rendered at the trailing end of the input, after the spinner. Use for clear buttons or keyboard shortcut hints.',
    },
    {
      name: 'value',
      type: 'string',
      description:
        'Search value. When omitted inside CommandPalette, reads from context.',
    },
    {
      name: 'onValueChange',
      type: '(value: string) => void',
      description:
        'Called when search value changes. When omitted inside CommandPalette, writes to context.',
    },
    {
      name: 'xstyle',
      type: 'StyleXStyles',
      description:
        'StyleX styles for layout customization. Must be a stylex.create() value.',
    },
  ],
  examples: [],
  notes: [
    'Generated wrapper: Tecton publishes this component with its behaviour unchanged, under Tecton names and with Tecton glyphs on its icon props.',
  ],
};
