/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
import {describe, expect, it} from 'vitest';
import {CommandPaletteInput} from './CommandPaletteInput.js';

describe('CommandPaletteInput', () => {
  it('is a component', () => {
    expect(typeof CommandPaletteInput).toBe('function');
  });

  it('names itself for the React tree', () => {
    expect(CommandPaletteInput.displayName).toBe('CommandPaletteInput');
  });
});
