/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
export {TableHeaderCell} from './TableHeaderCell.js';
export type {TableHeaderCellProps} from './TableHeaderCell.js';
