/**
 * Tecton TableHeaderCell.
 *
 * <th> wrapper that reads TableContext to apply density padding, semibold
 * weight, secondary text color, and divider borders when used inside Table.
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {TableHeaderCell as BaseTableHeaderCell} from '@astryxdesign/core/Table';

type TableHeaderCellBaseProps = ComponentProps<typeof BaseTableHeaderCell>;

/** Props for {@link TableHeaderCell}. */
export type TableHeaderCellProps = TableHeaderCellBaseProps;

export function TableHeaderCell(props: TableHeaderCellProps) {
  return <BaseTableHeaderCell {...props} />;
}

TableHeaderCell.displayName = 'TableHeaderCell';
