/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
export {ContextMenuSeparator} from './ContextMenuSeparator.js';
export type {ContextMenuSeparatorProps} from './ContextMenuSeparator.js';
