/**
 * Tecton Carousel.
 *
 * Carousel scrolls a row of items horizontally when they overflow the
 * available width. Use it for card grids, image galleries, product lists, or
 * any set of items that should be browsable without taking up the full page.
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {Carousel as BaseCarousel} from '@astryxdesign/core/Carousel';

type CarouselBaseProps = ComponentProps<typeof BaseCarousel>;

/** Props for {@link Carousel}. */
export type CarouselProps = CarouselBaseProps;

export function Carousel(props: CarouselProps) {
  return <BaseCarousel {...props} />;
}

Carousel.displayName = 'Carousel';
