/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
/** @type {import('@tecton/docs').ComponentDoc} */
export const docs = {
  name: 'Carousel',
  displayName: 'Carousel',
  group: 'Carousel',
  category: 'Surfaces',
  keywords: [
    'carousel',
    'slider',
    'scroll',
    'gallery',
    'filmstrip',
    'swiper',
    'horizontal',
    'overflow',
    'snap',
  ],
  usage: {
    description:
      'Carousel scrolls a row of items horizontally when they overflow the available width. Use it for card grids, image galleries, product lists, or any set of items that should be browsable without taking up the full page.',
    bestPractices: [
      {
        guidance: true,
        description:
          'Enable scroll-snap when each item should land precisely at the start edge, like a gallery or product list.',
      },
      {
        guidance: true,
        description:
          'Reach for hasLoop on small, cyclable sets like a photo gallery, where wrapping past the last item back to the first feels natural.',
      },
      {
        guidance: true,
        description:
          'Always provide an aria-label that describes what the carousel contains, like "Featured products" or "Team members".',
      },
      {
        guidance: true,
        description:
          'Carousel implements the WAI-ARIA APG carousel pattern (https://www.w3.org/WAI/ARIA/apg/patterns/carousel/) without auto-rotation: the region is labelled and carries aria-roledescription="carousel", each item is a group named "Slide N of M", and the scroll container is a tab stop so keyboard users can pan it with the arrow keys.',
      },
      {
        guidance: true,
        description:
          'Use a consistent gap and item width so the carousel looks intentional, not like content overflowing by accident.',
      },
      {
        guidance: true,
        description:
          'Trust the built-in navigation: trackpad users can swipe horizontally, and mouse users can hold Shift while scrolling the wheel to move through items.',
      },
      {
        guidance: false,
        description:
          'Use a carousel for content every user must see. Not everyone scrolls horizontally, so put critical content above the fold.',
      },
      {
        guidance: false,
        description:
          'Auto-advance items. Let the user scroll at their own pace.',
      },
      {
        guidance: false,
        description:
          'Nest carousels. A carousel inside a carousel is confusing and breaks keyboard navigation.',
      },
    ],
    anatomy: [
      {
        name: 'Scroll container',
        required: true,
        description: 'The horizontal overflow area that holds all items.',
      },
      {
        name: 'Items',
        required: true,
        description:
          'The children rendered in a row inside the scroll container. With hasSnap, each item snaps to the start edge.',
      },
      {
        name: 'Fade edges',
        required: false,
        description:
          'Gradient fades on the left and right edges that indicate more content is available. Enabled by default, disable with hasEdgeFade={false}.',
      },
      {
        name: 'Navigation buttons',
        required: false,
        description:
          'Prev/next buttons that appear when the content can scroll in that direction. Enabled by default, disable with hasButtons={false}.',
      },
    ],
  },
  props: [
    {
      name: 'children',
      type: 'ReactNode',
      description: 'Carousel items rendered in a horizontal scroll container.',
      required: true,
    },
    {
      name: 'gap',
      type: '0 | 0.5 | 1 | 1.5 | 2 | 3 | 4',
      description: 'Gap between items using the spacing token scale.',
      default: '1',
    },
    {
      name: 'hasButtons',
      type: 'boolean',
      description:
        'Show prev/next navigation buttons when content is scrollable.',
      default: 'true',
    },
    {
      name: 'hasEdgeFade',
      type: 'boolean',
      description:
        'Show a gradient edge-fade mask when content overflows, signalling that more items exist off-screen.',
      default: 'true',
    },
    {
      name: 'hasLoop',
      type: 'boolean',
      description:
        'Wrap-around scrolling: next at the end scrolls to the start, prev at the start scrolls to the end. Buttons stay visible at both edges. Only engages when content overflows.',
      default: 'false',
    },
    {
      name: 'hasSnap',
      type: 'boolean',
      description: 'Enable scroll-snap so each child snaps to the start edge.',
      default: 'false',
    },
    {
      name: 'padding',
      type: '0 | 0.5 | 1 | 1.5 | 2 | 3 | 4 | 5 | 6 | 8 | 10',
      description:
        'Inline padding inside the scroll container, with matching scroll-padding so snap points align to the content edge.',
    },
    {
      name: 'aria-label',
      type: 'string',
      description: 'Accessible label for the carousel region.',
      default: "'Carousel'",
    },
    {
      name: 'ref',
      type: 'React.Ref<HTMLDivElement>',
      description: 'Ref forwarded to the root element.',
    },
    {
      name: 'handleRef',
      type: 'React.Ref<CarouselHandle>',
      description:
        'Imperative handle exposing scrollNext(), scrollPrev(), scrollTo(index), canScrollNext(), and canScrollPrev() for programmatic scroll control.',
    },
    {
      name: 'xstyle',
      type: 'StyleXStyles',
      description:
        'StyleX styles for layout customization (margins, positioning, sizing). Must be a stylex.create() value.',
    },
    {
      name: 'className',
      type: 'string',
      description:
        'CSS class name for the root element. Prefer xstyle for styling.',
    },
    {
      name: 'style',
      type: 'CSSProperties',
      description: 'Inline styles for the root element. Prefer xstyle.',
    },
    {
      name: 'data-testid',
      type: 'string',
      description: 'Test selector for automated testing frameworks.',
    },
  ],
  examples: [],
  notes: [
    'Generated wrapper: Tecton publishes this component with its behaviour unchanged, under Tecton names and with Tecton glyphs on its icon props.',
  ],
};
