/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
import {describe, expect, it} from 'vitest';
import {BottomSheetSwitcher} from './BottomSheetSwitcher.js';

describe('BottomSheetSwitcher', () => {
  it('is a component', () => {
    expect(typeof BottomSheetSwitcher).toBe('function');
  });

  it('names itself for the React tree', () => {
    expect(BottomSheetSwitcher.displayName).toBe('BottomSheetSwitcher');
  });
});
