/**
 * Tecton BottomSheetSwitcher.
 *
 * Coordinates a multi-step bottom-sheet flow in one shared dialog; set
 * activeSheet to a nested BottomSheet's sheetId to open or switch steps, and
 * to null to close.
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {BottomSheetSwitcher as BaseBottomSheetSwitcher} from '@astryxdesign/core/BottomSheet';

type BottomSheetSwitcherBaseProps = ComponentProps<
  typeof BaseBottomSheetSwitcher
>;

/** Props for {@link BottomSheetSwitcher}. */
export type BottomSheetSwitcherProps = BottomSheetSwitcherBaseProps;

export function BottomSheetSwitcher(props: BottomSheetSwitcherProps) {
  return <BaseBottomSheetSwitcher {...props} />;
}

BottomSheetSwitcher.displayName = 'BottomSheetSwitcher';
