/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
export {MoreMenu} from './MoreMenu.js';
export type {MoreMenuProps} from './MoreMenu.js';
