/**
 * Tecton MoreMenu.
 *
 * MoreMenu is a three-dot button that opens a list of actions. Use it for
 * secondary actions that don't need to be always visible, like in table
 * rows, card headers, or toolbars.
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {MoreMenu as BaseMoreMenu} from '@astryxdesign/core/MoreMenu';
import {renderIcon, type TectonIconRef} from '../../icons/renderIcon.js';

type MoreMenuBaseProps = ComponentProps<typeof BaseMoreMenu>;

/** Props for {@link MoreMenu}. */
export interface MoreMenuProps extends Omit<MoreMenuBaseProps, 'icon'> {
  /**
   * Override the default three-dot icon. Accepts any ReactNode. Takes a
   * Tecton glyph name or an SVG component.
   */
  icon?: TectonIconRef;
}

export function MoreMenu({icon, ...rest}: MoreMenuProps) {
  return (
    <BaseMoreMenu {...(rest as MoreMenuBaseProps)} icon={renderIcon(icon)} />
  );
}

MoreMenu.displayName = 'MoreMenu';
