/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
/** @type {import('@tecton/docs').ComponentDoc} */
export const docs = {
  name: 'Code',
  displayName: 'Code',
  group: 'CodeBlock',
  category: 'Content',
  keywords: ['code'],
  usage: {
    description:
      'Inline code element. Renders a styled <code> with monospace font and muted background. For fenced blocks, use CodeBlock.',
  },
  props: [
    {
      name: 'children',
      type: 'ReactNode',
      description: 'Code content.',
      required: true,
    },
    {
      name: 'xstyle',
      type: 'StyleXStyles',
      description:
        'StyleX styles for layout customization. Must be a stylex.create() value.',
    },
    {
      name: 'className',
      type: 'string',
      description:
        'CSS class name for the root element. Prefer xstyle for styling.',
    },
    {
      name: 'style',
      type: 'CSSProperties',
      description: 'Inline styles. Prefer xstyle for StyleX-optimized styling.',
    },
  ],
  examples: [
    'CodeAcrossTextSizes',
    'CodeInlineInParagraph',
    'CodeShowcase',
    'CodeVariousContent',
  ],
  notes: [
    'Generated wrapper: Tecton publishes this component with its behaviour unchanged, under Tecton names and with Tecton glyphs on its icon props.',
  ],
};
