/**
 * Tecton TabMenu.
 *
 * Overflow menu trigger that opens a dropdown of additional tab options,
 * showing the selected option's label as the trigger text.
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {TabMenu as BaseTabMenu} from '@astryxdesign/core/TabList';

type TabMenuBaseProps = ComponentProps<typeof BaseTabMenu>;

/** Props for {@link TabMenu}. */
export type TabMenuProps = TabMenuBaseProps;

export function TabMenu(props: TabMenuProps) {
  return <BaseTabMenu {...props} />;
}

TabMenu.displayName = 'TabMenu';
