/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
/** @type {import('@tecton/docs').ComponentDoc} */
export const docs = {
  name: 'TabMenu',
  displayName: 'TabMenu',
  group: 'Tabs',
  category: 'Navigation',
  keywords: ['tabmenu'],
  usage: {
    description:
      "Overflow menu trigger that opens a dropdown of additional tab options, showing the selected option's label as the trigger text.",
  },
  props: [
    {
      name: 'label',
      type: 'string',
      description:
        'Label for the trigger button (shown when no option is selected) and the dropdown heading divider.',
      required: true,
    },
    {
      name: 'options',
      type: 'TabMenuOption[]',
      description: 'Array of menu options rendered in the dropdown.',
      required: true,
    },
  ],
  examples: [],
  notes: [
    'Generated wrapper: Tecton publishes this component with its behaviour unchanged, under Tecton names and with Tecton glyphs on its icon props.',
  ],
};
