/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
export {Stepper} from './Stepper.js';
export type {StepperProps} from './Stepper.js';
