/**
 * Tecton Stepper.
 *
 * Steppers display progress through a sequence of logical and numbered
 * steps. Use them for multi-step workflows like forms, onboarding flows, or
 * checkout processes where users need to see their position and the steps
 * ahead. Rendered as an ordered list (not a navigation landmark).
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {Stepper as BaseStepper} from '@astryxdesign/core/Stepper';

type StepperBaseProps = ComponentProps<typeof BaseStepper>;

/** Props for {@link Stepper}. */
export type StepperProps = StepperBaseProps;

export function Stepper(props: StepperProps) {
  return <BaseStepper {...props} />;
}

Stepper.displayName = 'Stepper';
