/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
import {describe, expect, it} from 'vitest';
import {Stepper} from './Stepper.js';

describe('Stepper', () => {
  it('is a component', () => {
    expect(typeof Stepper).toBe('function');
  });

  it('names itself for the React tree', () => {
    expect(Stepper.displayName).toBe('Stepper');
  });
});
