/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
/** @type {import('@tecton/docs').ComponentDoc} */
export const docs = {
  name: 'ChatLayoutScrollButton',
  displayName: 'ChatLayoutScrollButton',
  group: 'Chat',
  category: 'Chat',
  keywords: ['chatlayoutscrollbutton'],
  usage: {
    description:
      'Floating scroll-to-bottom button that appears when the user scrolls away from the latest messages. It fades in as a compact icon button and expands to show a label when new messages arrive. ChatLayout renders this by default: pass a custom element to the scrollButton prop to override, or null to hide it entirely.',
  },
  props: [
    {
      name: 'isVisible',
      type: 'boolean',
      description:
        'Whether the button is visible. Bind to a scroll-position check so the button only appears when the user has scrolled up.',
      required: true,
    },
    {
      name: 'label',
      type: 'string',
      description:
        'Optional label that expands the button (e.g. "New messages"). Use to signal unread content below the fold.',
    },
    {
      name: 'onClick',
      type: '() => void',
      description:
        'Click handler: typically scrolls to bottom and dismisses the new message indicator.',
      required: true,
    },
  ],
  examples: [],
  notes: [
    'Generated wrapper: Tecton publishes this component with its behaviour unchanged, under Tecton names and with Tecton glyphs on its icon props.',
  ],
};
