/**
 * Tecton ChatLayoutScrollButton.
 *
 * Floating scroll-to-bottom button that appears when the user scrolls away
 * from the latest messages. It fades in as a compact icon button and expands
 * to show a label when new messages arrive. ChatLayout renders this by
 * default: pass a custom element to the scrollButton prop to override, or
 * null to hide it entirely.
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {ChatLayoutScrollButton as BaseChatLayoutScrollButton} from '@astryxdesign/core/Chat';

type ChatLayoutScrollButtonBaseProps = ComponentProps<
  typeof BaseChatLayoutScrollButton
>;

/** Props for {@link ChatLayoutScrollButton}. */
export type ChatLayoutScrollButtonProps = ChatLayoutScrollButtonBaseProps;

export function ChatLayoutScrollButton(props: ChatLayoutScrollButtonProps) {
  return <BaseChatLayoutScrollButton {...props} />;
}

ChatLayoutScrollButton.displayName = 'ChatLayoutScrollButton';
