/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
import {describe, expect, it} from 'vitest';
import {ChatLayoutScrollButton} from './ChatLayoutScrollButton.js';

describe('ChatLayoutScrollButton', () => {
  it('is a component', () => {
    expect(typeof ChatLayoutScrollButton).toBe('function');
  });

  it('names itself for the React tree', () => {
    expect(ChatLayoutScrollButton.displayName).toBe('ChatLayoutScrollButton');
  });
});
