/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
export {ChatLayoutScrollButton} from './ChatLayoutScrollButton.js';
export type {ChatLayoutScrollButtonProps} from './ChatLayoutScrollButton.js';
