/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
export {TopNavMenu} from './TopNavMenu.js';
export type {TopNavMenuProps} from './TopNavMenu.js';
