/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
import {describe, expect, it} from 'vitest';
import {FormLayout} from './FormLayout.js';

describe('FormLayout', () => {
  it('is a component', () => {
    expect(typeof FormLayout).toBe('function');
  });

  it('names itself for the React tree', () => {
    expect(FormLayout.displayName).toBe('FormLayout');
  });
});
