/**
 * Tecton FormLayout.
 *
 * A layout container that arranges form fields with consistent spacing and
 * direction. FormLayout handles where fields go, not state or submission.
 * Wrap it in a <form> for that. Supports vertical (default), horizontal, and
 * horizontal-labels directions, and can be nested to mix them.
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {FormLayout as BaseFormLayout} from '@astryxdesign/core/FormLayout';

type FormLayoutBaseProps = ComponentProps<typeof BaseFormLayout>;

/** Props for {@link FormLayout}. */
export type FormLayoutProps = FormLayoutBaseProps;

export function FormLayout(props: FormLayoutProps) {
  return <BaseFormLayout {...props} />;
}

FormLayout.displayName = 'FormLayout';
