/**
 * Tecton ContextMenuSubMenu.
 *
 * ContextMenuSubMenu is published as part of the Tecton surface.
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {ContextMenuSubMenu as BaseContextMenuSubMenu} from '@astryxdesign/core/ContextMenu';

type ContextMenuSubMenuBaseProps = ComponentProps<
  typeof BaseContextMenuSubMenu
>;

/** Props for {@link ContextMenuSubMenu}. */
export type ContextMenuSubMenuProps = ContextMenuSubMenuBaseProps;

export function ContextMenuSubMenu(props: ContextMenuSubMenuProps) {
  return <BaseContextMenuSubMenu {...props} />;
}

ContextMenuSubMenu.displayName = 'ContextMenuSubMenu';
