/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
import {describe, expect, it} from 'vitest';
import {ContextMenuSubMenu} from './ContextMenuSubMenu.js';

describe('ContextMenuSubMenu', () => {
  it('is a component', () => {
    expect(typeof ContextMenuSubMenu).toBe('function');
  });

  it('names itself for the React tree', () => {
    expect(ContextMenuSubMenu.displayName).toBe('ContextMenuSubMenu');
  });
});
