/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
export {ContextMenuSubMenu} from './ContextMenuSubMenu.js';
export type {ContextMenuSubMenuProps} from './ContextMenuSubMenu.js';
