/**
 * @generated by packages/react/scripts/generate-icons.mjs — do not edit.
 * Source: design/icons/tecton/*.ts
 */
import type {TectonIconGlyph} from './glyph.js';
import type {TectonIconName} from './names.js';
import {AddIcon} from './generated/add.js';
import {AddCircleIcon} from './generated/add-circle.js';
import {AddPinIcon} from './generated/add-pin.js';
import {AnnotateIcon} from './generated/annotate.js';
import {AppsIcon} from './generated/apps.js';
import {ArrowDownIcon} from './generated/arrow-down.js';
import {ArrowLeftIcon} from './generated/arrow-left.js';
import {ArrowRightIcon} from './generated/arrow-right.js';
import {ArrowUpIcon} from './generated/arrow-up.js';
import {CancelCircleIcon} from './generated/cancel-circle.js';
import {CaretCollapseIcon} from './generated/caret-collapse.js';
import {CaretUpDownIcon} from './generated/caret-up-down.js';
import {CheckIcon} from './generated/check.js';
import {CheckCircleIcon} from './generated/check-circle.js';
import {CheckCircleOpenIcon} from './generated/check-circle-open.js';
import {CheckboxIcon} from './generated/checkbox.js';
import {CheckboxOutlineBlankIcon} from './generated/checkbox-outline-blank.js';
import {ChevronDownIcon} from './generated/chevron-down.js';
import {ChevronDownSmallIcon} from './generated/chevron-down-small.js';
import {ChevronLeftIcon} from './generated/chevron-left.js';
import {ChevronLeftSmallIcon} from './generated/chevron-left-small.js';
import {ChevronRightIcon} from './generated/chevron-right.js';
import {ChevronRightSmallIcon} from './generated/chevron-right-small.js';
import {ChevronUpIcon} from './generated/chevron-up.js';
import {ChevronUpSmallIcon} from './generated/chevron-up-small.js';
import {ChristmasTreeIcon} from './generated/christmas-tree.js';
import {CloseIcon} from './generated/close.js';
import {CloseSmallIcon} from './generated/close-small.js';
import {Co2LeafIcon} from './generated/co-2-leaf.js';
import {CodeIcon} from './generated/code.js';
import {CollapseContentIcon} from './generated/collapse-content.js';
import {ControlsIcon} from './generated/controls.js';
import {CopyIcon} from './generated/copy.js';
import {CrownIcon} from './generated/crown.js';
import {CubeIcon} from './generated/cube.js';
import {DatabaseIcon} from './generated/database.js';
import {DeleteIcon} from './generated/delete.js';
import {DesignIcon} from './generated/design.js';
import {DiamondMarkIcon} from './generated/diamond-mark.js';
import {DiscoveryIcon} from './generated/discovery.js';
import {DragIndicatorIcon} from './generated/drag-indicator.js';
import {DrillBitIcon} from './generated/drill-bit.js';
import {EditSquareIcon} from './generated/edit-square.js';
import {ElectricityIcon} from './generated/electricity.js';
import {EngineeringIcon} from './generated/engineering.js';
import {ErrorIcon} from './generated/error.js';
import {ExpandContentIcon} from './generated/expand-content.js';
import {ExportUploadIcon} from './generated/export-upload.js';
import {FacilityIcon} from './generated/facility.js';
import {FaultIcon} from './generated/fault.js';
import {FilterIcon} from './generated/filter.js';
import {FolderIcon} from './generated/folder.js';
import {FolderNewIcon} from './generated/folder-new.js';
import {FolderOpenIcon} from './generated/folder-open.js';
import {FrameworksIcon} from './generated/frameworks.js';
import {GeobodiesIcon} from './generated/geobodies.js';
import {GeostructureIcon} from './generated/geostructure.js';
import {GridViewIcon} from './generated/grid-view.js';
import {HistoryIcon} from './generated/history.js';
import {HomeIcon} from './generated/home.js';
import {HorizonIcon} from './generated/horizon.js';
import {ImageIcon} from './generated/image.js';
import {IndeterminateCheckboxIcon} from './generated/indeterminate-checkbox.js';
import {InfoIcon} from './generated/info.js';
import {InspectIcon} from './generated/inspect.js';
import {KanbanIcon} from './generated/kanban.js';
import {LayersIcon} from './generated/layers.js';
import {LineWeightIcon} from './generated/line-weight.js';
import {LinkIcon} from './generated/link.js';
import {LinkOffIcon} from './generated/link-off.js';
import {ListIcon} from './generated/list.js';
import {LockIcon} from './generated/lock.js';
import {LockOpenIcon} from './generated/lock-open.js';
import {LogCurveIcon} from './generated/log-curve.js';
import {MapIcon} from './generated/map.js';
import {MenuIcon} from './generated/menu.js';
import {MicrophoneIcon} from './generated/microphone.js';
import {MoneyIcon} from './generated/money.js';
import {MoreVertIcon} from './generated/more-vert.js';
import {NodeIcon} from './generated/node.js';
import {NotificationsIcon} from './generated/notifications.js';
import {NumericIcon} from './generated/numeric.js';
import {OilRigOffshoreIcon} from './generated/oil-rig-offshore.js';
import {OpenInNewIcon} from './generated/open-in-new.js';
import {PanToolIcon} from './generated/pan-tool.js';
import {PanelIcon} from './generated/panel.js';
import {PersonIcon} from './generated/person.js';
import {PlayIcon} from './generated/play.js';
import {PreviewIcon} from './generated/preview.js';
import {ProjectIcon} from './generated/project.js';
import {PulseIcon} from './generated/pulse.js';
import {RadioButtonIcon} from './generated/radio-button.js';
import {RedoIcon} from './generated/redo.js';
import {RemoveIcon} from './generated/remove.js';
import {RemoveCircleIcon} from './generated/remove-circle.js';
import {ReportsAnalyticsIcon} from './generated/reports-analytics.js';
import {RiskSkullIcon} from './generated/risk-skull.js';
import {Robot2Icon} from './generated/robot-2.js';
import {RockFormationsIcon} from './generated/rock-formations.js';
import {RotateIcon} from './generated/rotate.js';
import {RulerIcon} from './generated/ruler.js';
import {SearchIcon} from './generated/search.js';
import {SeismicIcon} from './generated/seismic.js';
import {SelectIcon} from './generated/select.js';
import {SelectCursorIcon} from './generated/select-cursor.js';
import {SettingsIcon} from './generated/settings.js';
import {SliceIcon} from './generated/slice.js';
import {SortEnabledIcon} from './generated/sort-enabled.js';
import {SplitscreenIcon} from './generated/splitscreen.js';
import {StrataIcon} from './generated/strata.js';
import {SurfaceIcon} from './generated/surface.js';
import {SwapIcon} from './generated/swap.js';
import {TargetIcon} from './generated/target.js';
import {ThreeDIcon} from './generated/three-d.js';
import {TrajectoryIcon} from './generated/trajectory.js';
import {TrendIcon} from './generated/trend.js';
import {UndoIcon} from './generated/undo.js';
import {ValveIcon} from './generated/valve.js';
import {VelocityModelIcon} from './generated/velocity-model.js';
import {ViewColumnIcon} from './generated/view-column.js';
import {ViewModuleIcon} from './generated/view-module.js';
import {VisibilityIcon} from './generated/visibility.js';
import {VisibilityOffIcon} from './generated/visibility-off.js';
import {WarningIcon} from './generated/warning.js';
import {WaterIcon} from './generated/water.js';
import {WellIcon} from './generated/well.js';
import {WellPickIcon} from './generated/well-pick.js';
import {WellPlanIcon} from './generated/well-plan.js';
import {WindowIcon} from './generated/window.js';
import {ZoomInIcon} from './generated/zoom-in.js';
import {ZoomOutIcon} from './generated/zoom-out.js';

/**
 * Every Tecton glyph, by name. {@link Icon} looks a glyph up here; application
 * code that already knows which glyph it wants should import the component.
 */
export const tectonIconRegistry: Record<TectonIconName, TectonIconGlyph> = {
  add: AddIcon,
  'add-circle': AddCircleIcon,
  'add-pin': AddPinIcon,
  annotate: AnnotateIcon,
  apps: AppsIcon,
  'arrow-down': ArrowDownIcon,
  'arrow-left': ArrowLeftIcon,
  'arrow-right': ArrowRightIcon,
  'arrow-up': ArrowUpIcon,
  'cancel-circle': CancelCircleIcon,
  'caret-collapse': CaretCollapseIcon,
  'caret-up-down': CaretUpDownIcon,
  check: CheckIcon,
  'check-circle': CheckCircleIcon,
  'check-circle-open': CheckCircleOpenIcon,
  checkbox: CheckboxIcon,
  'checkbox-outline-blank': CheckboxOutlineBlankIcon,
  'chevron-down': ChevronDownIcon,
  'chevron-down-small': ChevronDownSmallIcon,
  'chevron-left': ChevronLeftIcon,
  'chevron-left-small': ChevronLeftSmallIcon,
  'chevron-right': ChevronRightIcon,
  'chevron-right-small': ChevronRightSmallIcon,
  'chevron-up': ChevronUpIcon,
  'chevron-up-small': ChevronUpSmallIcon,
  'christmas-tree': ChristmasTreeIcon,
  close: CloseIcon,
  'close-small': CloseSmallIcon,
  'co-2-leaf': Co2LeafIcon,
  code: CodeIcon,
  'collapse-content': CollapseContentIcon,
  controls: ControlsIcon,
  copy: CopyIcon,
  crown: CrownIcon,
  cube: CubeIcon,
  database: DatabaseIcon,
  delete: DeleteIcon,
  design: DesignIcon,
  'diamond-mark': DiamondMarkIcon,
  discovery: DiscoveryIcon,
  'drag-indicator': DragIndicatorIcon,
  'drill-bit': DrillBitIcon,
  'edit-square': EditSquareIcon,
  electricity: ElectricityIcon,
  engineering: EngineeringIcon,
  error: ErrorIcon,
  'expand-content': ExpandContentIcon,
  'export-upload': ExportUploadIcon,
  facility: FacilityIcon,
  fault: FaultIcon,
  filter: FilterIcon,
  folder: FolderIcon,
  'folder-new': FolderNewIcon,
  'folder-open': FolderOpenIcon,
  frameworks: FrameworksIcon,
  geobodies: GeobodiesIcon,
  geostructure: GeostructureIcon,
  'grid-view': GridViewIcon,
  history: HistoryIcon,
  home: HomeIcon,
  horizon: HorizonIcon,
  image: ImageIcon,
  'indeterminate-checkbox': IndeterminateCheckboxIcon,
  info: InfoIcon,
  inspect: InspectIcon,
  kanban: KanbanIcon,
  layers: LayersIcon,
  'line-weight': LineWeightIcon,
  link: LinkIcon,
  'link-off': LinkOffIcon,
  list: ListIcon,
  lock: LockIcon,
  'lock-open': LockOpenIcon,
  'log-curve': LogCurveIcon,
  map: MapIcon,
  menu: MenuIcon,
  microphone: MicrophoneIcon,
  money: MoneyIcon,
  'more-vert': MoreVertIcon,
  node: NodeIcon,
  notifications: NotificationsIcon,
  numeric: NumericIcon,
  'oil-rig-offshore': OilRigOffshoreIcon,
  'open-in-new': OpenInNewIcon,
  'pan-tool': PanToolIcon,
  panel: PanelIcon,
  person: PersonIcon,
  play: PlayIcon,
  preview: PreviewIcon,
  project: ProjectIcon,
  pulse: PulseIcon,
  'radio-button': RadioButtonIcon,
  redo: RedoIcon,
  remove: RemoveIcon,
  'remove-circle': RemoveCircleIcon,
  'reports-analytics': ReportsAnalyticsIcon,
  'risk-skull': RiskSkullIcon,
  'robot-2': Robot2Icon,
  'rock-formations': RockFormationsIcon,
  rotate: RotateIcon,
  ruler: RulerIcon,
  search: SearchIcon,
  seismic: SeismicIcon,
  select: SelectIcon,
  'select-cursor': SelectCursorIcon,
  settings: SettingsIcon,
  slice: SliceIcon,
  'sort-enabled': SortEnabledIcon,
  splitscreen: SplitscreenIcon,
  strata: StrataIcon,
  surface: SurfaceIcon,
  swap: SwapIcon,
  target: TargetIcon,
  'three-d': ThreeDIcon,
  trajectory: TrajectoryIcon,
  trend: TrendIcon,
  undo: UndoIcon,
  valve: ValveIcon,
  'velocity-model': VelocityModelIcon,
  'view-column': ViewColumnIcon,
  'view-module': ViewModuleIcon,
  visibility: VisibilityIcon,
  'visibility-off': VisibilityOffIcon,
  warning: WarningIcon,
  water: WaterIcon,
  well: WellIcon,
  'well-pick': WellPickIcon,
  'well-plan': WellPlanIcon,
  window: WindowIcon,
  'zoom-in': ZoomInIcon,
  'zoom-out': ZoomOutIcon,
};
