/**
 * Tecton EmptyState.
 *
 * EmptyState shows a placeholder when a content area has no data. Use it for
 * empty lists, zero search results, first-time setups, or cleared inboxes.
 * Always include a title and a next step so the user is not stuck.
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {EmptyState as BaseEmptyState} from '@astryxdesign/core/EmptyState';
import {tectonIconNode, type TectonIconRef} from '../../icons/renderIcon.js';

type EmptyStateBaseProps = ComponentProps<typeof BaseEmptyState>;

/** Props for {@link EmptyState}. */
export interface EmptyStateProps extends Omit<EmptyStateBaseProps, 'icon'> {
  /**
   * Optional icon or illustration displayed above the title; rendered as
   * decorative (aria-hidden="true"). Takes a Tecton glyph name or an SVG
   * component.
   */
  icon?: TectonIconRef | EmptyStateBaseProps['icon'];
}

export function EmptyState({icon, ...rest}: EmptyStateProps) {
  return (
    <BaseEmptyState
      {...(rest as EmptyStateBaseProps)}
      icon={tectonIconNode(icon) as EmptyStateBaseProps['icon']}
    />
  );
}

EmptyState.displayName = 'EmptyState';
