/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
/** @type {import('@tecton/docs').ComponentDoc} */
export const docs = {
  name: 'EmptyState',
  displayName: 'EmptyState',
  group: 'EmptyState',
  category: 'Content',
  keywords: [
    'emptystate',
    'empty',
    'placeholder',
    'nodata',
    'blank',
    'noresults',
    'illustration',
    'blankslate',
  ],
  usage: {
    description:
      'EmptyState shows a placeholder when a content area has no data. Use it for empty lists, zero search results, first-time setups, or cleared inboxes. Always include a title and a next step so the user is not stuck.',
    bestPractices: [
      {
        guidance: true,
        description:
          'Include a clear title and a call-to-action button so users know how to proceed.',
      },
      {
        guidance: true,
        description:
          'Use an illustration or icon that reinforces the context of the empty state.',
      },
      {
        guidance: true,
        description:
          'Use the compact variant inside cards or sidebars where space is limited.',
      },
      {
        guidance: false,
        description:
          'Leave an empty state without guidance; always explain what happened and what the user can do next.',
      },
      {
        guidance: false,
        description:
          'Use a generic message like "No data"; be specific about what is empty and why.',
      },
      {
        guidance: false,
        description:
          'Use an EmptyState for error messages that require immediate action; use a Alert instead.',
      },
    ],
    anatomy: [
      {
        name: 'Icon',
        required: false,
        description:
          'A visual cue above the title that reinforces the context, like a search icon for no results.',
      },
      {
        name: 'Title',
        required: true,
        description:
          'Primary message explaining what is empty: "No projects yet" not "No data".',
      },
      {
        name: 'Description',
        required: false,
        description:
          'Additional context explaining why it is empty or what the user can do.',
      },
      {
        name: 'Actions',
        required: false,
        description:
          'One or two buttons guiding the user to a next step, like "Create project" or "Clear filters".',
      },
    ],
  },
  props: [
    {
      name: 'title',
      type: 'string',
      description:
        'Primary message rendered as an <h3> heading inside the empty state.',
      required: true,
    },
    {
      name: 'description',
      type: 'string',
      description:
        'Optional secondary text providing additional context below the title.',
    },
    {
      name: 'icon',
      type: 'ReactNode',
      description:
        'Optional icon or illustration displayed above the title; rendered as decorative (aria-hidden="true").',
    },
    {
      name: 'actions',
      type: 'ReactNode',
      description:
        'Optional action buttons displayed below the description, laid out horizontally by default and stacked vertically when isCompact is true.',
    },
    {
      name: 'headingLevel',
      type: '1 | 2 | 3 | 4 | 5 | 6',
      description:
        'Controls only the rendered HTML heading tag (h1-h6) so the title fits the document outline. This is a semantic change for accessibility and does not change the visual size of the title, which stays fixed regardless of level.',
      default: '3',
    },
    {
      name: 'isCompact',
      type: 'boolean',
      description:
        'Enables the compact variant with reduced spacing for constrained content areas.',
      default: 'false',
    },
    {
      name: 'xstyle',
      type: 'StyleXStyles',
      description:
        'StyleX styles for layout customization (margins, positioning, sizing). Must be a stylex.create() value, not an inline style object like style={{}}.',
    },
  ],
  examples: [],
  notes: [
    'Generated wrapper: Tecton publishes this component with its behaviour unchanged, under Tecton names and with Tecton glyphs on its icon props.',
  ],
};
