/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
export {EmptyState} from './EmptyState.js';
export type {EmptyStateProps} from './EmptyState.js';
