/**
 * Tecton Field.
 *
 * Field is a low-level wrapper for custom, native, or third-party controls
 * that do not already provide field label, description, and status UI.
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {Field as BaseField} from '@astryxdesign/core/Field';
import {resolveIcon, type TectonIconRef} from '../../icons/renderIcon.js';

type FieldBaseProps = ComponentProps<typeof BaseField>;

/** Props for {@link Field}. */
export interface FieldProps extends Omit<FieldBaseProps, 'labelIcon'> {
  /**
   * Icon to display before the label text. Takes a Tecton glyph name or an
   * SVG component.
   */
  labelIcon?: TectonIconRef;
}

export function Field({labelIcon, ...rest}: FieldProps) {
  return (
    <BaseField
      {...(rest as FieldBaseProps)}
      labelIcon={resolveIcon(labelIcon)}
    />
  );
}

Field.displayName = 'Field';
