/**
 * Tecton Timestamp.
 *
 * Timestamp formats a date or time value into human-readable text. Use it to
 * show when something was created, updated, or is scheduled; picking
 * relative for recency, absolute for precision, or auto to let the component
 * decide.
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {Timestamp as BaseTimestamp} from '@astryxdesign/core/Timestamp';

type TimestampBaseProps = ComponentProps<typeof BaseTimestamp>;

/** Props for {@link Timestamp}. */
export type TimestampProps = TimestampBaseProps;

export function Timestamp(props: TimestampProps) {
  return <BaseTimestamp {...props} />;
}

Timestamp.displayName = 'Timestamp';
