/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
export {TableRow} from './TableRow.js';
export type {TableRowProps} from './TableRow.js';
