/**
 * Tecton TableRow.
 *
 * <tr> wrapper that reads TableContext to apply striped, hover, and divider
 * styles when used inside Table.
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {TableRow as BaseTableRow} from '@astryxdesign/core/Table';

type TableRowBaseProps = ComponentProps<typeof BaseTableRow>;

/** Props for {@link TableRow}. */
export type TableRowProps = TableRowBaseProps;

export function TableRow(props: TableRowProps) {
  return <BaseTableRow {...props} />;
}

TableRow.displayName = 'TableRow';
