/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
import {describe, expect, it} from 'vitest';
import {ChatSendButton} from './ChatSendButton.js';

describe('ChatSendButton', () => {
  it('is a component', () => {
    expect(typeof ChatSendButton).toBe('function');
  });

  it('names itself for the React tree', () => {
    expect(ChatSendButton.displayName).toBe('ChatSendButton');
  });
});
