/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
export {ChatSendButton} from './ChatSendButton.js';
export type {ChatSendButtonProps} from './ChatSendButton.js';
