/**
 * Tecton FieldLabel.
 *
 * Standalone label component with optional/required indicators and tooltip
 * support.
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {FieldLabel as BaseFieldLabel} from '@astryxdesign/core/Field';
import {resolveIcon, type TectonIconRef} from '../../icons/renderIcon.js';

type FieldLabelBaseProps = ComponentProps<typeof BaseFieldLabel>;

/** Props for {@link FieldLabel}. */
export interface FieldLabelProps extends Omit<
  FieldLabelBaseProps,
  'labelIcon'
> {
  /**
   * Icon before the label text. Takes a Tecton glyph name or an SVG
   * component.
   */
  labelIcon?: TectonIconRef;
}

export function FieldLabel({labelIcon, ...rest}: FieldLabelProps) {
  return (
    <BaseFieldLabel
      {...(rest as FieldLabelBaseProps)}
      labelIcon={resolveIcon(labelIcon)}
    />
  );
}

FieldLabel.displayName = 'FieldLabel';
