/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
import {describe, expect, it} from 'vitest';
import {FieldLabel} from './FieldLabel.js';

describe('FieldLabel', () => {
  it('is a component', () => {
    expect(typeof FieldLabel).toBe('function');
  });

  it('names itself for the React tree', () => {
    expect(FieldLabel.displayName).toBe('FieldLabel');
  });
});
