/**
 * @generated by packages/react/scripts/port-examples.mjs — do not edit.
 *
 * Tecton page templates: whole screens, assembled from Tecton components,
 * that a team copies and edits rather than imports. Published from
 * `@tecton/react/templates` so the documentation site can render the
 * gallery from the same code a consumer would paste.
 */

/** A page template, as the gallery lists it. */
export interface TectonTemplateEntry {
  /** URL-safe identifier, and the directory the template lives in. */
  slug: string;
  /** The template's name, as the gallery shows it. */
  name: string;
  /** One sentence on what the page is for. */
  description: string;
  /** The gallery grouping. */
  category: string;
}

export {Template as BlankTemplate} from './blank/Template.js';
export {Template as CenteredHeroTemplate} from './centered-hero/Template.js';
export {Template as ClassicGalleryTemplate} from './classic-gallery/Template.js';
export {Template as DocumentationTemplate} from './documentation/Template.js';
export {Template as GalleryHeroTemplate} from './gallery-hero/Template.js';
export {Template as LoginTemplate} from './login/Template.js';
export {Template as LoginCardTemplate} from './login-card/Template.js';
export {Template as LoginSplitTemplate} from './login-split/Template.js';
export {Template as MixedGalleryTemplate} from './mixed-gallery/Template.js';
export {Template as ProductGalleryTemplate} from './product-gallery/Template.js';
export {Template as SettingsTemplate} from './settings/Template.js';
export {Template as SideGalleryTemplate} from './side-gallery/Template.js';

/** Every page template Tecton publishes. */
export const tectonTemplates: readonly TectonTemplateEntry[] = [
  {
    slug: 'blank',
    name: 'Blank',
    description:
      'Bare scaffold: one heading slot, one empty content region, no navigation and no chrome. The starting point when every other layout imposes more structure than wanted. Blank, empty, stub, placeholder, or minimal scaffold.',
    category: 'Shell - Blank',
  },
  {
    slug: 'centered-hero',
    name: 'Centered Hero',
    description:
      'Symmetrical centered stack (headline, short blurb, paired call-to-action buttons) resting on one wide full-bleed picture, with nothing on either flank competing. Hero, banner, splash, landing image, or marketing masthead.',
    category: 'Gallery - Hero',
  },
  {
    slug: 'classic-gallery',
    name: 'Classic Gallery',
    description:
      'Uniform grid of equal-ratio media tiles under a centered intro, with filter tabs that narrow the set in place. Regular rhythm, unlike the variable-height masonry variant. Gallery, photos, images, pictures, or portfolio index.',
    category: 'Gallery - Basic',
  },
  {
    slug: 'documentation',
    name: 'Documentation Catalog',
    description:
      'Reference landing that is pure wayfinding: a banner above a grid of category cards linking into sections, with no article content on the surface itself. Documentation, docs, guide, handbook, reference, or API index.',
    category: 'Content - Documentation Catalog',
  },
  {
    slug: 'gallery-hero',
    name: 'Gallery Hero',
    description:
      'Centered stack (headline, short blurb, call-to-action buttons) resolving into a multi-image photo grid rather than one wide full-bleed picture, so the imagery reads as a set. Hero, banner, splash, landing image, masthead, or gallery intro.',
    category: 'Gallery - Hero',
  },
  {
    slug: 'login',
    name: 'Basic Login',
    description:
      'Minimal centered credential form on a plain ground: two fields and a submit, nothing competing for attention. The least-chrome entry surface. Login, sign in, signin, authentication, credentials, or account access.',
    category: 'Login - Basic',
  },
  {
    slug: 'login-card',
    name: 'Login Card',
    description:
      'Credential form inside an elevated centered card, third-party provider buttons separated from the fields by a divider, secondary sign-up and legal links beneath. Login, sign in, signin, authentication, credentials, social, or account access.',
    category: 'Login - Card',
  },
  {
    slug: 'login-split',
    name: 'Login Split',
    description:
      'Credential form filling one half of a two-pane split, full-bleed media holding the other. Same fields as the card variant, but the layout carries brand imagery. Login, sign in, signin, authentication, credentials, or account access.',
    category: 'Login - Split',
  },
  {
    slug: 'mixed-gallery',
    name: 'Mixed Gallery',
    description:
      'Masonry grid of variable-height tiles that pack against each other instead of cropping to a shared ratio, captioned per tile. Irregular rhythm, unlike the uniform gallery. Photos, images, pictures, portfolio, masonry, or media wall.',
    category: 'Gallery - Mixed',
  },
  {
    slug: 'product-gallery',
    name: 'Product Gallery',
    description:
      'Uniform card grid where every tile carries media, title, supporting line, and a price. Browse-to-select only, with no filtering and no detail surface. Products, catalog, storefront, shop, listings, or ecommerce grid.',
    category: 'Gallery - Product',
  },
  {
    slug: 'settings',
    name: 'Settings Form',
    description:
      'Preferences as one continuously scrolling form, sections stacked in order with no navigation between them. The simplest settings shape: everything reachable by scrolling. Settings, preferences, configuration, options, or account.',
    category: 'Settings - Form',
  },
  {
    slug: 'side-gallery',
    name: 'Side Gallery',
    description:
      'Asymmetric split section: a copy column of headline, supporting text, and links held against a clustered image collage opposite. Deliberately off-balance, unlike the centered hero. Feature banner, split section, marketing, or gallery intro.',
    category: 'Gallery - Side',
  },
];
