/**
 * @generated by packages/react/scripts/port-examples.mjs — do not edit.
 *
 * Tecton page templates: whole screens, assembled from Tecton components, that
 * a team copies and edits rather than imports. They are published from
 * `@tecton/react/templates` so the documentation site can render the gallery
 * from the same code a consumer would paste.
 */

/** A page template, as the gallery lists it. */
export interface TectonTemplateEntry {
  /** URL-safe identifier, and the directory the template lives in. */
  slug: string;
  /** The template's name, as the gallery shows it. */
  name: string;
  /** One sentence on what the page is for. */
  description: string;
  /** The gallery grouping. */
  category: string;
}

/** Every page template Tecton publishes, by slug. */
export const tectonTemplates: readonly TectonTemplateEntry[] = [];
