/**
 * Tecton ChatTokenizedText.
 *
 * Renders a text string with token patterns replaced by inline Badge
 * components. Wrap any message body inside ChatMessageBubble to turn raw
 * @mentions, #tags, or /commands into styled badges. When no tokens match or
 * none are provided, the text renders as-is: so you can use
 * ChatTokenizedText unconditionally on every message.
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {ChatTokenizedText as BaseChatTokenizedText} from '@astryxdesign/core/Chat';

type ChatTokenizedTextBaseProps = ComponentProps<typeof BaseChatTokenizedText>;

/** Props for {@link ChatTokenizedText}. */
export type ChatTokenizedTextProps = ChatTokenizedTextBaseProps;

export function ChatTokenizedText(props: ChatTokenizedTextProps) {
  return <BaseChatTokenizedText {...props} />;
}

ChatTokenizedText.displayName = 'ChatTokenizedText';
