/**
 * Tecton ChatMessageBubble.
 *
 * Styled content container for the chat "bubble." Reads sender from parent
 * ChatMessage context to auto-style the background. Use filled for standard
 * messages and ghost when content needs alignment without a visible
 * boundary. Supports name/metadata slots aligned with bubble padding, and
 * multi-bubble grouping via the group prop for consecutive messages from the
 * same sender.
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {ChatMessageBubble as BaseChatMessageBubble} from '@astryxdesign/core/Chat';

type ChatMessageBubbleBaseProps = ComponentProps<typeof BaseChatMessageBubble>;

/** Props for {@link ChatMessageBubble}. */
export type ChatMessageBubbleProps = ChatMessageBubbleBaseProps;

export function ChatMessageBubble(props: ChatMessageBubbleProps) {
  return <BaseChatMessageBubble {...props} />;
}

ChatMessageBubble.displayName = 'ChatMessageBubble';
