/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
/** @type {import('@tecton/docs').ComponentDoc} */
export const docs = {
  name: 'ChatMessageBubble',
  displayName: 'ChatMessageBubble',
  group: 'Chat',
  category: 'Chat',
  keywords: ['chatmessagebubble'],
  usage: {
    description:
      'Styled content container for the chat "bubble." Reads sender from parent ChatMessage context to auto-style the background. Use filled for standard messages and ghost when content needs alignment without a visible boundary. Supports name/metadata slots aligned with bubble padding, and multi-bubble grouping via the group prop for consecutive messages from the same sender.',
  },
  props: [
    {
      name: 'children',
      type: 'ReactNode',
      description: 'Bubble content: text, Markdown, or any ReactNode.',
      required: true,
    },
    {
      name: 'variant',
      type: "'filled' | 'ghost'",
      description:
        "Visual variant. 'filled' renders sender-colored background (default). 'ghost' renders transparent background but keeps padding for alignment.",
      default: "'filled'",
    },
    {
      name: 'name',
      type: 'ReactNode',
      description:
        "Sender name rendered above the bubble, aligned with bubble text padding. Use on the first bubble in a message. If the first content is raw (no bubble), use ChatMessage's `name` prop instead.",
    },
    {
      name: 'metadata',
      type: 'ReactNode',
      description:
        "Metadata content rendered below the bubble, aligned with bubble text padding. Use on the last bubble in a message. If the last content is raw (no bubble), use ChatMessage's `metadata` prop instead.",
    },
    {
      name: 'group',
      type: "'first' | 'middle' | 'last'",
      description:
        'Position within a multi-bubble group. Controls corner radius reduction on the sender side. Leave unset for standalone bubbles (full radius).',
    },
    {
      name: 'width',
      type: 'SizeValue',
      description:
        'Width of the bubble (number = pixels, string = used as-is). When set, replaces the default max(80%, 280px) width cap. Combine with variant="ghost" to let custom content (an artifact card, attachments) span the full message column.',
    },
  ],
  examples: [],
  notes: [
    'Generated wrapper: Tecton publishes this component with its behaviour unchanged, under Tecton names and with Tecton glyphs on its icon props.',
  ],
};
