/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
export {ChatMessageBubble} from './ChatMessageBubble.js';
export type {ChatMessageBubbleProps} from './ChatMessageBubble.js';
