/**
 * Tecton Citation.
 *
 * Citations display inline references to external sources. Use them to
 * attribute information within AI-generated responses, articles, or anywhere
 * provenance and source links are needed.
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {Citation as BaseCitation} from '@astryxdesign/core/Citation';

type CitationBaseProps = ComponentProps<typeof BaseCitation>;

/** Props for {@link Citation}. */
export type CitationProps = CitationBaseProps;

export function Citation(props: CitationProps) {
  return <BaseCitation {...props} />;
}

Citation.displayName = 'Citation';
