/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
export {Thumbnail} from './Thumbnail.js';
export type {ThumbnailProps} from './Thumbnail.js';
