/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
export {ChatMessageMetadata} from './ChatMessageMetadata.js';
export type {ChatMessageMetadataProps} from './ChatMessageMetadata.js';
