/**
 * Tecton FieldMessage.
 *
 * FieldMessage renders validation feedback for fields and field-like
 * controls. Use it directly for custom controls that need the same error,
 * warning, or success presentation as Field.
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {FieldStatus as BaseFieldMessage} from '@astryxdesign/core/FieldStatus';

type FieldMessageBaseProps = ComponentProps<typeof BaseFieldMessage>;

/** Props for {@link FieldMessage}. */
export type FieldMessageProps = FieldMessageBaseProps;

export function FieldMessage(props: FieldMessageProps) {
  return <BaseFieldMessage {...props} />;
}

FieldMessage.displayName = 'FieldMessage';
