/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
/** @type {import('@tecton/docs').ComponentDoc} */
export const docs = {
  name: 'FieldMessage',
  displayName: 'FieldMessage',
  group: 'FieldMessage',
  category: 'Forms',
  keywords: ['fieldmessage'],
  usage: {
    description:
      'FieldMessage renders validation feedback for fields and field-like controls. Use it directly for custom controls that need the same error, warning, or success presentation as Field.',
    bestPractices: [
      {
        guidance: true,
        description:
          'Use attached status below bordered inputs when the message belongs to that input.',
      },
      {
        guidance: true,
        description:
          'Use detached status for controls like checkboxes, switches, and custom controls where overlap would be visually awkward.',
      },
      {
        guidance: false,
        description:
          'Use FieldMessage for general alerts or page-level notices; use Alert or Toast instead.',
      },
    ],
    anatomy: [
      {
        name: 'Message box',
        required: true,
        description: 'Painted container for the validation feedback.',
      },
      {
        name: 'Detached icon',
        required: false,
        description: 'Leading status glyph shown only by the detached variant.',
      },
      {
        name: 'Message text',
        required: true,
        description: 'Text describing the validation status.',
      },
    ],
  },
  props: [
    {
      name: 'type',
      type: "'error' | 'warning' | 'success'",
      description: 'Status type.',
      required: true,
    },
    {
      name: 'message',
      type: 'string',
      description: 'Status message text.',
      required: true,
    },
    {
      name: 'id',
      type: 'string',
      description: 'ID for aria-describedby association.',
    },
    {
      name: 'variant',
      type: "'attached' | 'detached'",
      description:
        'Visual variant: attached overlaps the input, detached floats below.',
      default: "'attached'",
    },
  ],
  examples: [],
  notes: [
    'Generated wrapper: Tecton publishes this component with its behaviour unchanged, under Tecton names and with Tecton glyphs on its icon props.',
  ],
};
