/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
export {FieldMessage} from './FieldMessage.js';
export type {FieldMessageProps} from './FieldMessage.js';
