/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
export {InputGroup} from './InputGroup.js';
export type {InputGroupProps} from './InputGroup.js';
