/**
 * Tecton InputGroup.
 *
 * InputGroup connects an input with prefix/suffix addons in a single visual
 * unit. Use it for URL fields, currency inputs, search fields with action
 * buttons, or any input that needs contextual decorations.
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {InputGroup as BaseInputGroup} from '@astryxdesign/core/InputGroup';

type InputGroupBaseProps = ComponentProps<typeof BaseInputGroup>;

/** Props for {@link InputGroup}. */
export type InputGroupProps = InputGroupBaseProps;

export function InputGroup(props: InputGroupProps) {
  return <BaseInputGroup {...props} />;
}

InputGroup.displayName = 'InputGroup';
