/**
 * Tecton Step.
 *
 * Individual step within a Stepper. Renders a progress-bar segment, an
 * indicator, and a label with optional description. Progress
 * (completed/active/not-started) is derived from the parent Stepper's
 * activeStep and this step's step index.
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {Step as BaseStep} from '@astryxdesign/core/Stepper';

type StepBaseProps = ComponentProps<typeof BaseStep>;

/** Props for {@link Step}. */
export type StepProps = StepBaseProps;

export function Step(props: StepProps) {
  return <BaseStep {...props} />;
}

Step.displayName = 'Step';
