/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
import {describe, expect, it} from 'vitest';
import {Step} from './Step.js';

describe('Step', () => {
  it('is a component', () => {
    expect(typeof Step).toBe('function');
  });

  it('names itself for the React tree', () => {
    expect(Step.displayName).toBe('Step');
  });
});
