/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
export {ResizeHandle} from './ResizeHandle.js';
export type {ResizeHandleProps} from './ResizeHandle.js';
