/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
import {describe, expect, it} from 'vitest';
import {ResizeHandle} from './ResizeHandle.js';

describe('ResizeHandle', () => {
  it('is a component', () => {
    expect(typeof ResizeHandle).toBe('function');
  });

  it('names itself for the React tree', () => {
    expect(ResizeHandle.displayName).toBe('ResizeHandle');
  });
});
