/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
/** @type {import('@tecton/docs').ComponentDoc} */
export const docs = {
  name: 'ResizeHandle',
  displayName: 'ResizeHandle',
  group: 'ResizeHandle',
  category: 'Layout',
  keywords: [
    'resize',
    'resizable',
    'split',
    'splitter',
    'panel',
    'drag',
    'separator',
    'divider',
    'handle',
    'grip',
  ],
  usage: {
    description:
      'Hook-based resizable panel system. useResizable() manages size state and ResizeHandle provides the interactive pill-grip separator. Pass resize props to existing layout components via their resizable prop.',
    bestPractices: [
      {
        guidance: true,
        description:
          'Use percent(value, {min: pixel(value)}) or percent(value, {max: pixel(value)}) when a percentage needs exactly one pixel floor or ceiling. Reuse Table’s pixel() helper; numbers, exact Npx, and pixel(value) remain pixels. State, persistence, callbacks, paint, and ARIA remain resolved pixels.',
      },
      {
        guidance: true,
        description:
          'Pass the returned props to the resizable prop on LayoutPanel or SideNav.',
      },
      {
        guidance: true,
        description:
          'Provide an accessible label on each ResizeHandle when multiple handles exist (e.g. "Resize sidebar", "Resize terminal").',
      },
      {
        guidance: false,
        description:
          'Wrap panels in extra container components for resize. The hook-first architecture avoids extra DOM; use it directly on existing components.',
      },
    ],
    anatomy: [
      {
        name: 'Handle',
        required: true,
        description:
          'Focusable separator that owns pointer and keyboard resize interaction.',
      },
      {
        name: 'Grip pill',
        required: false,
        description:
          'Default visible grip indicator; custom handle content can replace it.',
      },
      {
        name: 'Grab zone',
        required: true,
        description:
          'Invisible enlarged pointer region aligned with the grip or divider.',
      },
    ],
  },
  props: [],
  examples: ['ResizableSidebar'],
  notes: [
    'Generated wrapper: Tecton publishes this component with its behaviour unchanged, under Tecton names and with Tecton glyphs on its icon props.',
  ],
};
