/**
 * Tecton ResizeHandle.
 *
 * Hook-based resizable panel system. useResizable() manages size state and
 * ResizeHandle provides the interactive pill-grip separator. Pass resize
 * props to existing layout components via their resizable prop.
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {ResizeHandle as BaseResizeHandle} from '@astryxdesign/core/Resizable';

type ResizeHandleBaseProps = ComponentProps<typeof BaseResizeHandle>;

/** Props for {@link ResizeHandle}. */
export type ResizeHandleProps = ResizeHandleBaseProps;

export function ResizeHandle(props: ResizeHandleProps) {
  return <BaseResizeHandle {...props} />;
}

ResizeHandle.displayName = 'ResizeHandle';
