/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
import {describe, expect, it} from 'vitest';
import {ChatToolCalls} from './ChatToolCalls.js';

describe('ChatToolCalls', () => {
  it('is a component', () => {
    expect(typeof ChatToolCalls).toBe('function');
  });

  it('names itself for the React tree', () => {
    expect(ChatToolCalls.displayName).toBe('ChatToolCalls');
  });
});
