/**
 * Tecton ChatToolCalls.
 *
 * ChatToolCalls displays tool or function call invocations from an LLM
 * response. Pass an array of calls and the component handles the rest: a
 * single call renders inline, while multiple calls collapse into a summary
 * with the latest call visible at the surface. Use it anywhere an AI agent
 * shows what actions it took.
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {ChatToolCalls as BaseChatToolCalls} from '@astryxdesign/core/Chat';

type ChatToolCallsBaseProps = ComponentProps<typeof BaseChatToolCalls>;

/** Props for {@link ChatToolCalls}. */
export type ChatToolCallsProps = ChatToolCallsBaseProps;

export function ChatToolCalls(props: ChatToolCallsProps) {
  return <BaseChatToolCalls {...props} />;
}

ChatToolCalls.displayName = 'ChatToolCalls';
