/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
import {describe, expect, it} from 'vitest';
import {AutocompleteItem} from './AutocompleteItem.js';

describe('AutocompleteItem', () => {
  it('is a component', () => {
    expect(typeof AutocompleteItem).toBe('function');
  });

  it('names itself for the React tree', () => {
    expect(AutocompleteItem.displayName).toBe('AutocompleteItem');
  });
});
