/**
 * Tecton AutocompleteItem.
 *
 * Default dropdown item renderer for typeahead results. Shows label with
 * optional icon, description, and avatar. Exported for use in custom
 * renderItem implementations.
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {TypeaheadItem as BaseAutocompleteItem} from '@astryxdesign/core/Typeahead';
import {renderIcon, type TectonIconRef} from '../../icons/renderIcon.js';

type AutocompleteItemBaseProps = ComponentProps<typeof BaseAutocompleteItem>;

/** Props for {@link AutocompleteItem}. */
export interface AutocompleteItemProps extends Omit<
  AutocompleteItemBaseProps,
  'icon'
> {
  /**
   * Icon or avatar to display before the label. Takes a Tecton glyph name
   * or an SVG component.
   */
  icon?: TectonIconRef;
}

export function AutocompleteItem({icon, ...rest}: AutocompleteItemProps) {
  return (
    <BaseAutocompleteItem
      {...(rest as AutocompleteItemBaseProps)}
      icon={renderIcon(icon)}
    />
  );
}

AutocompleteItem.displayName = 'AutocompleteItem';
