/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
export {AutocompleteItem} from './AutocompleteItem.js';
export type {AutocompleteItemProps} from './AutocompleteItem.js';
