/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
export {TopNavMegaMenuFeaturedCard} from './TopNavMegaMenuFeaturedCard.js';
export type {TopNavMegaMenuFeaturedCardProps} from './TopNavMegaMenuFeaturedCard.js';
