/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
import {describe, expect, it} from 'vitest';
import {TopNavMegaMenuFeaturedCard} from './TopNavMegaMenuFeaturedCard.js';

describe('TopNavMegaMenuFeaturedCard', () => {
  it('is a component', () => {
    expect(typeof TopNavMegaMenuFeaturedCard).toBe('function');
  });

  it('names itself for the React tree', () => {
    expect(TopNavMegaMenuFeaturedCard.displayName).toBe(
      'TopNavMegaMenuFeaturedCard',
    );
  });
});
