/**
 * Tecton TopNavMegaMenuFeaturedCard.
 *
 * Standard featured card for the TopNavMegaMenu featured slot. Provides a
 * consistent card with optional image, title, description, and CTA link.
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {TopNavMegaMenuFeaturedCard as BaseTopNavMegaMenuFeaturedCard} from '@astryxdesign/core/TopNav';

type TopNavMegaMenuFeaturedCardBaseProps = ComponentProps<
  typeof BaseTopNavMegaMenuFeaturedCard
>;

/** Props for {@link TopNavMegaMenuFeaturedCard}. */
export type TopNavMegaMenuFeaturedCardProps =
  TopNavMegaMenuFeaturedCardBaseProps;

export function TopNavMegaMenuFeaturedCard(
  props: TopNavMegaMenuFeaturedCardProps,
) {
  return <BaseTopNavMegaMenuFeaturedCard {...props} />;
}

TopNavMegaMenuFeaturedCard.displayName = 'TopNavMegaMenuFeaturedCard';
