/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
export {BottomSheet} from './BottomSheet.js';
export type {BottomSheetProps} from './BottomSheet.js';
