/**
 * Tecton ClickableCard.
 *
 * An interactive card for navigation or action targets. Nested interactive
 * elements work independently.
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {ClickableCard as BaseClickableCard} from '@astryxdesign/core/ClickableCard';

type ClickableCardBaseProps = ComponentProps<typeof BaseClickableCard>;

/** Props for {@link ClickableCard}. */
export type ClickableCardProps = ClickableCardBaseProps;

export function ClickableCard(props: ClickableCardProps) {
  return <BaseClickableCard {...props} />;
}

ClickableCard.displayName = 'ClickableCard';
