/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
/** @type {import('@tecton/docs').ComponentDoc} */
export const docs = {
  name: 'ChatMessage',
  displayName: 'ChatMessage',
  group: 'Chat',
  category: 'Chat',
  keywords: ['chatmessage'],
  usage: {
    description:
      'Sender context wrapper: handles avatar, name, metadata, and alignment based on sender role.',
  },
  props: [
    {
      name: 'sender',
      type: "'user' | 'assistant' | 'system'",
      description: 'Who sent this message: controls alignment and layout.',
      required: true,
    },
    {
      name: 'children',
      type: 'ReactNode',
      description:
        'Free-form content: bubbles, asset lists, tool calls, images. Custom (non-bubble) children render flush with the message edge; wrap them in a ghost ChatMessageBubble to align them with the bubble text column.',
      required: true,
    },
    {
      name: 'avatar',
      type: 'ReactNode',
      description:
        'Avatar element rendered beside the message. Typically Avatar.',
    },
    {
      name: 'name',
      type: 'ReactNode',
      description:
        "Sender name rendered above the message body. Use when the first child is raw content (not a bubble). If the first child is a bubble, put the name on the bubble's `name` prop instead.",
    },
    {
      name: 'metadata',
      type: 'ReactNode',
      description:
        "Metadata rendered below the message body. Use when the last child is raw content (not a bubble). If the last child is a bubble, put metadata on the bubble's `metadata` prop instead.",
    },
    {
      name: 'density',
      type: "'compact' | 'balanced' | 'spacious'",
      description: 'Visual density. Inherited from list context if not set.',
    },
  ],
  examples: [
    'ChatMessageAvatarName',
    'ChatMessageGhost',
    'ChatMessageMultiBubble',
    'ChatMessageShowcase',
  ],
  notes: [
    'Generated wrapper: Tecton publishes this component with its behaviour unchanged, under Tecton names and with Tecton glyphs on its icon props.',
  ],
};
