/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
export {ChatMessage} from './ChatMessage.js';
export type {ChatMessageProps} from './ChatMessage.js';
