/**
 * `@tecton/react/Collapsible` — the `Collapsible` module, as the design system publishes it.
 *
 * @generated by packages/react/scripts/generate-modules.mjs — do not edit.
 */
export * from '@astryxdesign/core/Collapsible';
