/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
export {LayoutContent} from './LayoutContent.js';
export type {LayoutContentProps} from './LayoutContent.js';
