/**
 * Tecton DateTimeInput.
 *
 * DateTimeInput combines date and time selection in one field. The closed
 * segments stay side by side when at least 400px is available and wrap into
 * full-width rows below 400px, independent of viewport width. Use it for
 * scheduling, event creation, deadline setting, or any form field that needs
 * a specific datetime.
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {DateTimeInput as BaseDateTimeInput} from '@astryxdesign/core/DateTimeInput';

type DateTimeInputBaseProps = ComponentProps<typeof BaseDateTimeInput>;

/** Props for {@link DateTimeInput}. */
export type DateTimeInputProps = DateTimeInputBaseProps;

export function DateTimeInput(props: DateTimeInputProps) {
  return <BaseDateTimeInput {...props} />;
}

DateTimeInput.displayName = 'DateTimeInput';
