/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
import {describe, expect, it} from 'vitest';
import {DateRangeInput} from './DateRangeInput.js';

describe('DateRangeInput', () => {
  it('is a component', () => {
    expect(typeof DateRangeInput).toBe('function');
  });

  it('names itself for the React tree', () => {
    expect(DateRangeInput.displayName).toBe('DateRangeInput');
  });
});
