/**
 * Tecton DateRangeInput.
 *
 * DateRangeInput lets users select a start and end date from a dual-month
 * calendar popover. Use it for filtering data by time period, report
 * generation, analytics dashboards, and booking flows.
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {DateRangeInput as BaseDateRangeInput} from '@astryxdesign/core/DateRangeInput';

type DateRangeInputBaseProps = ComponentProps<typeof BaseDateRangeInput>;

/** Props for {@link DateRangeInput}. */
export type DateRangeInputProps = DateRangeInputBaseProps;

export function DateRangeInput(props: DateRangeInputProps) {
  return <BaseDateRangeInput {...props} />;
}

DateRangeInput.displayName = 'DateRangeInput';
