/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
export {DateRangeInput} from './DateRangeInput.js';
export type {DateRangeInputProps} from './DateRangeInput.js';
