/**
 * Tecton TopNav.
 *
 * TopNav is a horizontal navigation bar for product-level navigation in
 * application headers. Use TopNav for 5 or fewer always-visible navigation
 * items, or minimal navigation paired with search and controls. For complex
 * navigation hierarchies, use a sidebar; to filter content, use tabs or
 * filter buttons instead.
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {TopNav as BaseTopNav} from '@astryxdesign/core/TopNav';

type TopNavBaseProps = ComponentProps<typeof BaseTopNav>;

/** Props for {@link TopNav}. */
export type TopNavProps = TopNavBaseProps;

export function TopNav(props: TopNavProps) {
  return <BaseTopNav {...props} />;
}

TopNav.displayName = 'TopNav';
