/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
export {Outline} from './Outline.js';
export type {OutlineProps} from './Outline.js';
