/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
/** @type {import('@tecton/docs').ComponentDoc} */
export const docs = {
  name: 'Outline',
  displayName: 'Outline',
  group: 'Outline',
  category: 'Navigation',
  keywords: [
    'outline',
    'table of contents',
    'toc',
    'heading navigation',
    'scroll spy',
    'documentation',
    'anchors',
    'sliding indicator',
  ],
  usage: {
    description:
      'A table-of-contents sidebar for documentation pages, help centers, wikis, and long settings pages. Use it for navigation within a single page, not for app routes. Features a sliding indicator track that animates to the active heading. The list is a single tab stop: arrow keys move between headings, Home/End jump to the ends, and Enter/Space activate.',
    bestPractices: [
      {
        guidance: true,
        description:
          'Pass a flat ordered list of headings and let level control indentation.',
      },
      {
        guidance: true,
        description:
          'Use activeId when custom scroll logic owns the active section.',
      },
      {
        guidance: true,
        description:
          'Use density="compact" in dense sidebars where vertical space is tight.',
      },
      {
        guidance: true,
        description:
          'Use useOutlineFromMarkdown or useOutlineFromDOM when headings are generated from content.',
      },
      {
        guidance: true,
        description:
          'Pass scrollContainerRef when the content scrolls in a split pane, modal, or panel instead of the viewport.',
      },
      {
        guidance: true,
        description:
          'Set offset to the height of a fixed header that overlays the content, so headings land below it instead of underneath it.',
      },
      {
        guidance: false,
        description:
          'Use Outline for application navigation - use SideNav or TopNav for routes.',
      },
      {
        guidance: false,
        description:
          'Use Outline for expandable hierarchy - use TreeView when nodes need expand and collapse.',
      },
      {
        guidance: false,
        description:
          'Rely on onNavigateEnd to mean "arrived" - it also fires when the user interrupts the scroll.',
      },
    ],
    anatomy: [
      {
        name: 'Outline',
        required: true,
        description:
          'Navigation container for the same-page heading links and indicator.',
      },
      {
        name: 'Heading link',
        required: true,
        description:
          'Anchor for one heading, indented by level and marked when active.',
      },
      {
        name: 'Label',
        required: true,
        description: 'Heading text displayed inside its heading link.',
      },
      {
        name: 'Indicator track',
        required: true,
        description: 'Painted vertical rule behind the active indicator.',
      },
      {
        name: 'Active indicator',
        required: true,
        description:
          'Sliding bar positioned beside the currently active heading link.',
      },
    ],
  },
  props: [],
  examples: [
    'OutlineControlled',
    'OutlineDeepNesting',
    'OutlineDensity',
    'OutlineShowcase',
  ],
  notes: [
    'Generated wrapper: Tecton publishes this component with its behaviour unchanged, under Tecton names and with Tecton glyphs on its icon props.',
  ],
};
