/**
 * Tecton Outline.
 *
 * A table-of-contents sidebar for documentation pages, help centers, wikis,
 * and long settings pages. Use it for navigation within a single page, not
 * for app routes. Features a sliding indicator track that animates to the
 * active heading. The list is a single tab stop: arrow keys move between
 * headings, Home/End jump to the ends, and Enter/Space activate.
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {Outline as BaseOutline} from '@astryxdesign/core/Outline';

type OutlineBaseProps = ComponentProps<typeof BaseOutline>;

/** Props for {@link Outline}. */
export type OutlineProps = OutlineBaseProps;

export function Outline(props: OutlineProps) {
  return <BaseOutline {...props} />;
}

Outline.displayName = 'Outline';
