/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
export {LayoutFooter} from './LayoutFooter.js';
export type {LayoutFooterProps} from './LayoutFooter.js';
