/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
import {describe, expect, it} from 'vitest';
import {LayoutFooter} from './LayoutFooter.js';

describe('LayoutFooter', () => {
  it('is a component', () => {
    expect(typeof LayoutFooter).toBe('function');
  });

  it('names itself for the React tree', () => {
    expect(LayoutFooter.displayName).toBe('LayoutFooter');
  });
});
