/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
export {Overlay} from './Overlay.js';
export type {OverlayProps} from './Overlay.js';
