/**
 * Tecton Overlay.
 *
 * Overlay layers action or supporting content over media, cards, video, or
 * other bounded surfaces with an optional scrim and reveal behavior.
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {Overlay as BaseOverlay} from '@astryxdesign/core/Overlay';

type OverlayBaseProps = ComponentProps<typeof BaseOverlay>;

/** Props for {@link Overlay}. */
export type OverlayProps = OverlayBaseProps;

export function Overlay(props: OverlayProps) {
  return <BaseOverlay {...props} />;
}

Overlay.displayName = 'Overlay';
