/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
import {describe, expect, it} from 'vitest';
import {Overlay} from './Overlay.js';

describe('Overlay', () => {
  it('is a component', () => {
    expect(typeof Overlay).toBe('function');
  });

  it('names itself for the React tree', () => {
    expect(Overlay.displayName).toBe('Overlay');
  });
});
