/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
export {SideNavSection} from './SideNavSection.js';
export type {SideNavSectionProps} from './SideNavSection.js';
