/**
 * Tecton SideNavSection.
 *
 * Section grouping with an optional title, subtitle, and end content.
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {SideNavSection as BaseSideNavSection} from '@astryxdesign/core/SideNav';

type SideNavSectionBaseProps = ComponentProps<typeof BaseSideNavSection>;

/** Props for {@link SideNavSection}. */
export type SideNavSectionProps = SideNavSectionBaseProps;

export function SideNavSection(props: SideNavSectionProps) {
  return <BaseSideNavSection {...props} />;
}

SideNavSection.displayName = 'SideNavSection';
