/**
 * Tecton ChatComposerTokenElement.
 *
 * Renders a single token chip outside the contentEditable input.
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {ChatComposerTokenElement as BaseChatComposerTokenElement} from '@astryxdesign/core/Chat';

type ChatComposerTokenElementBaseProps = ComponentProps<
  typeof BaseChatComposerTokenElement
>;

/** Props for {@link ChatComposerTokenElement}. */
export type ChatComposerTokenElementProps = ChatComposerTokenElementBaseProps;

export function ChatComposerTokenElement(props: ChatComposerTokenElementProps) {
  return <BaseChatComposerTokenElement {...props} />;
}

ChatComposerTokenElement.displayName = 'ChatComposerTokenElement';
