/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
import {describe, expect, it} from 'vitest';
import {ChatComposerTokenElement} from './ChatComposerTokenElement.js';

describe('ChatComposerTokenElement', () => {
  it('is a component', () => {
    expect(typeof ChatComposerTokenElement).toBe('function');
  });

  it('names itself for the React tree', () => {
    expect(ChatComposerTokenElement.displayName).toBe(
      'ChatComposerTokenElement',
    );
  });
});
