/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
/** @type {import('@tecton/docs').ComponentDoc} */
export const docs = {
  name: 'ChatComposerTokenElement',
  displayName: 'ChatComposerTokenElement',
  group: 'Chat',
  category: 'Chat',
  keywords: ['chatcomposertokenelement'],
  usage: {
    description:
      'Renders a single token chip outside the contentEditable input.',
  },
  props: [
    {
      name: 'token',
      type: 'ChatComposerToken',
      description:
        'The token to render. Pass a badge config ({ value, label, variant?, icon? }) for the common case, or a custom render ({ value, render }) for full control.',
      required: true,
    },
  ],
  examples: [],
  notes: [
    'Generated wrapper: Tecton publishes this component with its behaviour unchanged, under Tecton names and with Tecton glyphs on its icon props.',
  ],
};
