/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
export {NavIcon} from './NavIcon.js';
export type {NavIconProps} from './NavIcon.js';
