/**
 * Tecton NavIcon.
 *
 * NavIcon is a circular icon container with an accent-colored background.
 * Use it in navigation headers such as TopNavHeading and PageNavHeader to
 * visually identify a section or application.
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {NavIcon as BaseNavIcon} from '@astryxdesign/core/NavIcon';
import {tectonIconNode, type TectonIconRef} from '../../icons/renderIcon.js';

type NavIconBaseProps = ComponentProps<typeof BaseNavIcon>;

/** Props for {@link NavIcon}. */
export interface NavIconProps extends Omit<NavIconBaseProps, 'icon'> {
  /**
   * The icon element to render inside the circular background. Should be
   * an Icon or similar icon component. Takes a Tecton glyph name or an SVG
   * component.
   */
  icon?: TectonIconRef | NavIconBaseProps['icon'];
}

export function NavIcon({icon, ...rest}: NavIconProps) {
  return (
    <BaseNavIcon
      {...(rest as NavIconBaseProps)}
      icon={tectonIconNode(icon) as NavIconBaseProps['icon']}
    />
  );
}

NavIcon.displayName = 'NavIcon';
