/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
/** @type {import('@tecton/docs').ComponentDoc} */
export const docs = {
  name: 'AvatarGroupOverflow',
  displayName: 'AvatarGroupOverflow',
  group: 'AvatarGroup',
  category: 'Content',
  keywords: ['avatargroupoverflow'],
  usage: {
    description:
      'AvatarGroupOverflow appears at the end of an AvatarGroup to summarize people who are not shown individually. Use it when a group is sliced to a small number of visible avatars but the hidden count still matters.',
    bestPractices: [
      {
        guidance: true,
        description:
          'Pass the real hidden count to `count` so the accessible label matches the visible indicator.',
      },
      {
        guidance: true,
        description:
          'Use short custom text such as `+12` or `99+`. The indicator is circular for short counts and grows into a pill for wider counts so the number always fits.',
      },
      {
        guidance: true,
        description:
          'Provide `onClick` when the overflow opens a member list, popover, or detail view.',
      },
      {
        guidance: false,
        description:
          'Do not pass custom text that disagrees with `count`; `count` continues to provide the accessible label.',
      },
      {
        guidance: false,
        description:
          'Do not use long labels inside the indicator; place longer participant details next to the group instead.',
      },
    ],
    anatomy: [
      {
        name: 'Count label',
        required: true,
        description:
          'The compact `+N` or custom count text displayed inside the circular indicator.',
      },
      {
        name: 'Button behavior',
        required: false,
        description:
          'When `onClick` is provided, the indicator becomes an interactive button with focus and hover states.',
      },
    ],
  },
  props: [
    {
      name: 'count',
      type: 'number',
      description:
        'The number of hidden avatars. Used for the default `+N` label and the accessible label.',
      required: true,
    },
    {
      name: 'children',
      type: 'ReactNode',
      description:
        'Optional custom count text rendered inside the indicator. Omit to use the default `+N` label.',
    },
    {
      name: 'onClick',
      type: '() => void',
      description:
        'Callback fired when the overflow indicator is clicked. When provided, the indicator renders as a focusable button.',
    },
    {
      name: 'ref',
      type: 'React.Ref<HTMLElement>',
      description: 'Ref forwarded to the overflow indicator element.',
    },
    {
      name: 'xstyle',
      type: 'StyleXStyles',
      description: 'stylex.create() value — not an inline style object.',
    },
  ],
  examples: [
    'AvatarGroupOverflowCustomText',
    'AvatarGroupOverflowDefault',
    'AvatarGroupOverflowShowcase',
  ],
  notes: [
    'Generated wrapper: Tecton publishes this component with its behaviour unchanged, under Tecton names and with Tecton glyphs on its icon props.',
  ],
};
