/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
export {AvatarGroupOverflow} from './AvatarGroupOverflow.js';
export type {AvatarGroupOverflowProps} from './AvatarGroupOverflow.js';
