/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
/** @type {import('@tecton/docs').ComponentDoc} */
export const docs = {
  name: 'NavHeadingMenu',
  displayName: 'NavHeadingMenu',
  group: 'NavHeadingMenu',
  category: 'Navigation',
  keywords: ['nav', 'menu', 'navigation', 'heading', 'menu-item', 'popover'],
  usage: {
    description:
      'Accessible menu container and items for nav heading popovers. NavHeadingMenu provides role="menu" with keyboard navigation; NavHeadingMenuItem renders individual selectable items. Pass as the menu prop of SideNavHeading or TopNavHeading.',
    anatomy: [
      {
        name: 'Menu',
        required: true,
        description:
          'Menu container for nav-heading actions, with menu semantics and keyboard navigation.',
      },
      {
        name: 'ItemRow',
        required: true,
        description: 'Selectable action or navigation link inside the Menu.',
      },
      {
        name: 'Icon',
        required: false,
        description:
          'Optional Icon-rendered artwork shown before an ItemRow label.',
      },
      {
        name: 'Text-rendered item label',
        required: false,
        description: 'String ItemRow label rendered through Text.',
      },
      {
        name: 'Caller-rendered item label',
        required: false,
        description:
          'Non-string ItemRow label content rendered directly by the caller.',
      },
      {
        name: 'ItemRow description',
        required: false,
        description: 'Optional supporting description rendered through Text.',
      },
    ],
  },
  props: [
    {
      name: 'children',
      type: 'ReactNode',
      description: 'Menu items.',
      required: true,
    },
    {
      name: 'size',
      type: "'sm' | 'md' | 'lg'",
      description: 'Controls min-width and item padding.',
      default: "'md'",
    },
    {
      name: 'minWidth',
      type: 'number | string',
      description: 'Minimum width override.',
    },
    {
      name: 'xstyle',
      type: 'StyleXStyles',
      description:
        'StyleX styles for layout customization (margins, positioning, sizing). Must be a stylex.create() value, not an inline style object like style={{}}.',
    },
  ],
  examples: [],
  notes: [
    'Generated wrapper: Tecton publishes this component with its behaviour unchanged, under Tecton names and with Tecton glyphs on its icon props.',
  ],
};
