/**
 * Tecton NavHeadingMenu.
 *
 * Accessible menu container and items for nav heading popovers.
 * NavHeadingMenu provides role="menu" with keyboard navigation;
 * NavHeadingMenuItem renders individual selectable items. Pass as the menu
 * prop of SideNavHeading or TopNavHeading.
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {NavHeadingMenu as BaseNavHeadingMenu} from '@astryxdesign/core/NavMenu';

type NavHeadingMenuBaseProps = ComponentProps<typeof BaseNavHeadingMenu>;

/** Props for {@link NavHeadingMenu}. */
export type NavHeadingMenuProps = NavHeadingMenuBaseProps;

export function NavHeadingMenu(props: NavHeadingMenuProps) {
  return <BaseNavHeadingMenu {...props} />;
}

NavHeadingMenu.displayName = 'NavHeadingMenu';
