/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
export {SelectableCard} from './SelectableCard.js';
export type {SelectableCardProps} from './SelectableCard.js';
