/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
/** @type {import('@tecton/docs').ComponentDoc} */
export const docs = {
  name: 'SelectableCard',
  displayName: 'SelectableCard',
  group: 'SelectableCard',
  category: 'Surfaces',
  keywords: ['card', 'selectable', 'toggle', 'checkbox', 'radio', 'selection'],
  usage: {
    description:
      'A card that toggles between selected and unselected states with an accent border. For navigation use ClickableCard.',
    bestPractices: [
      {
        guidance: true,
        description: 'Use for plan pickers, filter chips, or option grids.',
      },
      {
        guidance: true,
        description:
          'For single-select track one ID; for multi-select use a Set.',
      },
      {
        guidance: true,
        description: 'When focused, toggle selection with Space or Enter.',
      },
      {
        guidance: false,
        description: 'Use for navigation; use ClickableCard for that.',
      },
    ],
    anatomy: [
      {
        name: 'Container',
        required: true,
        description: 'Interactive div with accent border on selection.',
      },
      {
        name: 'Content',
        required: true,
        description: 'Children rendered inside the card.',
      },
    ],
  },
  props: [
    {
      name: 'label',
      type: 'string',
      description: 'Accessibility label.',
      required: true,
    },
    {
      name: 'isSelected',
      type: 'boolean',
      description: 'Controlled selection state.',
      required: true,
    },
    {
      name: 'onChange',
      type: '(isSelected: boolean) => void',
      description: 'Called when toggled.',
      required: true,
    },
    {
      name: 'isDisabled',
      type: 'boolean',
      description: 'Disables the card.',
      default: 'false',
    },
    {
      name: 'children',
      type: 'ReactNode',
      description: 'Card content.',
    },
    {
      name: 'padding',
      type: '0 | 0.5 | 1 | 1.5 | 2 | 3 | 4 | 5 | 6 | 8 | 10',
      description: 'Inner padding.',
      default: '4',
    },
    {
      name: 'variant',
      type: "'default' | 'transparent' | 'muted' | 'blue' | 'cyan' | 'gray' | 'green' | 'orange' | 'pink' | 'purple' | 'red' | 'teal' | 'yellow'",
      description: 'Background color variant.',
      default: "'default'",
    },
    {
      name: 'elevation',
      type: "'none' | 'low' | 'med' | 'high'",
      description:
        'Resting shadow depth. The selection ring composes on top, so a selected card keeps its shadow.',
      default: "'none'",
    },
    {
      name: 'width',
      type: 'SizeValue',
      description: 'Card width.',
    },
    {
      name: 'height',
      type: 'SizeValue',
      description: 'Card height.',
    },
    {
      name: 'maxWidth',
      type: 'SizeValue',
      description: 'Maximum card width.',
    },
    {
      name: 'xstyle',
      type: 'StyleXStyles',
      description:
        'StyleX styles for layout customization (margins, positioning, sizing). Must be a stylex.create() value, not an inline style object like style={{}}.',
    },
  ],
  examples: [],
  notes: [
    'Generated wrapper: Tecton publishes this component with its behaviour unchanged, under Tecton names and with Tecton glyphs on its icon props.',
  ],
};
