/**
 * Tecton ChatComposerInput.
 *
 * Rich text input for the chat composer. Supports trigger menus (type @ or /
 * to open a typeahead), inline tokens rendered as badges, message history
 * recall with ArrowUp/Down, paste/drop file handling, and a 16px
 * touch-device font-size floor to prevent iOS input zoom. Pass it to
 * ChatComposer's input slot when you need more than a plain textarea.
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {ChatComposerInput as BaseChatComposerInput} from '@astryxdesign/core/Chat';

type ChatComposerInputBaseProps = ComponentProps<typeof BaseChatComposerInput>;

/** Props for {@link ChatComposerInput}. */
export type ChatComposerInputProps = ChatComposerInputBaseProps;

export function ChatComposerInput(props: ChatComposerInputProps) {
  return <BaseChatComposerInput {...props} />;
}

ChatComposerInput.displayName = 'ChatComposerInput';
