/**
 * `@tecton/react/i18n` — the `i18n` module, as the design system publishes it.
 *
 * @generated by packages/react/scripts/generate-modules.mjs — do not edit.
 */
export * from '@astryxdesign/core/i18n';
