/**
 * Tecton MetadataListItem.
 *
 * A single labeled metadata value within an MetadataList.
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {MetadataListItem as BaseMetadataListItem} from '@astryxdesign/core/MetadataList';
import {tectonIconNode, type TectonIconRef} from '../../icons/renderIcon.js';

type MetadataListItemBaseProps = ComponentProps<typeof BaseMetadataListItem>;

/** Props for {@link MetadataListItem}. */
export interface MetadataListItemProps extends Omit<
  MetadataListItemBaseProps,
  'icon'
> {
  /**
   * Icon rendered before the label text. Takes a Tecton glyph name or an
   * SVG component.
   */
  icon?: TectonIconRef | MetadataListItemBaseProps['icon'];
}

export function MetadataListItem({icon, ...rest}: MetadataListItemProps) {
  return (
    <BaseMetadataListItem
      {...(rest as MetadataListItemBaseProps)}
      icon={tectonIconNode(icon) as MetadataListItemBaseProps['icon']}
    />
  );
}

MetadataListItem.displayName = 'MetadataListItem';
