/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
export {SelectChoice} from './SelectChoice.js';
export type {SelectChoiceProps} from './SelectChoice.js';
