/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
import {describe, expect, it} from 'vitest';
import {SelectChoice} from './SelectChoice.js';

describe('SelectChoice', () => {
  it('is a component', () => {
    expect(typeof SelectChoice).toBe('function');
  });

  it('names itself for the React tree', () => {
    expect(SelectChoice.displayName).toBe('SelectChoice');
  });
});
