/**
 * Tecton SelectChoice.
 *
 * Helper component for custom item rendering inside an Select renderOption
 * prop.
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {SelectorOption as BaseSelectChoice} from '@astryxdesign/core/Selector';
import {tectonIconValue, type TectonIconRef} from '../../icons/renderIcon.js';

type SelectChoiceBaseProps = ComponentProps<typeof BaseSelectChoice>;

/** Props for {@link SelectChoice}. */
export interface SelectChoiceProps extends Omit<SelectChoiceBaseProps, 'icon'> {
  /**
   * Icon displayed before the label. Takes a Tecton glyph name or an SVG
   * component.
   */
  icon?: TectonIconRef | SelectChoiceBaseProps['icon'];
}

export function SelectChoice({icon, ...rest}: SelectChoiceProps) {
  return (
    <BaseSelectChoice
      {...(rest as SelectChoiceBaseProps)}
      icon={tectonIconValue(icon) as SelectChoiceBaseProps['icon']}
    />
  );
}

SelectChoice.displayName = 'SelectChoice';
