/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
import {describe, expect, it} from 'vitest';
import {ContextMenuItem} from './ContextMenuItem.js';

describe('ContextMenuItem', () => {
  it('is a component', () => {
    expect(typeof ContextMenuItem).toBe('function');
  });

  it('names itself for the React tree', () => {
    expect(ContextMenuItem.displayName).toBe('ContextMenuItem');
  });
});
