/**
 * Tecton ContextMenuItem.
 *
 * Menu item component for compound mode. Re-exported from MenuActionItem for
 * discoverability.
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {ContextMenuItem as BaseContextMenuItem} from '@astryxdesign/core/ContextMenu';
import {resolveIcon, type TectonIconRef} from '../../icons/renderIcon.js';

type ContextMenuItemBaseProps = ComponentProps<typeof BaseContextMenuItem>;

/** Props for {@link ContextMenuItem}. */
export interface ContextMenuItemProps extends Omit<
  ContextMenuItemBaseProps,
  'icon'
> {
  /**
   * Icon to display before the label. Takes a Tecton glyph name or an SVG
   * component.
   */
  icon?: TectonIconRef;
}

export function ContextMenuItem({icon, ...rest}: ContextMenuItemProps) {
  return (
    <BaseContextMenuItem
      {...(rest as ContextMenuItemBaseProps)}
      icon={resolveIcon(icon)}
    />
  );
}

ContextMenuItem.displayName = 'ContextMenuItem';
