/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
export {ContextMenuItem} from './ContextMenuItem.js';
export type {ContextMenuItemProps} from './ContextMenuItem.js';
