/**
 * Tecton LayoutPanel.
 *
 * Sidebar for navigation, settings, or inspector panels.
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {LayoutPanel as BaseLayoutPanel} from '@astryxdesign/core/Layout';

type LayoutPanelBaseProps = ComponentProps<typeof BaseLayoutPanel>;

/** Props for {@link LayoutPanel}. */
export type LayoutPanelProps = LayoutPanelBaseProps;

export function LayoutPanel(props: LayoutPanelProps) {
  return <BaseLayoutPanel {...props} />;
}

LayoutPanel.displayName = 'LayoutPanel';
