/**
 * Tecton LinkProvider.
 *
 * Wraps your app to replace the default <a> tag with a framework-specific
 * link component (e.g.
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {LinkProvider as BaseLinkProvider} from '@astryxdesign/core/Link';

type LinkProviderBaseProps = ComponentProps<typeof BaseLinkProvider>;

/** Props for {@link LinkProvider}. */
export type LinkProviderProps = LinkProviderBaseProps;

export function LinkProvider(props: LinkProviderProps) {
  return <BaseLinkProvider {...props} />;
}

LinkProvider.displayName = 'LinkProvider';
