/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
/** @type {import('@tecton/docs').ComponentDoc} */
export const docs = {
  name: 'LinkProvider',
  displayName: 'LinkProvider',
  group: 'LinkProvider',
  category: 'Providers',
  keywords: ['link', 'provider', 'router', 'nextjs', 'client-side-routing'],
  usage: {
    description:
      'Wraps your app to replace the default <a> tag with a framework-specific link component (e.g.',
  },
  props: [
    {
      name: 'component',
      type: 'LinkComponentType',
      description:
        'Link component to use for all link elements in the subtree (e.g. Next.js Link).',
      required: true,
    },
    {
      name: 'children',
      type: 'ReactNode',
      description: 'Content to render with the link provider.',
      required: true,
    },
  ],
  examples: ['LinkProviderCustomLink'],
  notes: [
    'Generated wrapper: Tecton publishes this component with its behaviour unchanged, under Tecton names and with Tecton glyphs on its icon props.',
  ],
};
