/**
 * Tecton TableFooter.
 *
 * <tfoot> wrapper for children mode. Holds summary or total rows beneath the
 * body. A row must sit inside a section: <table> cannot contain a <tr>
 * directly, because the HTML parser inserts an implied <tbody> when it
 * parses server-rendered markup and React does not when it renders on the
 * client, so the two trees mismatch on hydration. Children mode only: the
 * data-driven data={...} path renders a header and a body, never a footer.
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {TableFooter as BaseTableFooter} from '@astryxdesign/core/Table';

type TableFooterBaseProps = ComponentProps<typeof BaseTableFooter>;

/** Props for {@link TableFooter}. */
export type TableFooterProps = TableFooterBaseProps;

export function TableFooter(props: TableFooterProps) {
  return <BaseTableFooter {...props} />;
}

TableFooter.displayName = 'TableFooter';
