/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
import {describe, expect, it} from 'vitest';
import {ItemRow} from './ItemRow.js';

describe('ItemRow', () => {
  it('is a component', () => {
    expect(typeof ItemRow).toBe('function');
  });

  it('names itself for the React tree', () => {
    expect(ItemRow.displayName).toBe('ItemRow');
  });
});
