/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
/** @type {import('@tecton/docs').ComponentDoc} */
export const docs = {
  name: 'AppShell',
  displayName: 'AppShell',
  group: 'AppShell',
  category: 'Layout',
  keywords: [
    'appshell',
    'layout',
    'scaffold',
    'sidebar',
    'sidenav',
    'topnav',
    'header',
    'navigation',
    'dashboard',
    'shell',
    'page',
    'frame',
  ],
  usage: {
    description:
      'AppShell is the page shell for an application. It provides slots for top navigation, side navigation, banners, and main content. Use it as the root wrapper for every page. It handles responsive mobile navigation and skip-to-content automatically. Configure side nav collapse on SideNav with its collapsible prop.',
    bestPractices: [
      {
        guidance: true,
        description:
          'Choose the right height: use "fill" for dashboards with internal scrolling and "auto" for pages that grow with content.',
      },
      {
        guidance: true,
        description:
          'Set `contentPadding` based on content type: 4 for forms and settings, 0 for tables and dashboards.',
      },
      {
        guidance: true,
        description:
          'Give every nav slot an accessible name. AppShell renders TopNav and SideNav as separate navigation landmarks, and a screen reader lists them by name, so pass `label` to each one.',
      },
      {
        guidance: true,
        description:
          'Start the page heading inside `children`. AppShell owns the skip link, the banner landmark and the main landmark, but it renders no heading, so the first heading in the content area is the page h1.',
      },
      {
        guidance: false,
        description:
          "Nest one AppShell inside another; it's the outermost layout frame.",
      },
      {
        guidance: false,
        description:
          'Use for sub-page layouts; use Layout for content areas within AppShell.',
      },
      {
        guidance: false,
        description:
          'Add your own skip link or <main> element. AppShell already renders both, and a second main landmark makes the first ambiguous.',
      },
    ],
    anatomy: [
      {
        name: 'Page shell',
        required: true,
        description:
          'Outermost application frame that owns page-level navigation, responsive shell behavior, and the main content landmark.',
      },
      {
        name: 'Skip link',
        required: true,
        description:
          'First focusable element on the page. Visually hidden until focused, then moves focus to the main content area.',
      },
      {
        name: 'Alert',
        required: false,
        description:
          'The banner slot, for system-wide announcements. Renders above the top nav, inside the banner landmark.',
      },
      {
        name: 'Top navigation',
        required: false,
        description:
          'The topNav slot, typically TopNav. Below the mobile breakpoint it becomes a compact bar carrying the nav toggle.',
      },
      {
        name: 'Side navigation',
        required: false,
        description:
          'The sideNav slot, typically SideNav. Inline above the breakpoint, moved into the mobile drawer below it.',
      },
      {
        name: 'Main content',
        required: true,
        description:
          'children, rendered in the main landmark. Scrolls internally when height is fill, and with the page when it is auto.',
      },
      {
        name: 'Mobile nav drawer',
        required: false,
        description:
          'Generated below the breakpoint from the nav slots unless mobileNav disables or replaces it. A modal dialog: it traps focus and returns focus to the toggle on close.',
      },
    ],
  },
  props: [
    {
      name: 'children',
      type: 'ReactNode',
      description: 'Main content area, rendered inside a <main> element.',
    },
    {
      name: 'contentPadding',
      type: '0 | 0.5 | 1 | 1.5 | 2 | 3 | 4 | 5 | 6 | 8 | 10',
      description:
        'Padding for the main content area. Set based on the dominant content pattern: 4 (16px) for forms/settings/text, 0 for dashboards/maps/tables. Override individual sections with Section.',
      default: '0',
    },
    {
      name: 'topNav',
      type: 'ReactNode',
      description: 'Top navigation slot, typically TopNav.',
    },
    {
      name: 'sideNav',
      type: 'ReactNode',
      description: 'Side navigation slot, typically SideNav.',
    },
    {
      name: 'mobileNav',
      type: 'ReactNode',
      description:
        "Mobile navigation configuration. Accepts false (disable), a config object (tune auto behavior), or ReactNode (full custom drawer). The config object is {hasToggle?: boolean, isOpen?: boolean, onOpenChange?: (isOpen: boolean) => void, content?: ReactNode, breakpoint?: 'sm' | 'md' | 'lg' | 'xl' | '2xl' | 'none', defaultIsMobile?: boolean}; breakpoint defaults to 'md', resolves through the nearest Theme's widthBreakpoints, and switches to the wider layout at equality. 'none' is always non-mobile and ignores defaultIsMobile.",
    },
    {
      name: 'banner',
      type: 'ReactNode',
      description:
        'Alert slot for system-wide announcements, placed above the topNav.',
    },
    {
      name: 'height',
      type: "'fill' | 'auto'",
      description:
        "Height behavior: 'fill' makes the shell fill the viewport (100dvh) with independent scroll containers; 'auto' lets the shell grow with content and uses sticky positioning for nav.",
      default: "'fill'",
    },
    {
      name: 'variant',
      type: "'wash' | 'surface' | 'section' | 'elevated'",
      description:
        "Navigation background style controlling how nav areas contrast with content. 'wash' uses wash background, 'surface' uses surface background, 'section' adds dividers between nav and content, 'elevated' uses wash nav with elevated surface content and border radius.",
      default: "'elevated'",
    },
    {
      name: 'xstyle',
      type: 'StyleXStyles',
      description:
        'StyleX styles for layout customization (margins, positioning, sizing). Must be a stylex.create() value, not an inline style object like style={{}}.',
    },
  ],
  examples: [
    'AppShellContentOnly',
    'AppShellShowcase',
    'AppShellSideNavOnly',
    'AppShellTopNavOnly',
    'AppShellTopNavWithSideNav',
    'AppShellWithBanner',
  ],
  notes: [
    'Generated wrapper: Tecton publishes this component with its behaviour unchanged, under Tecton names and with Tecton glyphs on its icon props.',
  ],
};
