/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
import {describe, expect, it} from 'vitest';
import {AppShell} from './AppShell.js';

describe('AppShell', () => {
  it('is a component', () => {
    expect(typeof AppShell).toBe('function');
  });

  it('names itself for the React tree', () => {
    expect(AppShell.displayName).toBe('AppShell');
  });
});
