/**
 * Tecton AppShell.
 *
 * AppShell is the page shell for an application. It provides slots for top
 * navigation, side navigation, banners, and main content. Use it as the root
 * wrapper for every page. It handles responsive mobile navigation and
 * skip-to-content automatically. Configure side nav collapse on SideNav with
 * its collapsible prop.
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {AppShell as BaseAppShell} from '@astryxdesign/core/AppShell';

type AppShellBaseProps = ComponentProps<typeof BaseAppShell>;

/** Props for {@link AppShell}. */
export type AppShellProps = AppShellBaseProps;

export function AppShell(props: AppShellProps) {
  return <BaseAppShell {...props} />;
}

AppShell.displayName = 'AppShell';
