/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
export {AppShell} from './AppShell.js';
export type {AppShellProps} from './AppShell.js';
