/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
export {Kbd} from './Kbd.js';
export type {KbdProps} from './Kbd.js';
