/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
/** @type {import('@tecton/docs').ComponentDoc} */
export const docs = {
  name: 'Kbd',
  displayName: 'Kbd',
  group: 'Kbd',
  category: 'Content',
  keywords: [
    'kbd',
    'keyboard',
    'shortcut',
    'hotkey',
    'keybinding',
    'keystroke',
    'keycombo',
    'modifier',
    'accelerator',
  ],
  usage: {
    description:
      'Renders a keyboard shortcut as styled key badges. Use Kbd in tooltips, menus, and help text to show key combinations.',
    bestPractices: [
      {
        guidance: true,
        description:
          'Place shortcuts near the action they trigger: in a tooltip, menu item, or inline instruction.',
      },
      {
        guidance: true,
        description:
          "Use mod instead of ctrl or cmd; it automatically adapts to the user's platform.",
      },
      {
        guidance: false,
        description:
          'Use Kbd as the only way to discover an action; shortcuts should supplement visible controls, not replace them.',
      },
    ],
    anatomy: [
      {
        name: 'Shortcut',
        required: true,
        description:
          'Group that presents the complete keyboard shortcut and its accessible name.',
      },
      {
        name: 'Key badge',
        required: true,
        description:
          'Painted key badge rendered once for each key in the shortcut.',
      },
    ],
  },
  props: [
    {
      name: 'keys',
      type: 'string',
      description:
        'Keyboard shortcut string. Use "+" to separate keys. Special keys: mod (Cmd on Mac), ctrl, alt, shift, enter, backspace, escape, tab, up, down, left, right.',
      required: true,
    },
    {
      name: 'xstyle',
      type: 'StyleXStyles',
      description:
        'StyleX styles for layout customization (margins, positioning, sizing). Must be a stylex.create() value, not an inline style object like style={{}}.',
    },
    {
      name: 'className',
      type: 'string',
      description:
        'CSS class name for the root element. Prefer xstyle for styling; className is provided for integration with non-StyleX systems.',
    },
    {
      name: 'style',
      type: 'CSSProperties',
      description:
        'Inline styles for the root element. Prefer xstyle for styling; inline styles bypass StyleX optimization.',
    },
  ],
  examples: [
    'KbdInlineInstructions',
    'KbdMenuShortcuts',
    'KbdModifierCombos',
    'KbdShowcase',
  ],
  notes: [
    'Generated wrapper: Tecton publishes this component with its behaviour unchanged, under Tecton names and with Tecton glyphs on its icon props.',
  ],
};
