/**
 * Tecton AspectRatio.
 *
 * Maintains a fixed width-to-height ratio for its children as its container
 * resizes. Use it for media containers like videos, images, thumbnails, or
 * any content that needs consistent proportions. It takes its width from the
 * container and derives its height from the ratio, so it needs an ancestor
 * with a definite width.
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {AspectRatio as BaseAspectRatio} from '@astryxdesign/core/AspectRatio';

type AspectRatioBaseProps = ComponentProps<typeof BaseAspectRatio>;

/** Props for {@link AspectRatio}. */
export type AspectRatioProps = AspectRatioBaseProps;

export function AspectRatio(props: AspectRatioProps) {
  return <BaseAspectRatio {...props} />;
}

AspectRatio.displayName = 'AspectRatio';
