/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
/** @type {import('@tecton/docs').ComponentDoc} */
export const docs = {
  name: 'DialogHeader',
  displayName: 'DialogHeader',
  group: 'Dialog',
  category: 'Overlay',
  keywords: ['dialogheader'],
  usage: {
    description:
      'Use DialogHeader to give a dialog a labelled title area and optional close control.',
    anatomy: [
      {
        name: 'Header row',
        required: true,
        description:
          'Arranges the title block, optional start/end content, and close control.',
      },
      {
        name: 'Title block',
        required: true,
        description: 'Groups the title and optional subtitle.',
      },
      {
        name: 'Close icon',
        required: false,
        description: 'Visual close glyph inside the close button.',
      },
    ],
  },
  props: [
    {
      name: 'title',
      type: 'string',
      description:
        'Dialog title (receives focus on open and labels the dialog via aria-labelledby).',
    },
    {
      name: 'subtitle',
      type: 'string',
      description: 'Subtitle below the title.',
    },
    {
      name: 'onOpenChange',
      type: '(isOpen: boolean) => unknown',
      description: 'Close button callback (no button if omitted).',
    },
    {
      name: 'startContent',
      type: 'ReactNode',
      description: 'Content before the title (e.g., a back button).',
    },
    {
      name: 'endContent',
      type: 'ReactNode',
      description: 'Content after the title, before close button.',
    },
    {
      name: 'hasDivider',
      type: 'boolean',
      description: 'Adds border at the bottom edge.',
      default: 'true',
    },
  ],
  examples: ['DialogHeaderBasic', 'DialogHeaderShowcase'],
  notes: [
    'Generated wrapper: Tecton publishes this component with its behaviour unchanged, under Tecton names and with Tecton glyphs on its icon props.',
  ],
};
