/**
 * Tecton DialogHeader.
 *
 * Use DialogHeader to give a dialog a labelled title area and optional close
 * control.
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {DialogHeader as BaseDialogHeader} from '@astryxdesign/core/Dialog';

type DialogHeaderBaseProps = ComponentProps<typeof BaseDialogHeader>;

/** Props for {@link DialogHeader}. */
export type DialogHeaderProps = DialogHeaderBaseProps;

export function DialogHeader(props: DialogHeaderProps) {
  return <BaseDialogHeader {...props} />;
}

DialogHeader.displayName = 'DialogHeader';
