/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
import {describe, expect, it} from 'vitest';
import {DialogHeader} from './DialogHeader.js';

describe('DialogHeader', () => {
  it('is a component', () => {
    expect(typeof DialogHeader).toBe('function');
  });

  it('names itself for the React tree', () => {
    expect(DialogHeader.displayName).toBe('DialogHeader');
  });
});
