/**
 * Tecton CommandPaletteItem.
 *
 * A selectable item. Accepts arbitrary children for full rendering control.
 * Registers with context for keyboard navigation when inside CommandPalette.
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {CommandPaletteItem as BaseCommandPaletteItem} from '@astryxdesign/core/CommandPalette';

type CommandPaletteItemBaseProps = ComponentProps<
  typeof BaseCommandPaletteItem
>;

/** Props for {@link CommandPaletteItem}. */
export type CommandPaletteItemProps = CommandPaletteItemBaseProps;

export function CommandPaletteItem(props: CommandPaletteItemProps) {
  return <BaseCommandPaletteItem {...props} />;
}

CommandPaletteItem.displayName = 'CommandPaletteItem';
