/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
/** @type {import('@tecton/docs').ComponentDoc} */
export const docs = {
  name: 'CommandPaletteItem',
  displayName: 'CommandPaletteItem',
  group: 'CommandPalette',
  category: 'Overlay',
  keywords: ['commandpaletteitem'],
  usage: {
    description:
      'A selectable item. Accepts arbitrary children for full rendering control. Registers with context for keyboard navigation when inside CommandPalette.',
  },
  props: [
    {
      name: 'value',
      type: 'string',
      description: 'Unique value for identification and selection.',
      required: true,
    },
    {
      name: 'children',
      type: 'ReactNode',
      description:
        'ItemRow content: render icons, descriptions, keyboard shortcuts, etc.',
      required: true,
    },
    {
      name: 'onSelect',
      type: '(value: string) => void',
      description: 'Called when this item is selected via click or Enter.',
    },
    {
      name: 'isHighlighted',
      type: 'boolean',
      description:
        'Whether this item has keyboard focus. Derived from context when inside CommandPalette.',
      default: 'false',
    },
    {
      name: 'isSelected',
      type: 'boolean',
      description: 'Whether this item is selected in picker mode.',
      default: 'false',
    },
    {
      name: 'isDisabled',
      type: 'boolean',
      description: 'Whether the item is non-interactive.',
      default: 'false',
    },
    {
      name: 'xstyle',
      type: 'StyleXStyles',
      description:
        'StyleX styles for layout customization. Must be a stylex.create() value.',
    },
  ],
  examples: [],
  notes: [
    'Generated wrapper: Tecton publishes this component with its behaviour unchanged, under Tecton names and with Tecton glyphs on its icon props.',
  ],
};
