/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
export {CommandPaletteItem} from './CommandPaletteItem.js';
export type {CommandPaletteItemProps} from './CommandPaletteItem.js';
