/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
export {StatusDot} from './StatusDot.js';
export type {StatusDotProps} from './StatusDot.js';
