/**
 * Tecton StatusDot.
 *
 * A small colored dot that communicates status like online/offline presence
 * or severity levels. Supports five semantic variants and an optional pulse
 * animation. Always pair with a visible text label, as color alone should
 * not carry meaning.
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {StatusDot as BaseStatusDot} from '@astryxdesign/core/StatusDot';
import {tectonIconNode, type TectonIconRef} from '../../icons/renderIcon.js';

type StatusDotBaseProps = ComponentProps<typeof BaseStatusDot>;

/** Props for {@link StatusDot}. */
export interface StatusDotProps extends Omit<StatusDotBaseProps, 'icon'> {
  /**
   * Optional icon rendered centered inside the dot, painted in
   * currentColor (the variant's ink). Gives the status a non-color mark,
   * so use a different icon per status. Booleans and empty strings are
   * ignored, so `cond && <Icon />` is safe. Same contract as
   * AvatarStatusDot. Takes a Tecton glyph name or an SVG component.
   */
  icon?: TectonIconRef | StatusDotBaseProps['icon'];
}

export function StatusDot({icon, ...rest}: StatusDotProps) {
  return (
    <BaseStatusDot
      {...(rest as StatusDotBaseProps)}
      icon={tectonIconNode(icon) as StatusDotBaseProps['icon']}
    />
  );
}

StatusDot.displayName = 'StatusDot';
