/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
export {SelectItem} from './SelectItem.js';
export type {SelectItemProps} from './SelectItem.js';
