/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
import {describe, expect, it} from 'vitest';
import {SelectItem} from './SelectItem.js';

describe('SelectItem', () => {
  it('is a component', () => {
    expect(typeof SelectItem).toBe('function');
  });

  it('names itself for the React tree', () => {
    expect(SelectItem.displayName).toBe('SelectItem');
  });
});
