/**
 * Tecton SelectItem.
 *
 * Helper component for custom item rendering inside an Select renderOption
 * prop.
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {SelectorOption as BaseSelectItem} from '@astryxdesign/core/Selector';
import {resolveIcon, type TectonIconRef} from '../../icons/renderIcon.js';

type SelectItemBaseProps = ComponentProps<typeof BaseSelectItem>;

/** Props for {@link SelectItem}. */
export interface SelectItemProps extends Omit<SelectItemBaseProps, 'icon'> {
  /**
   * Icon displayed before the label. Takes a Tecton glyph name or an SVG
   * component.
   */
  icon?: TectonIconRef;
}

export function SelectItem({icon, ...rest}: SelectItemProps) {
  return (
    <BaseSelectItem
      {...(rest as SelectItemBaseProps)}
      icon={resolveIcon(icon)}
    />
  );
}

SelectItem.displayName = 'SelectItem';
