/**
 * `@tecton/react/BaseProps` — the `BaseProps` module, as the design system publishes it.
 *
 * @generated by packages/react/scripts/generate-modules.mjs — do not edit.
 */
export * from '@astryxdesign/core/BaseProps';
