/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
import {describe, expect, it} from 'vitest';
import {VisuallyHidden} from './VisuallyHidden.js';

describe('VisuallyHidden', () => {
  it('is a component', () => {
    expect(typeof VisuallyHidden).toBe('function');
  });

  it('names itself for the React tree', () => {
    expect(VisuallyHidden.displayName).toBe('VisuallyHidden');
  });
});
