/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
/** @type {import('@tecton/docs').ComponentDoc} */
export const docs = {
  name: 'VisuallyHidden',
  displayName: 'VisuallyHidden',
  group: 'VisuallyHidden',
  category: 'Content',
  keywords: [
    'visually hidden',
    'sr-only',
    'screen reader',
    'accessibility',
    'a11y',
    'aria-live',
    'hidden label',
    'assistive technology',
  ],
  usage: {
    description:
      'Renders content in the accessibility tree while hiding it visually. Use for accessible names on icon-only controls, aria-live announcement regions, and supplementary screen-reader context. Deliberately has no styling props; the whole point is to stay invisible.',
    bestPractices: [
      {
        guidance: true,
        description:
          'Use to give icon-only buttons and controls an accessible name that screen readers announce.',
      },
      {
        guidance: true,
        description:
          'Render as a block element (as="div") with aria-live to announce dynamic updates like drag-and-drop or result counts.',
      },
      {
        guidance: false,
        description:
          'Use it to hide content from everyone; it stays in the accessibility tree; use conditional rendering or `hidden` to remove content entirely.',
      },
      {
        guidance: false,
        description:
          'Put interactive controls inside it; the content is not visible and cannot receive pointer input.',
      },
    ],
  },
  props: [
    {
      name: 'children',
      type: 'ReactNode',
      description:
        'Content exposed to assistive technology while hidden from sight.',
    },
    {
      name: 'as',
      type: 'ElementType',
      description:
        'HTML tag to render as. Use a block element for live regions.',
      default: "'span'",
    },
  ],
  examples: [
    'VisuallyHiddenLiveRegion',
    'VisuallyHiddenShowcase',
    'VisuallyHiddenStructuralHeading',
    'VisuallyHiddenSupplementaryContext',
  ],
  notes: [
    'Generated wrapper: Tecton publishes this component with its behaviour unchanged, under Tecton names and with Tecton glyphs on its icon props.',
  ],
};
