/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
/** @type {import('@tecton/docs').ComponentDoc} */
export const docs = {
  name: 'LocaleProvider',
  displayName: 'LocaleProvider',
  group: 'LocaleProvider',
  category: 'Providers',
  keywords: [
    'i18n',
    'internationalization',
    'localization',
    'locale',
    'translation',
    'translations',
    'provider',
    'language',
  ],
  usage: {
    description:
      'Wraps your app to set the active locale and (optionally) merge additional translation catalogs + per-locale overrides. If no provider is present, components fall back to the shipped English defaults.',
    bestPractices: [
      {
        guidance: true,
        description: '',
      },
      {
        guidance: true,
        description: '',
      },
      {
        guidance: true,
        description:
          'Use real BCP 47 tags such as `fr`, `pt-BR`, or `ar`; regional locales fall back to their base language before English.',
      },
      {
        guidance: true,
        description:
          'Set the `dir` attribute on `<html>` (or a wrapping element) yourself; the provider does not set it. Use `getLocaleDirection(locale)` to derive the value for both the provider and the DOM.',
      },
      {
        guidance: false,
        description:
          'Cast custom catalog maps to `any`; the i18n package exports `MessagesByLocale` and `Catalog` for local catalog typing.',
      },
    ],
  },
  props: [
    {
      name: 'locale',
      type: 'string',
      description:
        'BCP 47 language tag for the active locale (e.g. "en", "pt", "pt-BR", "zh-Hans"). Regional tags fall back to their base language, then to the shipped "en" catalog.',
      required: true,
    },
    {
      name: 'messages',
      type: 'MessagesByLocale',
      description: 'Optional map of BCP 47 tag to translation catalog.',
    },
    {
      name: 'overrides',
      type: 'Overrides',
      description:
        'Sparse per-locale key overrides applied on top of shipped defaults. Overrides are locale-keyed so a runtime locale swap picks up the correct set.',
    },
    {
      name: 'dir',
      type: "'ltr' | 'rtl'",
      description:
        'Explicit text-direction override for the context. When omitted, direction is derived from `locale` via `Intl.Locale.getTextInfo()`. Set both to the same value and keep them in sync.',
    },
    {
      name: 'children',
      type: 'ReactNode',
      description: 'Content to render with the internationalization provider.',
      required: true,
    },
  ],
  examples: ['LocaleProvider02Overrides', 'LocaleProvider03RtlDirection'],
  notes: [
    'Generated wrapper: Tecton publishes this component with its behaviour unchanged, under Tecton names and with Tecton glyphs on its icon props.',
  ],
};
