/**
 * Tecton LocaleProvider.
 *
 * Wraps your app to set the active locale and (optionally) merge additional
 * translation catalogs + per-locale overrides. If no provider is present,
 * components fall back to the shipped English defaults.
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {InternationalizationProvider as BaseLocaleProvider} from '@astryxdesign/core/i18n';

type LocaleProviderBaseProps = ComponentProps<typeof BaseLocaleProvider>;

/** Props for {@link LocaleProvider}. */
export type LocaleProviderProps = LocaleProviderBaseProps;

export function LocaleProvider(props: LocaleProviderProps) {
  return <BaseLocaleProvider {...props} />;
}

LocaleProvider.displayName = 'LocaleProvider';
