/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
import {describe, expect, it} from 'vitest';
import {LocaleProvider} from './LocaleProvider.js';

describe('LocaleProvider', () => {
  it('is a component', () => {
    expect(typeof LocaleProvider).toBe('function');
  });

  it('names itself for the React tree', () => {
    expect(LocaleProvider.displayName).toBe('LocaleProvider');
  });
});
