/**
 * Tecton CommandPaletteFooter.
 *
 * Footer showing keyboard navigation hints. Renders default
 * arrow/Enter/Escape hints when no children are provided.
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {CommandPaletteFooter as BaseCommandPaletteFooter} from '@astryxdesign/core/CommandPalette';

type CommandPaletteFooterBaseProps = ComponentProps<
  typeof BaseCommandPaletteFooter
>;

/** Props for {@link CommandPaletteFooter}. */
export type CommandPaletteFooterProps = CommandPaletteFooterBaseProps;

export function CommandPaletteFooter(props: CommandPaletteFooterProps) {
  return <BaseCommandPaletteFooter {...props} />;
}

CommandPaletteFooter.displayName = 'CommandPaletteFooter';
