/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
/** @type {import('@tecton/docs').ComponentDoc} */
export const docs = {
  name: 'CommandPaletteFooter',
  displayName: 'CommandPaletteFooter',
  group: 'CommandPalette',
  category: 'Overlay',
  keywords: ['commandpalettefooter'],
  usage: {
    description:
      'Footer showing keyboard navigation hints. Renders default arrow/Enter/Escape hints when no children are provided.',
  },
  props: [
    {
      name: 'children',
      type: 'ReactNode',
      description:
        'Custom footer content. When omitted, renders default keyboard hints via Kbd.',
    },
    {
      name: 'xstyle',
      type: 'StyleXStyles',
      description:
        'StyleX styles for layout customization. Must be a stylex.create() value.',
    },
  ],
  examples: ['CommandPaletteFooterBasic', 'CommandPaletteFooterShowcase'],
  notes: [
    'Generated wrapper: Tecton publishes this component with its behaviour unchanged, under Tecton names and with Tecton glyphs on its icon props.',
  ],
};
