/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
export {CommandPaletteFooter} from './CommandPaletteFooter.js';
export type {CommandPaletteFooterProps} from './CommandPaletteFooter.js';
