/**
 * Tecton TopNavMegaMenu.
 *
 * Navigation item that displays a full-width mega menu panel on hover. Uses
 * a slots API with items and featured props. TopNavMegaMenuItem renders
 * itself in both desktop and mobile drawer modes. Supports inline
 * collapsible drawer via render mode context.
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {TopNavMegaMenu as BaseTopNavMegaMenu} from '@astryxdesign/core/TopNav';

type TopNavMegaMenuBaseProps = ComponentProps<typeof BaseTopNavMegaMenu>;

/** Props for {@link TopNavMegaMenu}. */
export type TopNavMegaMenuProps = TopNavMegaMenuBaseProps;

export function TopNavMegaMenu(props: TopNavMegaMenuProps) {
  return <BaseTopNavMegaMenu {...props} />;
}

TopNavMegaMenu.displayName = 'TopNavMegaMenu';
