/**
 * Tecton DateInput.
 *
 * DateInput lets the user type or pick a date from a calendar popover. Use
 * it for scheduling, deadlines, booking dates, or any form field that needs
 * a specific calendar date.
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {DateInput as BaseDateInput} from '@astryxdesign/core/DateInput';

type DateInputBaseProps = ComponentProps<typeof BaseDateInput>;

/** Props for {@link DateInput}. */
export type DateInputProps = DateInputBaseProps;

export function DateInput(props: DateInputProps) {
  return <BaseDateInput {...props} />;
}

DateInput.displayName = 'DateInput';
