/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
import {describe, expect, it} from 'vitest';
import {DateInput} from './DateInput.js';

describe('DateInput', () => {
  it('is a component', () => {
    expect(typeof DateInput).toBe('function');
  });

  it('names itself for the React tree', () => {
    expect(DateInput.displayName).toBe('DateInput');
  });
});
