/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
import {describe, expect, it} from 'vitest';
import {ChatComposer} from './ChatComposer.js';

describe('ChatComposer', () => {
  it('is a component', () => {
    expect(typeof ChatComposer).toBe('function');
  });

  it('names itself for the React tree', () => {
    expect(ChatComposer.displayName).toBe('ChatComposer');
  });
});
