/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
export {ChatComposer} from './ChatComposer.js';
export type {ChatComposerProps} from './ChatComposer.js';
