/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
export {LayoutHeader} from './LayoutHeader.js';
export type {LayoutHeaderProps} from './LayoutHeader.js';
