/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
import {describe, expect, it} from 'vitest';
import {LayoutHeader} from './LayoutHeader.js';

describe('LayoutHeader', () => {
  it('is a component', () => {
    expect(typeof LayoutHeader).toBe('function');
  });

  it('names itself for the React tree', () => {
    expect(LayoutHeader.displayName).toBe('LayoutHeader');
  });
});
