/**
 * Tecton LayoutHeader.
 *
 * Top bar for page titles, app bars, and toolbars.
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {LayoutHeader as BaseLayoutHeader} from '@astryxdesign/core/Layout';

type LayoutHeaderBaseProps = ComponentProps<typeof BaseLayoutHeader>;

/** Props for {@link LayoutHeader}. */
export type LayoutHeaderProps = LayoutHeaderBaseProps;

export function LayoutHeader(props: LayoutHeaderProps) {
  return <BaseLayoutHeader {...props} />;
}

LayoutHeader.displayName = 'LayoutHeader';
