/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
/** @type {import('@tecton/docs').ComponentDoc} */
export const docs = {
  name: 'Blockquote',
  displayName: 'Blockquote',
  group: 'Blockquote',
  category: 'Content',
  keywords: [
    'blockquote',
    'quote',
    'citation',
    'pullquote',
    'quotation',
    'cite',
    'excerpt',
  ],
  usage: {
    description:
      'A quotation block with a rule on its inline-start edge and secondary text color. Use to highlight quoted content, testimonials, or excerpts. The rule and padding are logical, so they move to the right edge in right-to-left locales.',
    bestPractices: [
      {
        guidance: true,
        description:
          'Use for quoted text, testimonials, or highlighted excerpts from external sources.',
      },
      {
        guidance: true,
        description:
          'Provide a cite prop when the source of the quote is known.',
      },
      {
        guidance: true,
        description:
          'Pass the source through cite rather than typing it into children, so it renders as a semantic <cite> element that assistive technology can distinguish from the quotation.',
      },
      {
        guidance: false,
        description:
          'Use for callout boxes or informational notes; use Alert for those.',
      },
      {
        guidance: false,
        description:
          'Wrap the attribution in your own <footer>. A <footer> inside a <blockquote> becomes a contentinfo document landmark, and a page with several quotes then reports several page footers.',
      },
    ],
    anatomy: [
      {
        name: 'Rule',
        required: true,
        description:
          'The border on the inline-start edge, drawn with --color-border-emphasized.',
      },
      {
        name: 'Quotation',
        required: true,
        description:
          'The quoted content, passed as children. Renders inside the <blockquote> element.',
      },
      {
        name: 'Attribution',
        required: false,
        description:
          'The source, passed as cite. Renders as a <cite> element below the quotation.',
      },
    ],
  },
  props: [
    {
      name: 'children',
      type: 'ReactNode',
      description: 'Content of the blockquote.',
      required: true,
    },
    {
      name: 'cite',
      type: 'ReactNode',
      description:
        'Optional attribution for the quote. Rendered in a <cite> element after the quoted content.',
    },
    {
      name: 'xstyle',
      type: 'StyleXStyles',
      description:
        'StyleX styles for layout customization (margins, positioning, sizing). Must be a stylex.create() value, not an inline style object like style={{}}.',
    },
  ],
  examples: [],
  notes: [
    'Generated wrapper: Tecton publishes this component with its behaviour unchanged, under Tecton names and with Tecton glyphs on its icon props.',
  ],
};
