/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
import {describe, expect, it} from 'vitest';
import {Blockquote} from './Blockquote.js';

describe('Blockquote', () => {
  it('is a component', () => {
    expect(typeof Blockquote).toBe('function');
  });

  it('names itself for the React tree', () => {
    expect(Blockquote.displayName).toBe('Blockquote');
  });
});
