/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
export {Blockquote} from './Blockquote.js';
export type {BlockquoteProps} from './Blockquote.js';
