/**
 * Tecton Section.
 *
 * Section is the correct way to create page regions and group related
 * content on a page. Use it for settings groups, form sections, sidebar
 * areas, or any time you need visual separation between parts of a page. If
 * you are tempted to use a Card for a page section, use Section instead.
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {Section as BaseSection} from '@astryxdesign/core/Section';

type SectionBaseProps = ComponentProps<typeof BaseSection>;

/** Props for {@link Section}. */
export type SectionProps = SectionBaseProps;

export function Section(props: SectionProps) {
  return <BaseSection {...props} />;
}

Section.displayName = 'Section';
