/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
export {StackItem} from './StackItem.js';
export type {StackItemProps} from './StackItem.js';
