/**
 * Tecton StackItem.
 *
 * StackItem is published as part of the Tecton surface.
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {StackItem as BaseStackItem} from '@astryxdesign/core/Layout';

type StackItemBaseProps = ComponentProps<typeof BaseStackItem>;

/** Props for {@link StackItem}. */
export type StackItemProps = StackItemBaseProps;

export function StackItem(props: StackItemProps) {
  return <BaseStackItem {...props} />;
}

StackItem.displayName = 'StackItem';
