/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
import {describe, expect, it} from 'vitest';
import {StackItem} from './StackItem.js';

describe('StackItem', () => {
  it('is a component', () => {
    expect(typeof StackItem).toBe('function');
  });

  it('names itself for the React tree', () => {
    expect(StackItem.displayName).toBe('StackItem');
  });
});
