/**
 * Tecton SideNavItem.
 *
 * Navigation item with icon, selected state, optional end content, and
 * nesting support via children.
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {SideNavItem as BaseSideNavItem} from '@astryxdesign/core/SideNav';
import {tectonIconValue, type TectonIconRef} from '../../icons/renderIcon.js';

type SideNavItemBaseProps = ComponentProps<typeof BaseSideNavItem>;

/** Props for {@link SideNavItem}. */
export interface SideNavItemProps extends Omit<
  SideNavItemBaseProps,
  'icon' | 'selectedIcon'
> {
  /**
   * Icon displayed in the outline (unselected) variant. Takes a Tecton
   * glyph name or an SVG component.
   */
  icon?: TectonIconRef | SideNavItemBaseProps['icon'];
  /**
   * Icon displayed when the item is selected (filled variant). Takes a
   * Tecton glyph name or an SVG component.
   */
  selectedIcon?: TectonIconRef | SideNavItemBaseProps['selectedIcon'];
}

export function SideNavItem({icon, selectedIcon, ...rest}: SideNavItemProps) {
  return (
    <BaseSideNavItem
      {...(rest as SideNavItemBaseProps)}
      icon={tectonIconValue(icon) as SideNavItemBaseProps['icon']}
      selectedIcon={
        tectonIconValue(selectedIcon) as SideNavItemBaseProps['selectedIcon']
      }
    />
  );
}

SideNavItem.displayName = 'SideNavItem';
