/**
 * Tecton SideNavItem.
 *
 * Navigation item with icon, selected state, optional end content, and
 * nesting support via children.
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {SideNavItem as BaseSideNavItem} from '@astryxdesign/core/SideNav';
import {resolveIcon, type TectonIconRef} from '../../icons/renderIcon.js';

type SideNavItemBaseProps = ComponentProps<typeof BaseSideNavItem>;

/** Props for {@link SideNavItem}. */
export interface SideNavItemProps extends Omit<
  SideNavItemBaseProps,
  'icon' | 'selectedIcon'
> {
  /**
   * Icon displayed in the outline (unselected) variant. Takes a Tecton
   * glyph name or an SVG component.
   */
  icon?: TectonIconRef;
  /**
   * Icon displayed when the item is selected (filled variant). Takes a
   * Tecton glyph name or an SVG component.
   */
  selectedIcon?: TectonIconRef;
}

export function SideNavItem({icon, selectedIcon, ...rest}: SideNavItemProps) {
  return (
    <BaseSideNavItem
      {...(rest as SideNavItemBaseProps)}
      icon={resolveIcon(icon)}
      selectedIcon={resolveIcon(selectedIcon)}
    />
  );
}

SideNavItem.displayName = 'SideNavItem';
