/**
 * Tecton CommandPaletteList.
 *
 * Scrollable results container. Renders as a listbox for ARIA. Contains
 * CommandPaletteItem and CommandPaletteGroup children.
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {CommandPaletteList as BaseCommandPaletteList} from '@astryxdesign/core/CommandPalette';

type CommandPaletteListBaseProps = ComponentProps<
  typeof BaseCommandPaletteList
>;

/** Props for {@link CommandPaletteList}. */
export type CommandPaletteListProps = CommandPaletteListBaseProps;

export function CommandPaletteList(props: CommandPaletteListProps) {
  return <BaseCommandPaletteList {...props} />;
}

CommandPaletteList.displayName = 'CommandPaletteList';
