/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
export {CommandPaletteList} from './CommandPaletteList.js';
export type {CommandPaletteListProps} from './CommandPaletteList.js';
