/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
/** @type {import('@tecton/docs').ComponentDoc} */
export const docs = {
  name: 'SideNavHeading',
  displayName: 'SideNavHeading',
  group: 'SideNav',
  category: 'Navigation',
  keywords: ['sidenavheading'],
  usage: {
    description:
      'Product/suite/account heading with smart interaction boundary logic for links and a menu popover.',
  },
  props: [
    {
      name: 'heading',
      type: 'string',
      description: 'Product/app name.',
      required: true,
    },
    {
      name: 'icon',
      type: 'ReactNode',
      description: 'Product/app icon.',
    },
    {
      name: 'headingHref',
      type: 'string',
      description: 'Link for the heading.',
    },
    {
      name: 'superheading',
      type: 'string',
      description: 'Text above the heading.',
    },
    {
      name: 'superheadingHref',
      type: 'string',
      description: 'Link for the superheading.',
    },
    {
      name: 'subheading',
      type: 'string',
      description: 'Text below the heading.',
    },
    {
      name: 'subheadingHref',
      type: 'string',
      description: 'Link for the subheading.',
    },
    {
      name: 'menu',
      type: 'ReactNode',
      description: 'Menu content rendered inside a popover.',
    },
    {
      name: 'headerEndContent',
      type: 'ReactNode',
      description:
        'Content rendered at the trailing edge of the heading row, between text and chevron. Useful for badges, status indicators, or compact action buttons. Hidden when collapsed.',
    },
  ],
  examples: ['SideNavHeadingBasic', 'SideNavHeadingShowcase'],
  notes: [
    'Generated wrapper: Tecton publishes this component with its behaviour unchanged, under Tecton names and with Tecton glyphs on its icon props.',
  ],
};
