/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
import {describe, expect, it} from 'vitest';
import {SideNavHeading} from './SideNavHeading.js';

describe('SideNavHeading', () => {
  it('is a component', () => {
    expect(typeof SideNavHeading).toBe('function');
  });

  it('names itself for the React tree', () => {
    expect(SideNavHeading.displayName).toBe('SideNavHeading');
  });
});
