/**
 * Tecton SideNavHeading.
 *
 * Product/suite/account heading with smart interaction boundary logic for
 * links and a menu popover.
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {SideNavHeading as BaseSideNavHeading} from '@astryxdesign/core/SideNav';
import {tectonIconNode, type TectonIconRef} from '../../icons/renderIcon.js';

type SideNavHeadingBaseProps = ComponentProps<typeof BaseSideNavHeading>;

/** Props for {@link SideNavHeading}. */
export interface SideNavHeadingProps extends Omit<
  SideNavHeadingBaseProps,
  'icon'
> {
  /**
   * Product/app icon. Takes a Tecton glyph name or an SVG component.
   */
  icon?: TectonIconRef | SideNavHeadingBaseProps['icon'];
}

export function SideNavHeading({icon, ...rest}: SideNavHeadingProps) {
  return (
    <BaseSideNavHeading
      {...(rest as SideNavHeadingBaseProps)}
      icon={tectonIconNode(icon) as SideNavHeadingBaseProps['icon']}
    />
  );
}

SideNavHeading.displayName = 'SideNavHeading';
