/**
 * Tecton SideNav.
 *
 * A sidebar navigation component for organizing application pages with
 * sections, nested items, and icons. Use SideNav as the primary navigation
 * when an app has 5 or more destinations or requires hierarchical grouping.
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {SideNav as BaseSideNav} from '@astryxdesign/core/SideNav';

type SideNavBaseProps = ComponentProps<typeof BaseSideNav>;

/** Props for {@link SideNav}. */
export type SideNavProps = SideNavBaseProps;

export function SideNav(props: SideNavProps) {
  return <BaseSideNav {...props} />;
}

SideNav.displayName = 'SideNav';
