/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
/** @type {import('@tecton/docs').ComponentDoc} */
export const docs = {
  name: 'SideNav',
  displayName: 'SideNav',
  group: 'SideNav',
  category: 'Navigation',
  keywords: [
    'sidenav',
    'sidebar',
    'navigation',
    'drawer',
    'menu',
    'nav',
    'aside',
    'sidemenu',
    'navmenu',
    'sider',
    'treeview',
  ],
  usage: {
    description:
      'A sidebar navigation component for organizing application pages with sections, nested items, and icons. Use SideNav as the primary navigation when an app has 5 or more destinations or requires hierarchical grouping.',
    bestPractices: [
      {
        guidance: true,
        description:
          'Use sections to group related navigation items and help users scan for their destination.',
      },
      {
        guidance: true,
        description:
          'Pair outline and filled icon variants so the selected state is visually distinct.',
      },
      {
        guidance: true,
        description:
          'Mark the current page with isSelected: it sets aria-current="page", so the current destination is announced rather than carried by color alone.',
      },
      {
        guidance: true,
        description:
          'SideNav renders a navigation landmark, and a collapsible item follows the WAI-ARIA APG Disclosure pattern (https://www.w3.org/WAI/ARIA/apg/patterns/disclosure/): the toggle carries aria-expanded and aria-controls, and the group it owns is inert while collapsed. Keep item labels short; they name icon-only items unless a meaningful aria-label supplies more context.',
      },
      {
        guidance: true,
        description:
          'While the nav is collapsed, an item with children shows them in a submenu flyout. On a device that can hover, pointing at the item opens it after a short delay and moving away closes it; a flyout opened by clicking stays open until it is dismissed. On touch, it opens on tap. Do not put an action in there that has no other route to it.',
      },
      {
        guidance: false,
        description:
          'Include a SideNavHeading when a TopNav is already providing app identity; this duplicates branding.',
      },
      {
        guidance: false,
        description:
          'Use for filtering content; use tabs or filter buttons instead.',
      },
    ],
    anatomy: [
      {
        name: 'Product icon and name',
        required: false,
        description: 'Branding area at the top of the nav.',
      },
      {
        name: 'Navigation items',
        required: true,
        description: 'Sections and groups of navigable links.',
      },
      {
        name: 'Collapse/expand toggle',
        required: false,
        description: 'Toggle to collapse or expand the side nav.',
      },
    ],
  },
  props: [
    {
      name: 'header',
      type: 'ReactNode',
      description: 'Header area (typically SideNavHeading). Sticky.',
    },
    {
      name: 'topContent',
      type: 'ReactNode',
      description: 'Content below the header, e.g., a create button.',
    },
    {
      name: 'children',
      type: 'ReactNode',
      description: 'Navigation sections and items. Scrollable.',
    },
    {
      name: 'footer',
      type: 'ReactNode',
      description: 'Footer area above the icon bar.',
    },
    {
      name: 'footerIcons',
      type: 'ReactNode',
      description:
        "Footer icon bar. The row cascades a 'sm' size to the interactive children it contains, so its icons and the built-in collapse button come out one height; pass an explicit size on a child to opt out.",
    },
    {
      name: 'collapsible',
      type: 'boolean | { defaultIsCollapsed?: boolean; isCollapsed?: boolean; onCollapsedChange?: (isCollapsed: boolean) => void; hasButton?: boolean; buttonLabel?: string }',
      description:
        'Enables collapse behavior. true for uncontrolled with default toggle button, or an object for controlled mode and advanced config (defaultIsCollapsed, isCollapsed + onCollapsedChange, hasButton, buttonLabel). A controlled config can also be passed to a SideNavCollapseButton rendered outside this SideNav, so both share one state.',
      default: 'false',
    },
    {
      name: 'resizable',
      type: 'boolean | { defaultWidth?: number; minWidth?: number; maxWidth?: number; autoSaveId?: string; onWidthChange?: (width: number) => void; defaultIsCollapsed?: boolean; isCollapsed?: boolean; onCollapseChange?: (isCollapsed: boolean) => void }',
      description:
        'Enables a resize handle at the inline-end edge. true for defaults (260px initial, 180-480px range), or a ResizableConfig object (defaultWidth, minWidth, maxWidth, autoSaveId for localStorage persistence of width and collapse state, onWidthChange). It can also own collapse state (defaultIsCollapsed, isCollapsed + onCollapseChange); when both props carry collapse state, resizable wins and a dev warning names the conflicting keys. The handle is hidden while collapsed.',
      default: 'false',
    },
    {
      name: 'handleRef',
      type: 'Ref<SideNavImperativeCollapseHandle>',
      description:
        'Deprecated. Imperative collapse handle for SideNavCollapseButton instances rendered outside this SideNav; hand both the same controlled collapsible config instead. Separate from `ref`, which continues to expose the root HTMLElement.',
    },
    {
      name: 'xstyle',
      type: 'StyleXStyles',
      description:
        'StyleX styles for layout customization (margins, positioning, sizing). Must be a stylex.create() value: not an inline style object like style={{}}.',
    },
  ],
  examples: [
    'SideNavEndContent',
    'SideNavNestedItems',
    'SideNavShowcase',
    'SideNavWithHeaderMenu',
  ],
  notes: [
    'Generated wrapper: Tecton publishes this component with its behaviour unchanged, under Tecton names and with Tecton glyphs on its icon props.',
  ],
};
