/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
import {describe, expect, it} from 'vitest';
import {TableHeader} from './TableHeader.js';

describe('TableHeader', () => {
  it('is a component', () => {
    expect(typeof TableHeader).toBe('function');
  });

  it('names itself for the React tree', () => {
    expect(TableHeader.displayName).toBe('TableHeader');
  });
});
