/**
 * Tecton ComplexSelector.
 *
 * Use ComplexSelector when a selection needs richer custom content than a
 * Select option row. It is intentionally one component: ComplexSelector owns
 * the field, trigger, popover, focus restore, and changeAction flow, while
 * the content render prop owns the selector-specific accessible structure.
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {ComplexSelector as BaseComplexSelector} from '@astryxdesign/core/ComplexSelector';

type ComplexSelectorBaseProps = ComponentProps<typeof BaseComplexSelector>;

/** Props for {@link ComplexSelector}. */
export type ComplexSelectorProps = ComplexSelectorBaseProps;

export function ComplexSelector(props: ComplexSelectorProps) {
  return <BaseComplexSelector {...props} />;
}

ComplexSelector.displayName = 'ComplexSelector';
