/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
/** @type {import('@tecton/docs').ComponentDoc} */
export const docs = {
  name: 'ComplexSelector',
  displayName: 'ComplexSelector',
  group: 'ComplexSelector',
  category: 'Forms',
  keywords: [
    'selector',
    'picker',
    'popover',
    'dialog',
    'custom',
    'rich',
    'matrix',
    'grid',
  ],
  usage: {
    description:
      'Use ComplexSelector when a selection needs richer custom content than a Select option row. It is intentionally one component: ComplexSelector owns the field, trigger, popover, focus restore, and changeAction flow, while the content render prop owns the selector-specific accessible structure.',
    bestPractices: [
      {
        guidance: true,
        description:
          'Use variant="ghost" with a startIcon when the selector is triggered from a toolbar. Use alignment="end" when a wide surface should align its end edge to the trigger.',
      },
      {
        guidance: true,
        description:
          'For staged editors, keep draft state in the composed content and call the provided onChange helper only from Apply. Cancel or dismiss without committing.',
      },
      {
        guidance: true,
        description:
          'Compose the dialog content from the appropriate accessible structure for the job: RadioGroup for a simple choice, Calendar/date inputs for date picking, TreeView or a searchable list for hierarchy, or a custom grid when two-dimensional arrow navigation is useful.',
      },
      {
        guidance: true,
        description:
          'Use the provided onChange helper from children; it already calls both onChange and changeAction and updates optimistic busy state.',
      },
      {
        guidance: true,
        description:
          'Call close() from custom content when a selection should dismiss the popup. Keep it open for multi-step content or freeform entry flows.',
      },
      {
        guidance: true,
        description: '',
      },
      {
        guidance: true,
        description:
          'Evaluate custom content against WCAG 2.2: keyboard operation, focus visible/not obscured, names and roles, labels/instructions, target size, and contrast/non-text contrast are especially relevant for selector popovers.',
      },
      {
        guidance: false,
        description:
          'Do not rebuild trigger ARIA, popover focus management, or changeAction handling in product code.',
      },
      {
        guidance: false,
        description:
          'Do not use ComplexSelector for a plain single-column text list; use Select instead.',
      },
    ],
    anatomy: [
      {
        name: 'Field',
        required: true,
        description:
          'Field shell that provides the label and optional supporting field content.',
      },
      {
        name: 'Trigger',
        required: true,
        description:
          'Control that displays the current value or placeholder and opens the popup.',
      },
      {
        name: 'Icon-rendered start icon',
        required: false,
        description:
          'Optional leading semantic icon or icon component rendered through Icon.',
      },
      {
        name: 'Caller-rendered start content',
        required: false,
        description:
          'Optional arbitrary React content rendered directly at the start of the trigger.',
      },
      {
        name: 'Indicator icon',
        required: true,
        description:
          'Trailing chevron that rotates to reflect whether the popup is open.',
      },
      {
        name: 'Popup',
        required: true,
        description:
          'Mounted dialog surface that is painted and shown while open and hidden while closed.',
      },
    ],
  },
  props: [],
  examples: ['ComplexSelectorDeadlinePicker', 'ComplexSelectorTreeSearch'],
  notes: [
    'Generated wrapper: Tecton publishes this component with its behaviour unchanged, under Tecton names and with Tecton glyphs on its icon props.',
  ],
};
