/**
 * Tecton ScrollableArea.
 *
 * Provides a native scroll viewport and a real observed content box. The
 * viewport enters the tab order only while a requested logical axis is
 * effectively scrollable, and containment applies only to effective axes.
 *
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 */
import type {ComponentProps} from 'react';
import {ScrollableArea as BaseScrollableArea} from '@astryxdesign/core/ScrollableArea';

type ScrollableAreaBaseProps = ComponentProps<typeof BaseScrollableArea>;

/** Props for {@link ScrollableArea}. */
export type ScrollableAreaProps = ScrollableAreaBaseProps;

export function ScrollableArea(props: ScrollableAreaProps) {
  return <BaseScrollableArea {...props} />;
}

ScrollableArea.displayName = 'ScrollableArea';
