/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
/** @type {import('@tecton/docs').ComponentDoc} */
export const docs = {
  name: 'CommandPaletteEmpty',
  displayName: 'CommandPaletteEmpty',
  group: 'CommandPalette',
  category: 'Overlay',
  keywords: ['commandpaletteempty'],
  usage: {
    description:
      'Empty state display for the results area. Rendered automatically by CommandPalette for no-results and no-query states.',
  },
  props: [
    {
      name: 'children',
      type: 'ReactNode',
      description: 'Message or content to display.',
      required: true,
    },
  ],
  examples: [],
  notes: [
    'Generated wrapper: Tecton publishes this component with its behaviour unchanged, under Tecton names and with Tecton glyphs on its icon props.',
  ],
};
