/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
export {CommandPaletteEmpty} from './CommandPaletteEmpty.js';
export type {CommandPaletteEmptyProps} from './CommandPaletteEmpty.js';
