/**
 * @generated by packages/react/scripts/generate-wrappers.mjs — do not edit.
 * Regenerate with `pnpm --filter @tecton/react generate:wrappers`.
 */
export {InputGroupText} from './InputGroupText.js';
export type {InputGroupTextProps} from './InputGroupText.js';
